// Code generated by stylegen; DO NOT EDIT.

package canonical

import "github.com/gsxhq/gsxui/internal/recipe"

// avatarRecipe is avatar's typed slot accessor set.
type avatarRecipe struct{ c recipe.Component }

func (r avatarRecipe) Root() string { return r.c.SlotClass("") }

func (r avatarRecipe) Fallback() string { return r.c.SlotClass("fallback") }

func (r avatarRecipe) Image() string { return r.c.SlotClass("image") }
