// Code generated by stylegen; DO NOT EDIT.

package canonical

import "github.com/gsxhq/gsxui/internal/recipe"

// comboboxRecipe is combobox's typed slot accessor set.
type comboboxRecipe struct{ c recipe.Component }

func (r comboboxRecipe) Root() string { return r.c.SlotClass("") }

func (r comboboxRecipe) Clear() string { return r.c.SlotClass("clear") }

func (r comboboxRecipe) Content() string { return r.c.SlotClass("content") }

func (r comboboxRecipe) Empty() string { return r.c.SlotClass("empty") }

func (r comboboxRecipe) InputGroup() string { return r.c.SlotClass("input-group") }

func (r comboboxRecipe) Item() string { return r.c.SlotClass("item") }

func (r comboboxRecipe) ItemIndicator() string { return r.c.SlotClass("item-indicator") }

func (r comboboxRecipe) Label() string { return r.c.SlotClass("label") }

func (r comboboxRecipe) List() string { return r.c.SlotClass("list") }

func (r comboboxRecipe) Separator() string { return r.c.SlotClass("separator") }

func (r comboboxRecipe) Trigger() string { return r.c.SlotClass("trigger") }

func (r comboboxRecipe) TriggerIcon() string { return r.c.SlotClass("trigger-icon") }
