// Code generated by stylegen; DO NOT EDIT.

package canonical

import "github.com/gsxhq/gsxui/internal/recipe"

// dialogRecipe is dialog's typed slot accessor set.
type dialogRecipe struct{ c recipe.Component }

func (r dialogRecipe) Root() string { return r.c.SlotClass("") }

func (r dialogRecipe) CloseButton() string { return r.c.SlotClass("close-button") }

func (r dialogRecipe) CloseIcon() string { return r.c.SlotClass("close-icon") }

func (r dialogRecipe) Content() string { return r.c.SlotClass("content") }

func (r dialogRecipe) Description() string { return r.c.SlotClass("description") }

func (r dialogRecipe) Footer() string { return r.c.SlotClass("footer") }

func (r dialogRecipe) Header() string { return r.c.SlotClass("header") }

func (r dialogRecipe) Title() string { return r.c.SlotClass("title") }
