// Code generated by stylegen; DO NOT EDIT.

package canonical

import "github.com/gsxhq/gsxui/internal/recipe"

// inputGroupRecipe is input-group's typed slot accessor set.
type inputGroupRecipe struct{ c recipe.Component }

func (r inputGroupRecipe) Root() string { return r.c.SlotClass("") }

func (r inputGroupRecipe) Addon() string { return r.c.SlotClass("addon") }

func (r inputGroupRecipe) AddonAlign(value string) string {
	return r.c.SlotValueClass("addon", "align", value)
}

func (r inputGroupRecipe) Control() string { return r.c.SlotClass("control") }

func (r inputGroupRecipe) Text() string { return r.c.SlotClass("text") }
