// Code generated by gsx; DO NOT EDIT.

package canonical

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxstd "github.com/gsxhq/gsx/std"
	_gsxcm "github.com/gsxhq/gsxui/merge"
	_gsxio "io"
)

//line item.gsx:12:1
func ItemGroup(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:13:2
		_gsxgw.S("<div class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(item.Group()), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		if !attrs.Has("role") {
			_gsxgw.S(" role=\"list\"")
		}
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-item-group"})
		_gsxgw.BoolAttr("data-gsxui-slot-item-group", true)
		_gsxgw.S(">")
//line item.gsx:14:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line item.gsx:18:1
// ItemSeparator composes ui.Separator directly (flat package, no
// re-implementation) — the item -> separator dependency internal/registry
// derives and registry_test.go pins. shadcn's own version types its props as
// React.ComponentProps<typeof Separator> and spreads {...props} after its
// explicit orientation="horizontal", so a caller-supplied orientation prop
// wins there. `orientation` here is a real Go param (not left to attrs) for
// exactly that reason: attrs is untyped fallthrough onto Separator's own
// rendered <div>, not a hook into the orientation argument compiled into the
// call to Separator, so only an explicit param can actually override it —
// same competing-defaults mechanism as ButtonGroupSeparator's own
// orientation |> default("vertical").

//line item.gsx:29:1
func ItemSeparator(orientation string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:30:2
		_gsxgw.NodeResult(_gsxrenderSeparator(ctx, _gsxgw, _gsxstd.Default((orientation), "horizontal"), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.Class(item.Separator()))}}, attrs, _gsxrt.Attrs{{Key: "data-gsxui-slot-item-separator", Value: _gsxrt.Toggle(true)}})))
		return _gsxgw.Err()
	})
}

//line item.gsx:38:1
// Item's variant/size cva map (itemVariants) picks between static class
// blocks by the JS-resolved prop values — no data-[variant=...]/
// data-[size=...] selectors in registry/new-york-v4/ui/item.tsx to preserve,
// so both are reflected as explicit data attributes for the style pack.
//
// asChild tag-swapping is dropped — always renders a <div> — the same
// narrow gap as button's own asChild (see docs/jsx-parity.md ## button).

//line item.gsx:45:1
func Item(variant string, size string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:46:2
		_gsxgw.S("<div")
		if !attrs.Has("data-variant") {
			_gsxgw.S(" data-variant=\"")
			_gsxgw.AttrValue(string(_gsxstd.Default((variant), "default")))
			_gsxgw.S("\"")
		}
		if !attrs.Has("data-size") {
			_gsxgw.S(" data-size=\"")
			_gsxgw.AttrValue(string(_gsxstd.Default((size), "default")))
			_gsxgw.S("\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(item.Root()), _gsxrt.Class(item.Variant(variant)), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-item"})
		_gsxgw.BoolAttr("data-gsxui-slot-item", true)
		_gsxgw.S(">")
//line item.gsx:56:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line item.gsx:60:1
// ItemMedia's variant cva map (itemMediaVariants) is reflected through
// data-variant for the style pack.
//
// Retargeted to nova density (2026-07-24 nova density map, `## item`).
// DEVIATION: nova's icon-media variant drops the bordered/muted size-8 box
// entirely (bare 1rem svg, no container) and the image variant gains
// ancestor-size responsive sizing tied to a `size=xs` axis this
// package doesn't ship — both left as-is here: the box drop bundles a
// color/border removal (border, bg-muted) the retarget is scoped to leave
// alone, and the responsive image sizing is half dead weight without a real
// xs size param (Item's `size` axis stays sm/default only, per task scope).

//line item.gsx:71:1
func ItemMedia(variant string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:72:2
		_gsxgw.S("<div")
		if !attrs.Has("data-variant") {
			_gsxgw.S(" data-variant=\"")
			_gsxgw.AttrValue(string(_gsxstd.Default((variant), "default")))
			_gsxgw.S("\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(item.Media()), _gsxrt.Class(item.MediaVariant(variant)), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-item-media"})
		_gsxgw.BoolAttr("data-gsxui-slot-item-media", true)
		_gsxgw.S(">")
//line item.gsx:81:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line item.gsx:85:1
func ItemContent(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:86:2
		_gsxgw.S("<div class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(item.Content()), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-item-content"})
		_gsxgw.BoolAttr("data-gsxui-slot-item-content", true)
		_gsxgw.S(">")
//line item.gsx:87:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line item.gsx:91:1
func ItemTitle(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:92:2
		_gsxgw.S("<div class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(item.Title()), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-item-title"})
		_gsxgw.BoolAttr("data-gsxui-slot-item-title", true)
		_gsxgw.S(">")
//line item.gsx:93:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line item.gsx:97:1
// ItemDescription renders a real <p>, matching shadcn's own source exactly
// (unlike EmptyDescription, whose type says "p" but whose element is a
// <div> — see empty.gsx).

//line item.gsx:100:1
func ItemDescription(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:101:2
		_gsxgw.S("<p class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(item.Description()), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "p", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-item-description"})
		_gsxgw.BoolAttr("data-gsxui-slot-item-description", true)
		_gsxgw.S(">")
//line item.gsx:102:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</p>")
		return _gsxgw.Err()
	})
}

//line item.gsx:106:1
func ItemActions(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:107:2
		_gsxgw.S("<div class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(item.Actions()), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-item-actions"})
		_gsxgw.BoolAttr("data-gsxui-slot-item-actions", true)
		_gsxgw.S(">")
//line item.gsx:108:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line item.gsx:112:1
func ItemHeader(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:113:2
		_gsxgw.S("<div class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(item.Header()), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-item-header"})
		_gsxgw.BoolAttr("data-gsxui-slot-item-header", true)
		_gsxgw.S(">")
//line item.gsx:114:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line item.gsx:118:1
func ItemFooter(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:119:2
		_gsxgw.S("<div class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(item.Footer()), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-item-footer"})
		_gsxgw.BoolAttr("data-gsxui-slot-item-footer", true)
		_gsxgw.S(">")
//line item.gsx:120:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}
