// Code generated by stylegen; DO NOT EDIT.

package canonical

import "github.com/gsxhq/gsxui/internal/recipe"

// nativeSelectRecipe is native-select's typed slot accessor set.
type nativeSelectRecipe struct{ c recipe.Component }

func (r nativeSelectRecipe) Root() string { return r.c.SlotClass("") }

func (r nativeSelectRecipe) Wrapper() string { return r.c.SlotClass("wrapper") }
