// Code generated by stylegen; DO NOT EDIT.

package canonical

import "github.com/gsxhq/gsxui/internal/recipe"

// tableRecipe is table's typed slot accessor set.
type tableRecipe struct{ c recipe.Component }

func (r tableRecipe) Root() string { return r.c.SlotClass("") }

func (r tableRecipe) Caption() string { return r.c.SlotClass("caption") }

func (r tableRecipe) Cell() string { return r.c.SlotClass("cell") }

func (r tableRecipe) Container() string { return r.c.SlotClass("container") }

func (r tableRecipe) Footer() string { return r.c.SlotClass("footer") }

func (r tableRecipe) Head() string { return r.c.SlotClass("head") }

func (r tableRecipe) Row() string { return r.c.SlotClass("row") }
