// Code generated by gsx; DO NOT EDIT.

package canonical

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxcm "github.com/gsxhq/gsxui/merge"
	"github.com/gsxhq/gsxui/ui/icon"
	_gsxio "io"
)

//line toast.gsx:8:1
// Toast is the server-rendered toast card — the single source of truth for
// the toast <li> markup, and a standalone component: it is usable on its own
// (a server-rendered flash row, a static markup showcase) without Toaster.
// That is why it is registered separately rather than shipped as part of
// ui/toaster.gsx, matching upstream shadcn's split between the toast card and
// the toaster region.
//
// shadcn's own sonner.tsx renders nothing but a re-themed <Sonner>
// passthrough (the toast library owns 100% of the toast DOM from a
// non-Tailwind stylesheet), so there is no upstream markup to port. This is
// the ONE place the card is authored: ui/toaster.js clones a pre-rendered
// Toast (one per type, shipped as inert <template>s by Toaster) rather than
// building the card from JS string DOM — the old "icon paths hand-copied
// into a JS module" maintenance seam is gone (docs/jsx-parity.md ## sonner).
//
// toastType is one of default/success/info/warning/error/loading (the Go
// keyword `type` forces the param name); empty is normalised to "default".
// The type drives the icon (via ui/icon), the data-type styling axis, and
// the aria-live level: an error toast
// announces assertively, every other type politely. description/action/
// cancel are optional — an empty string renders the part absent, matching
// the JS `toast(msg, { description, action, cancel })` option surface; the
// action/cancel buttons carry dedicated behavior hooks ui/toaster.js wires
// clicks onto. A custom auto-dismiss is a data-duration attr passed
// through attrs (ui/toaster.js reads it on adoption; loading defaults to no
// auto-dismiss).

//line toast.gsx:34:1
func Toast(toastType string, title string, description string, action string, cancel string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderToast(ctx, _gsxgw, toastType, title, description, action, cancel, attrs)
	})
}

func _gsxrenderToast(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, toastType string, title string, description string, action string, cancel string, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line toast.gsx:35:2
	t := toastType
	if t == "" {
		t = "default"
	}
	ariaLive := "polite"
	if t == "error" {
		ariaLive = "assertive"
	}
//line toast.gsx:45:2
	_gsxgw.S("<li")
	if !attrs.Has("data-gsxui-toast") {
		_gsxgw.BoolAttr("data-gsxui-toast", true)
	}
	if !attrs.Has("data-type") {
		_gsxgw.S(" data-type=\"")
		_gsxgw.AttrValue(string(t))
		_gsxgw.S("\"")
	}
	if !attrs.Has("role") {
		_gsxgw.S(" role=\"status\"")
	}
	if !attrs.Has("aria-live") {
		_gsxgw.S(" aria-live=\"")
		_gsxgw.AttrValue(string(ariaLive))
		_gsxgw.S("\"")
	}
	if !attrs.Has("aria-atomic") {
		_gsxgw.S(" aria-atomic=\"true\"")
	}
	_gsxgw.S(" class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(toast.Root()), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, "li", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-toast"})
	_gsxgw.BoolAttr("data-gsxui-slot-toast", true)
	_gsxgw.S(">")
//line toast.gsx:55:3
	if t != "default" {
//line toast.gsx:56:4
		switch t {
		case "success":
//line toast.gsx:58:5
			_gsxgw.Node(ctx, icon.CircleCheck(_gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.Class(toast.Icon()))}}, _gsxrt.Attrs{{Key: "data-gsxui-toast-icon", Value: _gsxrt.Toggle(true)}}, _gsxrt.Attrs{{Key: "data-gsxui-slot-toast-icon", Value: _gsxrt.Toggle(true)}})...))
		case "info":
//line toast.gsx:60:5
			_gsxgw.Node(ctx, icon.Info(_gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.Class(toast.Icon()))}}, _gsxrt.Attrs{{Key: "data-gsxui-toast-icon", Value: _gsxrt.Toggle(true)}}, _gsxrt.Attrs{{Key: "data-gsxui-slot-toast-icon", Value: _gsxrt.Toggle(true)}})...))
		case "warning":
//line toast.gsx:62:5
			_gsxgw.Node(ctx, icon.TriangleAlert(_gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.Class(toast.Icon()))}}, _gsxrt.Attrs{{Key: "data-gsxui-toast-icon", Value: _gsxrt.Toggle(true)}}, _gsxrt.Attrs{{Key: "data-gsxui-slot-toast-icon", Value: _gsxrt.Toggle(true)}})...))
		case "error":
//line toast.gsx:64:5
			_gsxgw.Node(ctx, icon.OctagonX(_gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.Class(toast.Icon()))}}, _gsxrt.Attrs{{Key: "data-gsxui-toast-icon", Value: _gsxrt.Toggle(true)}}, _gsxrt.Attrs{{Key: "data-gsxui-slot-toast-icon", Value: _gsxrt.Toggle(true)}})...))
		case "loading":
//line toast.gsx:66:5
			_gsxgw.Node(ctx, icon.LoaderCircle(_gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.Class(toast.Icon()))}}, _gsxrt.Attrs{{Key: "data-gsxui-toast-icon", Value: _gsxrt.Toggle(true)}}, _gsxrt.Attrs{{Key: "data-gsxui-slot-toast-icon", Value: _gsxrt.Toggle(true)}})...))
		}
	}
//line toast.gsx:69:3
	_gsxgw.S("<div class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(toast.Content()))
	_gsxgw.S("\"")
	_gsxgw.BoolAttr("data-gsxui-slot-toast-content", true)
	_gsxgw.S(">")
//line toast.gsx:70:4
	_gsxgw.S("<div class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(toast.Title()))
	_gsxgw.S("\"")
	_gsxgw.BoolAttr("data-gsxui-toast-title", true)
	_gsxgw.BoolAttr("data-gsxui-slot-toast-title", true)
	_gsxgw.S(">")
//line toast.gsx:70:84
	_gsxgw.Text(string(title))
	_gsxgw.S("</div>")
//line toast.gsx:71:4
	if description != "" {
//line toast.gsx:72:5
		_gsxgw.S("<div class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(toast.Description()))
		_gsxgw.S("\"")
		_gsxgw.BoolAttr("data-gsxui-toast-description", true)
		_gsxgw.BoolAttr("data-gsxui-slot-toast-description", true)
		_gsxgw.S(">")
//line toast.gsx:72:103
		_gsxgw.Text(string(description))
		_gsxgw.S("</div>")
	}
	_gsxgw.S("</div>")
//line toast.gsx:75:3
	if action != "" {
//line toast.gsx:76:4
		_gsxgw.S("<button type=\"button\" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(toast.Action()))
		_gsxgw.S("\"")
		_gsxgw.BoolAttr("data-gsxui-toast-action", true)
		_gsxgw.BoolAttr("data-gsxui-slot-toast-action", true)
		_gsxgw.S(">")
//line toast.gsx:82:5
		_gsxgw.Text(string(action))
		_gsxgw.S("</button>")
	}
//line toast.gsx:85:3
	if cancel != "" {
//line toast.gsx:86:4
		_gsxgw.S("<button type=\"button\" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(toast.Cancel()))
		_gsxgw.S("\"")
		_gsxgw.BoolAttr("data-gsxui-toast-cancel", true)
		_gsxgw.BoolAttr("data-gsxui-slot-toast-cancel", true)
		_gsxgw.S(">")
//line toast.gsx:92:5
		_gsxgw.Text(string(cancel))
		_gsxgw.S("</button>")
	}
//line toast.gsx:95:3
	_gsxgw.S("<button type=\"button\" class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(toast.Close()))
	_gsxgw.S("\"")
	_gsxgw.BoolAttr("data-gsxui-toast-close", true)
	_gsxgw.S(" aria-label=\"Close\"")
	_gsxgw.BoolAttr("data-gsxui-slot-toast-close", true)
	_gsxgw.S(">")
//line toast.gsx:102:4
	_gsxgw.Node(ctx, icon.X(_gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.Class(toast.CloseIcon()))}}, _gsxrt.Attrs{{Key: "data-gsxui-slot-toast-close-icon", Value: _gsxrt.Toggle(true)}})...))
	_gsxgw.S("</button></li>")
	return _gsxgw.Err()
}
