// Code generated by stylegen; DO NOT EDIT.

package canonical

import "github.com/gsxhq/gsxui/internal/recipe"

// toastRecipe is toast's typed slot accessor set.
type toastRecipe struct{ c recipe.Component }

func (r toastRecipe) Root() string { return r.c.SlotClass("") }

func (r toastRecipe) Action() string { return r.c.SlotClass("action") }

func (r toastRecipe) Cancel() string { return r.c.SlotClass("cancel") }

func (r toastRecipe) Close() string { return r.c.SlotClass("close") }

func (r toastRecipe) CloseIcon() string { return r.c.SlotClass("close-icon") }

func (r toastRecipe) Content() string { return r.c.SlotClass("content") }

func (r toastRecipe) Description() string { return r.c.SlotClass("description") }

func (r toastRecipe) Icon() string { return r.c.SlotClass("icon") }

func (r toastRecipe) Title() string { return r.c.SlotClass("title") }
