// Package shapes holds every component's style interface as pure data.
//
// It is a leaf package on purpose. internal/stylegen imports it to read shapes
// and to GENERATE the per-slot accessors in registry/canonical — which cannot
// compile until those accessors exist. Keeping shapes here means the generator
// always has something that compiles to read from.
//
// Nothing here may import registry/canonical, and internal/recipe must never
// import this package.
package shapes

import (
	"maps"

	"github.com/gsxhq/gsxui/internal/recipe"
)

var all = map[string]recipe.Shape{
	Button.Component:         Button,
	Card.Component:           Card,
	Badge.Component:          Badge,
	Alert.Component:          Alert,
	Skeleton.Component:       Skeleton,
	Spinner.Component:        Spinner,
	Progress.Component:       Progress,
	Avatar.Component:         Avatar,
	Button.Component:         Button,
	Card.Component:           Card,
	Badge.Component:          Badge,
	Alert.Component:          Alert,
	Label.Component:          Label,
	AspectRatio.Component:    AspectRatio,
	Separator.Component:      Separator,
	Kbd.Component:            Kbd,
	Collapsible.Component:    Collapsible,
	Resizable.Component:      Resizable,
	Breadcrumb.Component:     Breadcrumb,
	Radio.Component:          Radio,
	ToggleGroup.Component:    ToggleGroup,
	ScrollArea.Component:     ScrollArea,
	Checkbox.Component:       Checkbox,
	Accordion.Component:      Accordion,
	Table.Component:          Table,
	InputOTP.Component:       InputOTP,
	Slider.Component:         Slider,
	Empty.Component:          Empty,
	Tabs.Component:           Tabs,
	Pagination.Component:     Pagination,
	Switch.Component:         Switch,
	Select.Component:         Select,
	Toggle.Component:         Toggle,
	Popover.Component:        Popover,
	HoverCard.Component:      HoverCard,
	Tooltip.Component:        Tooltip,
	Button.Component:         Button,
	Card.Component:           Card,
	Badge.Component:          Badge,
	Alert.Component:          Alert,
	Skeleton.Component:       Skeleton,
	Spinner.Component:        Spinner,
	Progress.Component:       Progress,
	Avatar.Component:         Avatar,
	Button.Component:         Button,
	Card.Component:           Card,
	Badge.Component:          Badge,
	Alert.Component:          Alert,
	Label.Component:          Label,
	AspectRatio.Component:    AspectRatio,
	Separator.Component:      Separator,
	Kbd.Component:            Kbd,
	Collapsible.Component:    Collapsible,
	Resizable.Component:      Resizable,
	Breadcrumb.Component:     Breadcrumb,
	Radio.Component:          Radio,
	ToggleGroup.Component:    ToggleGroup,
	ScrollArea.Component:     ScrollArea,
	Checkbox.Component:       Checkbox,
	Accordion.Component:      Accordion,
	Table.Component:          Table,
	InputOTP.Component:       InputOTP,
	Slider.Component:         Slider,
	Empty.Component:          Empty,
	Tabs.Component:           Tabs,
	Pagination.Component:     Pagination,
	Switch.Component:         Switch,
	Select.Component:         Select,
	Toggle.Component:         Toggle,
	DropdownMenu.Component:   DropdownMenu,
	ContextMenu.Component:    ContextMenu,
	Menubar.Component:        Menubar,
	NavigationMenu.Component: NavigationMenu,
	Button.Component:         Button,
	Card.Component:           Card,
	Badge.Component:          Badge,
	Alert.Component:          Alert,
	Skeleton.Component:       Skeleton,
	Spinner.Component:        Spinner,
	Progress.Component:       Progress,
	Avatar.Component:         Avatar,
	Button.Component:         Button,
	Card.Component:           Card,
	Badge.Component:          Badge,
	Alert.Component:          Alert,
	Label.Component:          Label,
	AspectRatio.Component:    AspectRatio,
	Separator.Component:      Separator,
	Kbd.Component:            Kbd,
	Collapsible.Component:    Collapsible,
	Resizable.Component:      Resizable,
	Breadcrumb.Component:     Breadcrumb,
	Radio.Component:          Radio,
	ToggleGroup.Component:    ToggleGroup,
	ScrollArea.Component:     ScrollArea,
	Checkbox.Component:       Checkbox,
	Accordion.Component:      Accordion,
	Table.Component:          Table,
	InputOTP.Component:       InputOTP,
	Slider.Component:         Slider,
	Empty.Component:          Empty,
	Tabs.Component:           Tabs,
	Pagination.Component:     Pagination,
	Switch.Component:         Switch,
	Select.Component:         Select,
	Toggle.Component:         Toggle,
	Textarea.Component:       Textarea,
	Button.Component:         Button,
	Card.Component:           Card,
	Badge.Component:          Badge,
	Alert.Component:          Alert,
	Skeleton.Component:       Skeleton,
	Spinner.Component:        Spinner,
	Progress.Component:       Progress,
	Avatar.Component:         Avatar,
	Button.Component:         Button,
	Card.Component:           Card,
	Badge.Component:          Badge,
	Alert.Component:          Alert,
	Label.Component:          Label,
	AspectRatio.Component:    AspectRatio,
	Separator.Component:      Separator,
	Kbd.Component:            Kbd,
	Collapsible.Component:    Collapsible,
	Resizable.Component:      Resizable,
	Breadcrumb.Component:     Breadcrumb,
	Radio.Component:          Radio,
	ToggleGroup.Component:    ToggleGroup,
	ScrollArea.Component:     ScrollArea,
	Checkbox.Component:       Checkbox,
	Accordion.Component:      Accordion,
	Table.Component:          Table,
	InputOTP.Component:       InputOTP,
	Slider.Component:         Slider,
	Empty.Component:          Empty,
	Tabs.Component:           Tabs,
	Pagination.Component:     Pagination,
	Switch.Component:         Switch,
	Select.Component:         Select,
	Toggle.Component:         Toggle,
	Textarea.Component:       Textarea,
	Input.Component:          Input,
	Button.Component:         Button,
	Card.Component:           Card,
	Badge.Component:          Badge,
	Alert.Component:          Alert,
	Skeleton.Component:       Skeleton,
	Spinner.Component:        Spinner,
	Progress.Component:       Progress,
	Avatar.Component:         Avatar,
	Button.Component:         Button,
	Card.Component:           Card,
	Badge.Component:          Badge,
	Alert.Component:          Alert,
	Label.Component:          Label,
	AspectRatio.Component:    AspectRatio,
	Separator.Component:      Separator,
	Kbd.Component:            Kbd,
	Collapsible.Component:    Collapsible,
	Resizable.Component:      Resizable,
	Breadcrumb.Component:     Breadcrumb,
	Radio.Component:          Radio,
	ToggleGroup.Component:    ToggleGroup,
	ScrollArea.Component:     ScrollArea,
	Checkbox.Component:       Checkbox,
	Accordion.Component:      Accordion,
	Table.Component:          Table,
	InputOTP.Component:       InputOTP,
	Slider.Component:         Slider,
	Empty.Component:          Empty,
	Tabs.Component:           Tabs,
	Pagination.Component:     Pagination,
	Switch.Component:         Switch,
	Select.Component:         Select,
	Toggle.Component:         Toggle,
	Textarea.Component:       Textarea,
	Input.Component:          Input,
	Dialog.Component:         Dialog,
	Command.Component:        Command,
	AlertDialog.Component:    AlertDialog,
	Drawer.Component:         Drawer,
	Sheet.Component:          Sheet,
	Carousel.Component:       Carousel,
	Calendar.Component:       Calendar,
	NativeSelect.Component:   NativeSelect,
	ButtonGroup.Component:    ButtonGroup,
	Item.Component:           Item,
	Field.Component:          Field,
	InputGroup.Component:     InputGroup,
}

// All returns every declared component shape, keyed by component name.
func All() map[string]recipe.Shape {
	out := make(map[string]recipe.Shape, len(all))
	maps.Copy(out, all)
	return out
}
