// Code generated by gsx; DO NOT EDIT.

package empty

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
	"github.com/gsxhq/gsxui/ui/icon"
	_gsxio "io"
)

//line rtl.gsx:8:1
// Rtl mirrors shadcn's own empty-rtl demo's Arabic "no projects yet" copy,
// kept in Basic's shape (icon.Inbox media, title, description, one
// EmptyContent Button — shadcn's version swaps in a folder icon and a
// second outline Button plus a "learn more" link, which this directory's
// Basic doesn't compose; DEVIATED from rather than invented).

//line rtl.gsx:13:1
func Rtl() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:14:2
		_gsxgw.S("<div dir=\"rtl\" lang=\"ar\">")
//line rtl.gsx:15:3
		_gsxgw.Node(ctx, ui.Empty(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:16:4
			_gsxgw.Node(ctx, ui.EmptyHeader(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:17:5
				_gsxgw.Node(ctx, ui.EmptyMedia("", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("الوسائط الافتراضية")
					return _gsxgw.Err()
				}), nil))
//line rtl.gsx:18:5
				_gsxgw.Node(ctx, ui.EmptyMedia("icon", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:19:6
					_gsxgw.Node(ctx, icon.Inbox())
					return _gsxgw.Err()
				}), nil))
//line rtl.gsx:21:5
				_gsxgw.Node(ctx, ui.EmptyTitle(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("لا توجد مشاريع بعد")
					return _gsxgw.Err()
				}), nil))
//line rtl.gsx:22:5
				_gsxgw.Node(ctx, ui.EmptyDescription(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("لم تقم بإنشاء أي مشاريع بعد. ابدأ بإنشاء مشروعك الأول.")
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
//line rtl.gsx:26:4
			_gsxgw.Node(ctx, ui.EmptyContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:27:5
				_gsxgw.Node(ctx, ui.Button("", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("إنشاء مشروع")
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), nil))
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}
