// Code generated by gsx; DO NOT EDIT.

package selectbox

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

//line basic.gsx:8:1
// Basic is a single-group Select with a label, five items and a placeholder;
// the trigger is width-pinned (w-[180px]) the way shadcn callers size the
// Trigger. name="fruit" renders the hidden native <select> form bridge.

//line basic.gsx:11:1
func Basic() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:12:2
		_gsxgw.Node(ctx, ui.Select("fruit", false, false, "", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:13:3
			_gsxgw.Node(ctx, ui.SelectTrigger("", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:14:4
				_gsxgw.Node(ctx, ui.SelectValue("Select a fruit", nil))
				return _gsxgw.Err()
			}), _gsxrt.Attrs{{Key: "class", Value: "w-[180px]"}}))
//line basic.gsx:16:3
			_gsxgw.Node(ctx, ui.SelectContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:17:4
				_gsxgw.Node(ctx, ui.SelectGroup(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:18:5
					_gsxgw.Node(ctx, ui.SelectLabel(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Fruits")
						return _gsxgw.Err()
					}), nil))
//line basic.gsx:19:5
					_gsxgw.Node(ctx, ui.SelectItem("apple", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Apple")
						return _gsxgw.Err()
					}), nil))
//line basic.gsx:20:5
					_gsxgw.Node(ctx, ui.SelectItem("banana", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Banana")
						return _gsxgw.Err()
					}), nil))
//line basic.gsx:21:5
					_gsxgw.Node(ctx, ui.SelectItem("blueberry", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Blueberry")
						return _gsxgw.Err()
					}), nil))
//line basic.gsx:22:5
					_gsxgw.Node(ctx, ui.SelectItem("grapes", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Grapes")
						return _gsxgw.Err()
					}), nil))
//line basic.gsx:23:5
					_gsxgw.Node(ctx, ui.SelectItem("pineapple", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Pineapple")
						return _gsxgw.Err()
					}), nil))
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), nil))
		return _gsxgw.Err()
	})
}
