// Code generated by gsx; DO NOT EDIT.

package selectbox

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

//line scrollable.gsx:5:1
// Scrollable is the long-list stress test: five SelectGroups spanning 27
// world timezones, separated by SelectSeparator. The content's max-h-96 cap
// (the base class) makes the whole viewport scroll natively — this is the
// demo for the "drop the scroll up/down buttons, rely on overflow-y-auto"
// decision (the custom listbox always anchors popper-equivalent, so Radix's
// item-aligned scroll affordances are unnecessary).

//line scrollable.gsx:11:1
func Scrollable() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line scrollable.gsx:12:2
		_gsxgw.Node(ctx, ui.Select("timezone", false, false, "", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line scrollable.gsx:13:3
			_gsxgw.Node(ctx, ui.SelectTrigger("", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line scrollable.gsx:14:4
				_gsxgw.Node(ctx, ui.SelectValue("Select a timezone", nil))
				return _gsxgw.Err()
			}), _gsxrt.Attrs{{Key: "class", Value: "w-[280px]"}}))
//line scrollable.gsx:16:3
			_gsxgw.Node(ctx, ui.SelectContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line scrollable.gsx:17:4
				_gsxgw.Node(ctx, ui.SelectGroup(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line scrollable.gsx:18:5
					_gsxgw.Node(ctx, ui.SelectLabel(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("North America")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:19:5
					_gsxgw.Node(ctx, ui.SelectItem("est", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Eastern Standard Time (EST)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:20:5
					_gsxgw.Node(ctx, ui.SelectItem("cst", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Central Standard Time (CST)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:21:5
					_gsxgw.Node(ctx, ui.SelectItem("mst", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Mountain Standard Time (MST)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:22:5
					_gsxgw.Node(ctx, ui.SelectItem("pst", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Pacific Standard Time (PST)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:23:5
					_gsxgw.Node(ctx, ui.SelectItem("akst", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Alaska Standard Time (AKST)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:24:5
					_gsxgw.Node(ctx, ui.SelectItem("hst", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Hawaii Standard Time (HST)")
						return _gsxgw.Err()
					}), nil))
					return _gsxgw.Err()
				}), nil))
//line scrollable.gsx:26:4
				_gsxgw.Node(ctx, ui.SelectSeparator(nil))
//line scrollable.gsx:27:4
				_gsxgw.Node(ctx, ui.SelectGroup(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line scrollable.gsx:28:5
					_gsxgw.Node(ctx, ui.SelectLabel(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Europe &amp; Africa")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:29:5
					_gsxgw.Node(ctx, ui.SelectItem("gmt", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Greenwich Mean Time (GMT)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:30:5
					_gsxgw.Node(ctx, ui.SelectItem("cet", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Central European Time (CET)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:31:5
					_gsxgw.Node(ctx, ui.SelectItem("eet", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Eastern European Time (EET)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:32:5
					_gsxgw.Node(ctx, ui.SelectItem("west", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Western European Summer Time (WEST)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:33:5
					_gsxgw.Node(ctx, ui.SelectItem("cat", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Central Africa Time (CAT)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:34:5
					_gsxgw.Node(ctx, ui.SelectItem("eat", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("East Africa Time (EAT)")
						return _gsxgw.Err()
					}), nil))
					return _gsxgw.Err()
				}), nil))
//line scrollable.gsx:36:4
				_gsxgw.Node(ctx, ui.SelectSeparator(nil))
//line scrollable.gsx:37:4
				_gsxgw.Node(ctx, ui.SelectGroup(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line scrollable.gsx:38:5
					_gsxgw.Node(ctx, ui.SelectLabel(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Asia")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:39:5
					_gsxgw.Node(ctx, ui.SelectItem("msk", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Moscow Time (MSK)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:40:5
					_gsxgw.Node(ctx, ui.SelectItem("ist", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("India Standard Time (IST)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:41:5
					_gsxgw.Node(ctx, ui.SelectItem("cst_china", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("China Standard Time (CST)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:42:5
					_gsxgw.Node(ctx, ui.SelectItem("jst", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Japan Standard Time (JST)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:43:5
					_gsxgw.Node(ctx, ui.SelectItem("kst", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Korea Standard Time (KST)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:44:5
					_gsxgw.Node(ctx, ui.SelectItem("ist_indonesia", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Indonesia Central Standard Time (WITA)")
						return _gsxgw.Err()
					}), nil))
					return _gsxgw.Err()
				}), nil))
//line scrollable.gsx:46:4
				_gsxgw.Node(ctx, ui.SelectSeparator(nil))
//line scrollable.gsx:47:4
				_gsxgw.Node(ctx, ui.SelectGroup(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line scrollable.gsx:48:5
					_gsxgw.Node(ctx, ui.SelectLabel(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Australia &amp; Pacific")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:49:5
					_gsxgw.Node(ctx, ui.SelectItem("awst", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Australian Western Standard Time (AWST)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:50:5
					_gsxgw.Node(ctx, ui.SelectItem("acst", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Australian Central Standard Time (ACST)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:51:5
					_gsxgw.Node(ctx, ui.SelectItem("aest", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Australian Eastern Standard Time (AEST)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:52:5
					_gsxgw.Node(ctx, ui.SelectItem("nzst", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("New Zealand Standard Time (NZST)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:53:5
					_gsxgw.Node(ctx, ui.SelectItem("fjt", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Fiji Time (FJT)")
						return _gsxgw.Err()
					}), nil))
					return _gsxgw.Err()
				}), nil))
//line scrollable.gsx:55:4
				_gsxgw.Node(ctx, ui.SelectSeparator(nil))
//line scrollable.gsx:56:4
				_gsxgw.Node(ctx, ui.SelectGroup(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line scrollable.gsx:57:5
					_gsxgw.Node(ctx, ui.SelectLabel(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("South America")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:58:5
					_gsxgw.Node(ctx, ui.SelectItem("art", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Argentina Time (ART)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:59:5
					_gsxgw.Node(ctx, ui.SelectItem("bot", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Bolivia Time (BOT)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:60:5
					_gsxgw.Node(ctx, ui.SelectItem("brt", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Brasilia Time (BRT)")
						return _gsxgw.Err()
					}), nil))
//line scrollable.gsx:61:5
					_gsxgw.Node(ctx, ui.SelectItem("clt", false, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Chile Standard Time (CLT)")
						return _gsxgw.Err()
					}), nil))
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), nil))
		return _gsxgw.Err()
	})
}
