// Code generated by gsx; DO NOT EDIT.

package input

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

//line custom.gsx:5:1
// Custom overrides Input's default height by passing class="h-12 text-base" at the
// call site. Input's own h-8 is part of the same class-merge group, so the
// caller's h-12 wins and h-8 is dropped entirely — not appended alongside
// it — rather than the two classes fighting in the cascade.

//line custom.gsx:9:1
func Custom() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line custom.gsx:10:2
		_gsxgw.Node(ctx, ui.Input(_gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "class", Value: "h-12 text-base"}}, _gsxrt.Attrs{{Key: "placeholder", Value: "Larger input"}})))
		return _gsxgw.Err()
	})
}
