// Code generated by gsx; DO NOT EDIT.

package nova

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxcm "github.com/gsxhq/gsxui/merge"
	_gsxio "io"
)

//line popover.gsx:5:1
// Popover uses the native auto-popover top layer with light dismissal and
// proximity-scoped behavior in ui/popover.js.

//line popover.gsx:7:1
func Popover(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line popover.gsx:8:2
		_gsxgw.S("<div class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("contents"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-popover"})
		_gsxgw.BoolAttr("data-gsxui-slot-popover", true)
		_gsxgw.S(">")
//line popover.gsx:8:65
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line popover.gsx:11:1
func PopoverTrigger(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line popover.gsx:12:2
		_gsxgw.S("<button")
		if !attrs.Has("type") {
			_gsxgw.S(" type=\"button\"")
		}
		if !attrs.Has("aria-expanded") {
			_gsxgw.S(" aria-expanded=\"false\"")
		}
		_gsxgw.ClassMerged(_gsxcm.Merge, attrs.Class())
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "button", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-popover-trigger"})
		_gsxgw.BoolAttr("data-gsxui-slot-popover-trigger", true)
		_gsxgw.S(">")
//line popover.gsx:18:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</button>")
		return _gsxgw.Err()
	})
}

//line popover.gsx:22:1
func PopoverContent(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line popover.gsx:23:2
		_gsxgw.S("<div")
		if !attrs.Has("popover") {
			_gsxgw.S(" popover=\"auto\"")
		}
		if !attrs.Has("data-state") {
			_gsxgw.S(" data-state=\"closed\"")
		}
		if !attrs.Has("data-side") {
			_gsxgw.S(" data-side=\"bottom\"")
		}
		if !attrs.Has("tabindex") {
			_gsxgw.S(" tabindex=\"-1\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("z-50 w-72 origin-top gap-2.5 rounded-lg border bg-popover p-2.5 text-sm text-popover-foreground shadow-md outline-hidden opacity-0 scale-95 transition-[opacity,scale,translate,display,overlay] transition-discrete duration-150 [&:popover-open]:opacity-100 [&:popover-open]:scale-100 starting:[&:popover-open]:opacity-0 starting:[&:popover-open]:scale-95 starting:[&:popover-open]:data-[side=bottom]:-translate-y-2 starting:[&:popover-open]:data-[side=left]:translate-x-2 starting:[&:popover-open]:data-[side=right]:-translate-x-2 starting:[&:popover-open]:data-[side=top]:translate-y-2"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-popover-content"})
		_gsxgw.BoolAttr("data-gsxui-slot-popover-content", true)
		_gsxgw.S(">")
//line popover.gsx:34:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}
