// Code generated by gsx; DO NOT EDIT.

package hovercard

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxstd "github.com/gsxhq/gsx/std"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

//line rtl.gsx:5:1
// Rtl mirrors Basic's own hover-card-demo shape (link trigger, avatar +
// name + description + joined-date card), translated to Arabic. shadcn's
// own hover-card-rtl demo is a product-price card with four physical-side
// and two logical-side triggers, which this directory's Basic doesn't
// compose; DEVIATED from rather than invented.

//line rtl.gsx:10:1
func Rtl() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:11:2
		_gsxgw.S("<div dir=\"rtl\" lang=\"ar\">")
//line rtl.gsx:12:3
		_gsxgw.Node(ctx, ui.HoverCard(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:13:4
			_gsxgw.Node(ctx, ui.HoverCardTrigger(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:14:5
				_gsxgw.Node(ctx, ui.Button("link", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("@nextjs")
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
//line rtl.gsx:16:4
			_gsxgw.Node(ctx, ui.HoverCardContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:17:5
				_gsxgw.S("<div class=\"flex justify-between gap-4\">")
//line rtl.gsx:18:6
				_gsxgw.Node(ctx, ui.Avatar(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:19:7
					_gsxgw.Node(ctx, ui.AvatarImage(_gsxstd.DataURL((avatarSVG), "image/svg+xml"), "@nextjs", nil))
//line rtl.gsx:20:7
					_gsxgw.Node(ctx, ui.AvatarFallback(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("VC")
						return _gsxgw.Err()
					}), nil))
					return _gsxgw.Err()
				}), nil))
//line rtl.gsx:22:6
				_gsxgw.S("<div class=\"space-y-1\">")
//line rtl.gsx:23:7
				_gsxgw.S("<h4 class=\"text-sm font-semibold\">@nextjs</h4>")
//line rtl.gsx:24:7
				_gsxgw.S("<p class=\"text-sm\">إطار React – تم إنشاؤه وصيانته بواسطة @vercel.</p>")
//line rtl.gsx:25:7
				_gsxgw.S("<div class=\"text-xs text-muted-foreground\">انضم في ديسمبر 2021</div></div></div>")
				return _gsxgw.Err()
			}), _gsxrt.Attrs{{Key: "class", Value: "w-80"}}))
			return _gsxgw.Err()
		}), nil))
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}
