// Code generated by gsx; DO NOT EDIT.

package luma

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxstd "github.com/gsxhq/gsx/std"
	_gsxcm "github.com/gsxhq/gsxui/merge"
	_gsxio "io"
)

//line empty.gsx:5:1
// Empty and its parts are the shadcn/ui Empty (registry/new-york-v4/ui/
// empty.tsx) — no Radix primitive underneath either; every part is already a
// plain styled <div>, the same "package-namespaced compound parts" shape as
// card/breadcrumb.

//line empty.gsx:9:1
func Empty(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderEmpty(ctx, _gsxgw, children, attrs)
	})
}

func _gsxrenderEmpty(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line empty.gsx:10:2
	_gsxgw.S("<div class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("gap-4 rounded-2xl border-dashed p-12 flex flex-col"), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-empty"})
	_gsxgw.BoolAttr("data-gsxui-slot-empty", true)
	_gsxgw.S(">")
//line empty.gsx:11:3
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}

//line empty.gsx:15:1
func EmptyHeader(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderEmptyHeader(ctx, _gsxgw, children, attrs)
	})
}

func _gsxrenderEmptyHeader(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line empty.gsx:16:2
	_gsxgw.S("<div class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("gap-2 flex flex-col"), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-empty-header"})
	_gsxgw.BoolAttr("data-gsxui-slot-empty-header", true)
	_gsxgw.S(">")
//line empty.gsx:17:3
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}

//line empty.gsx:21:1
// EmptyMedia's variant cva map (registry's emptyMediaVariants) picks between
// two entirely static presentation blocks by the JS-resolved variant value.
// The CSS-only contract reflects that value through data-variant.
// The stable token is "empty-icon", matching shadcn's own semantic name.

//line empty.gsx:25:1
func EmptyMedia(variant string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderEmptyMedia(ctx, _gsxgw, variant, children, attrs)
	})
}

func _gsxrenderEmptyMedia(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, variant string, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line empty.gsx:26:2
	_gsxgw.S("<div")
	if !attrs.Has("data-variant") {
		_gsxgw.S(" data-variant=\"")
		_gsxgw.AttrValue(string(_gsxstd.Default((variant), "default")))
		_gsxgw.S("\"")
	}
	_gsxv0 := "mb-2 flex"
	var _gsxv1 string
	switch variant {
	case "icon":
		_gsxv1 = "bg-muted text-foreground flex size-10 shrink-0 items-center justify-center rounded-xl [&_svg:not([class*='size-'])]:size-5"
	default:
		_gsxv1 = "bg-transparent"
	}
	_gsxgw.S(" class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(_gsxv0), _gsxrt.Class(_gsxv1), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-empty-icon"})
	_gsxgw.BoolAttr("data-gsxui-slot-empty-icon", true)
	_gsxgw.S(">")
//line empty.gsx:40:3
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}

//line empty.gsx:44:1
func EmptyTitle(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderEmptyTitle(ctx, _gsxgw, children, attrs)
	})
}

func _gsxrenderEmptyTitle(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line empty.gsx:45:2
	_gsxgw.S("<div class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("text-lg font-medium tracking-tight"), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-empty-title"})
	_gsxgw.BoolAttr("data-gsxui-slot-empty-title", true)
	_gsxgw.S(">")
//line empty.gsx:46:3
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}

//line empty.gsx:50:1
// EmptyDescription renders a <div>, matching shadcn's own actual element —
// its TypeScript prop type reads React.ComponentProps<"p"> but the JSX it
// returns is a <div>, the same shipped-type/element mismatch already noted
// for Kbd/KbdGroup (see docs/jsx-parity.md ## kbd); ported verbatim, tag
// included, per the token-for-token rule.

//line empty.gsx:55:1
func EmptyDescription(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderEmptyDescription(ctx, _gsxgw, children, attrs)
	})
}

func _gsxrenderEmptyDescription(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line empty.gsx:56:2
	_gsxgw.S("<div class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("text-sm/relaxed"), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-empty-description"})
	_gsxgw.BoolAttr("data-gsxui-slot-empty-description", true)
	_gsxgw.S(">")
//line empty.gsx:57:3
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}

//line empty.gsx:61:1
func EmptyContent(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderEmptyContent(ctx, _gsxgw, children, attrs)
	})
}

func _gsxrenderEmptyContent(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line empty.gsx:62:2
	_gsxgw.S("<div class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("gap-4 text-sm flex flex-col"), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-empty-content"})
	_gsxgw.BoolAttr("data-gsxui-slot-empty-content", true)
	_gsxgw.S(">")
//line empty.gsx:63:3
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}
