// Code generated by gsx; DO NOT EDIT.

package collapsible

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
	"github.com/gsxhq/gsxui/ui/icon"
	_gsxio "io"
)

//line basic.gsx:10:1
// Basic mirrors shadcn's own collapsible demo (registry/new-york-v4/
// examples/collapsible-demo.tsx): a title row with a chevron ghost
// icon-button trigger, one always-visible list item, then two more
// revealed by expanding.
//
// ADAPT from the demo's literal shape: shadcn wraps ONLY the icon Button in
// CollapsibleTrigger (asChild), leaving the title <h4> outside it — Radix's
// Trigger is an inert wrapper, so the title/button can share a plain sibling
// <div> row with no HTML placement constraint. Native <details> imposes one
// shadcn's version doesn't have: only a summary that is a DIRECT CHILD of
// its details is recognized as the disclosure control (a summary nested a
// level deeper, e.g. inside a wrapping row <div>, renders as inert content
// and the browser falls back to its own default-labelled summary). So the
// title and button both move INSIDE CollapsibleTrigger here, and the flex
// row classes move from the (now-gone) wrapper div onto the trigger itself
// — the whole row is the clickable summary, not just the button, per
// ui/collapsible.gsx's CollapsibleTrigger doc comment.
//
// The chevron is a STYLED SPAN (ghost icon-button look), not a real
// ui.Button: activating a nested interactive element inside a <summary> is
// the element's own activation, not the summary's — a real <button> there
// swallows the click and the details never toggles (and Radix never had
// this trap: its Trigger IS the button). The summary is the one
// interactive/focusable control; the span is decoration (aria-hidden).

//line basic.gsx:34:1
func Basic() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:35:2
		_gsxgw.Node(ctx, ui.Collapsible(false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:36:3
			_gsxgw.Node(ctx, ui.CollapsibleTrigger(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:37:4
				_gsxgw.S("<h4 class=\"text-sm font-semibold\">@peduarte starred 3 repositories</h4>")
//line basic.gsx:38:4
				_gsxgw.S("<span aria-hidden=\"true\" class=\"inline-flex size-8 shrink-0 items-center justify-center rounded-md transition-colors hover:bg-accent hover:text-accent-foreground [&amp;_svg]:pointer-events-none [&amp;_svg:not([class*=&#39;size-&#39;])]:size-4\">")
//line basic.gsx:42:5
				_gsxgw.Node(ctx, icon.ChevronsUpDown())
				_gsxgw.S("</span>")
				return _gsxgw.Err()
			}), _gsxrt.Attrs{{Key: "class", Value: "flex cursor-default items-center justify-between gap-4 px-4"}}))
//line basic.gsx:45:3
			_gsxgw.S("<div class=\"rounded-md border px-4 py-2 font-mono text-sm\">@radix-ui/primitives</div>")
//line basic.gsx:46:3
			_gsxgw.Node(ctx, ui.CollapsibleContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:47:4
				_gsxgw.S("<div class=\"rounded-md border px-4 py-2 font-mono text-sm\">@radix-ui/colors</div>")
//line basic.gsx:48:4
				_gsxgw.S("<div class=\"rounded-md border px-4 py-2 font-mono text-sm\">@stitches/react</div>")
				return _gsxgw.Err()
			}), _gsxrt.Attrs{{Key: "class", Value: "flex flex-col gap-2"}}))
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "class", Value: "flex w-[350px] flex-col gap-2"}}))
		return _gsxgw.Err()
	})
}
