// Code generated by gsx; DO NOT EDIT.

package resizable

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

//line rtl.gsx:5:1
// Rtl mirrors shadcn's own resizable-rtl demo: the same horizontal
// two-panel / nested-vertical-group shape as this dir's own Basic, labels
// translated to Arabic and wrapped in dir="rtl".

//line rtl.gsx:8:1
func Rtl() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:9:2
		_gsxgw.S("<div dir=\"rtl\" lang=\"ar\">")
//line rtl.gsx:10:3
		_gsxgw.Node(ctx, ui.ResizablePanelGroup("horizontal", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:11:4
			_gsxgw.Node(ctx, ui.ResizablePanel("50%", "", "", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:12:5
				_gsxgw.S("<div class=\"flex h-[200px] items-center justify-center p-6\">")
//line rtl.gsx:13:6
				_gsxgw.S("<span class=\"font-semibold\">واحد</span></div>")
				return _gsxgw.Err()
			}), nil))
//line rtl.gsx:16:4
			_gsxgw.Node(ctx, ui.ResizableHandle("horizontal", true, nil))
//line rtl.gsx:17:4
			_gsxgw.Node(ctx, ui.ResizablePanel("50%", "", "", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:18:5
				_gsxgw.Node(ctx, ui.ResizablePanelGroup("vertical", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:19:6
					_gsxgw.Node(ctx, ui.ResizablePanel("25%", "", "", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:20:7
						_gsxgw.S("<div class=\"flex h-full items-center justify-center p-6\">")
//line rtl.gsx:21:8
						_gsxgw.S("<span class=\"font-semibold\">اثنان</span></div>")
						return _gsxgw.Err()
					}), nil))
//line rtl.gsx:24:6
					_gsxgw.Node(ctx, ui.ResizableHandle("vertical", true, nil))
//line rtl.gsx:25:6
					_gsxgw.Node(ctx, ui.ResizablePanel("75%", "", "", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:26:7
						_gsxgw.S("<div class=\"flex h-full items-center justify-center p-6\">")
//line rtl.gsx:27:8
						_gsxgw.S("<span class=\"font-semibold\">ثلاثة</span></div>")
						return _gsxgw.Err()
					}), nil))
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "class", Value: "max-w-sm rounded-lg border"}}))
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}
