// Code generated by gsx; DO NOT EDIT.

package avatar

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxstd "github.com/gsxhq/gsx/std"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

// A 64x64 violet tile with white "AL" initials — a stand-in portrait, so
// the loaded-image state is visibly an avatar and visibly distinct from
// the gray fallback. Authored as plain SVG bytes; the `|> dataURL(mime)`
// std filter at the src site assembles the base64 data: URL gsx's
// image-sink sanitizer accepts (see docs/jsx-parity.md ## avatar).
//
//line basic.gsx:6:1
var avatarSVG = []byte("<svg xmlns='http://www.w3.org/2000/svg' width='64' height='64'><rect width='64' height='64' fill='#6d28d9'/><text x='32' y='34' text-anchor='middle' dominant-baseline='central' font-family='sans-serif' font-weight='600' font-size='26' fill='#fff'>AL</text></svg>")

// Basic renders two Avatars side by side: one whose image loads (a data
// URI), one whose image 404s and falls back to initials — avatar.js
// toggles which of image/fallback is visible on the image's load/error.

//line basic.gsx:16:1
func Basic() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:17:2
		_gsxgw.S("<div class=\"flex items-center gap-4\">")
//line basic.gsx:18:3
		_gsxgw.Node(ctx, ui.Avatar(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:19:4
			_gsxgw.Node(ctx, ui.AvatarImage(_gsxstd.DataURL((avatarSVG), "image/svg+xml"), "Ada Lovelace", nil))
//line basic.gsx:20:4
			_gsxgw.Node(ctx, ui.AvatarFallback(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("AL")
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), nil))
//line basic.gsx:22:3
		_gsxgw.Node(ctx, ui.Avatar(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:23:4
			_gsxgw.Node(ctx, ui.AvatarImage("/broken-image.jpg", "Broken avatar", nil))
//line basic.gsx:24:4
			_gsxgw.Node(ctx, ui.AvatarFallback(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("JD")
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), nil))
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}
