// Code generated by gsx; DO NOT EDIT.

package avatar

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxstd "github.com/gsxhq/gsx/std"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

//line group.gsx:5:1
// Group renders three overlapping Avatars — a stacked-avatars pattern
// built entirely from attrs (-space-x-2, a ring), no extra component.

//line group.gsx:7:1
func Group() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line group.gsx:8:2
		_gsxgw.S("<div class=\"flex -space-x-2\">")
//line group.gsx:9:3
		_gsxgw.Node(ctx, ui.Avatar(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line group.gsx:10:4
			_gsxgw.Node(ctx, ui.AvatarImage(_gsxstd.DataURL((avatarSVG), "image/svg+xml"), "Ada Lovelace", nil))
//line group.gsx:11:4
			_gsxgw.Node(ctx, ui.AvatarFallback(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("AL")
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "class", Value: "ring-2 ring-background"}}))
//line group.gsx:13:3
		_gsxgw.Node(ctx, ui.Avatar(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line group.gsx:14:4
			_gsxgw.Node(ctx, ui.AvatarFallback(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("GH")
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "class", Value: "ring-2 ring-background"}}))
//line group.gsx:16:3
		_gsxgw.Node(ctx, ui.Avatar(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line group.gsx:17:4
			_gsxgw.Node(ctx, ui.AvatarFallback(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("AT")
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "class", Value: "ring-2 ring-background"}}))
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}
