// Code generated by gsx; DO NOT EDIT.

package main

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

//line sidebar_contract.gsx:8:1
func SidebarContractFrame(open bool, side string, variant string, collapsible string, children gsx.Node, sidebarAttrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderSidebarContractFrame(ctx, _gsxgw, open, side, variant, collapsible, children, sidebarAttrs)
	})
}

func _gsxrenderSidebarContractFrame(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, open bool, side string, variant string, collapsible string, children gsx.Node, sidebarAttrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line sidebar_contract.gsx:9:2
	_gsxgw.Node(ctx, ui.SidebarProvider(open, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:10:3
		_gsxgw.Node(ctx, ui.Sidebar(open, side, variant, collapsible, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:17:4
			_gsxgw.Node(ctx, children)
//line sidebar_contract.gsx:18:4
			_gsxgw.Node(ctx, ui.SidebarRail(nil))
			return _gsxgw.Err()
		}), sidebarAttrs))
//line sidebar_contract.gsx:20:3
		_gsxgw.Node(ctx, ui.SidebarInset(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:21:4
			_gsxgw.Node(ctx, ui.SidebarTrigger(nil))
//line sidebar_contract.gsx:22:4
			_gsxgw.S("<button type=\"button\"")
			_gsxgw.BoolAttr("data-gsxui-slot-sidebar-trigger", true)
			_gsxgw.S(">Custom Sidebar Trigger</button>")
			return _gsxgw.Err()
		}), nil))
		return _gsxgw.Err()
	}), nil))
	return _gsxgw.Err()
}

//line sidebar_contract.gsx:27:1
func SidebarContractMenu() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderSidebarContractMenu(ctx, _gsxgw)
	})
}

func _gsxrenderSidebarContractMenu(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line sidebar_contract.gsx:28:2
	_gsxgw.Node(ctx, ui.SidebarHeader(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:29:3
		_gsxgw.Node(ctx, ui.SidebarInput(_gsxrt.Attrs{{Key: "aria-label", Value: "Sidebar search"}}))
		return _gsxgw.Err()
	}), nil))
//line sidebar_contract.gsx:31:2
	_gsxgw.Node(ctx, ui.SidebarContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:32:3
		_gsxgw.Node(ctx, ui.SidebarGroup(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:33:4
			_gsxgw.Node(ctx, ui.SidebarGroupLabel(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Application")
				return _gsxgw.Err()
			}), _gsxrt.Attrs{{Key: "tabindex", Value: "0"}}))
//line sidebar_contract.gsx:34:4
			_gsxgw.Node(ctx, ui.SidebarGroupAction(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("+")
				return _gsxgw.Err()
			}), _gsxrt.Attrs{{Key: "aria-label", Value: "Add group"}}))
//line sidebar_contract.gsx:35:4
			_gsxgw.Node(ctx, ui.SidebarGroupContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:36:5
				_gsxgw.Node(ctx, ui.SidebarMenu(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:37:6
					_gsxgw.Node(ctx, ui.SidebarMenuItem(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:38:7
						_gsxgw.Node(ctx, ui.SidebarMenuButton(true, "", "sm", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
							_gsxgw.S("Small action")
							return _gsxgw.Err()
						}), nil))
//line sidebar_contract.gsx:39:7
						_gsxgw.Node(ctx, ui.SidebarMenuAction(true, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
							_gsxgw.S("…")
							return _gsxgw.Err()
						}), _gsxrt.Attrs{{Key: "aria-label", Value: "Small action menu"}}))
//line sidebar_contract.gsx:40:7
						_gsxgw.Node(ctx, ui.SidebarMenuBadge(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
							_gsxgw.S("3")
							return _gsxgw.Err()
						}), nil))
						return _gsxgw.Err()
					}), _gsxrt.Attrs{{Key: "data-sidebar-contract", Value: "action-item"}}))
//line sidebar_contract.gsx:42:6
					_gsxgw.Node(ctx, ui.SidebarMenuItem(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:43:7
						_gsxgw.Node(ctx, ui.SidebarMenuButton(false, "", "", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
							_gsxgw.S("Default action")
							return _gsxgw.Err()
						}), nil))
//line sidebar_contract.gsx:44:7
						_gsxgw.Node(ctx, ui.SidebarMenuAction(false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
							_gsxgw.S("…")
							return _gsxgw.Err()
						}), _gsxrt.Attrs{{Key: "data-sidebar-contract", Value: "default-action"}}))
						return _gsxgw.Err()
					}), nil))
//line sidebar_contract.gsx:46:6
					_gsxgw.Node(ctx, ui.SidebarMenuItem(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:47:7
						_gsxgw.Node(ctx, ui.SidebarMenuButton(false, "", "lg", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
							_gsxgw.S("Large badge")
							return _gsxgw.Err()
						}), nil))
//line sidebar_contract.gsx:48:7
						_gsxgw.Node(ctx, ui.SidebarMenuBadge(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
							_gsxgw.S("9")
							return _gsxgw.Err()
						}), _gsxrt.Attrs{{Key: "data-sidebar-contract", Value: "large-badge"}}))
						return _gsxgw.Err()
					}), nil))
//line sidebar_contract.gsx:50:6
					_gsxgw.Node(ctx, ui.SidebarMenuItem(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:51:7
						_gsxgw.Node(ctx, ui.SidebarMenuButton(false, "", "", "Tooltip item", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
							_gsxgw.S("Tooltip item")
							return _gsxgw.Err()
						}), nil))
						return _gsxgw.Err()
					}), nil))
//line sidebar_contract.gsx:53:6
					_gsxgw.Node(ctx, ui.SidebarMenuItem(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:54:7
						_gsxgw.Node(ctx, ui.SidebarMenuButton(true, "", "", "Tooltip link", "#tooltip-link", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
							_gsxgw.S("Tooltip link")
							return _gsxgw.Err()
						}), _gsxrt.Attrs{{Key: "data-sidebar-contract", Value: "tooltip-link"}}))
						return _gsxgw.Err()
					}), nil))
//line sidebar_contract.gsx:63:6
					_gsxgw.Node(ctx, ui.SidebarMenuItem(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:64:7
						_gsxgw.Node(ctx, ui.SidebarMenuButton(false, "", "", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
							_gsxgw.S("Parent")
							return _gsxgw.Err()
						}), nil))
//line sidebar_contract.gsx:65:7
						_gsxgw.Node(ctx, ui.SidebarMenuSub(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:66:8
							_gsxgw.Node(ctx, ui.SidebarMenuSubItem(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
								_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:67:9
								_gsxgw.Node(ctx, ui.SidebarMenuSubButton("sm", true, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
									_gsxgw := _gsxrt.W(_gsxw)
									_gsxgw.S("Child")
									return _gsxgw.Err()
								}), _gsxrt.Attrs{{Key: "href", Value: "#"}}))
								return _gsxgw.Err()
							}), nil))
							return _gsxgw.Err()
						}), nil))
						return _gsxgw.Err()
					}), nil))
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), nil))
		return _gsxgw.Err()
	}), nil))
//line sidebar_contract.gsx:77:2
	_gsxgw.Node(ctx, ui.SidebarFooter(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		_gsxgw.S("Footer")
		return _gsxgw.Err()
	}), nil))
	return _gsxgw.Err()
}

//line sidebar_contract.gsx:80:1
func SidebarTokenFixture() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderSidebarTokenFixture(ctx, _gsxgw)
	})
}

func _gsxrenderSidebarTokenFixture(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line sidebar_contract.gsx:81:2
	_gsxgw.S("<div style=\"--sidebar:rgb(1,2,3);--sidebar-foreground:rgb(4,5,6);--sidebar-primary:rgb(7,8,9);--sidebar-primary-foreground:rgb(10,11,12);--sidebar-accent:rgb(13,14,15);--sidebar-accent-foreground:rgb(16,17,18);--sidebar-border:rgb(19,20,21);--sidebar-ring:rgb(22,23,24)\">")
//line sidebar_contract.gsx:84:3
	_gsxgw.NodeResult(_gsxrenderSidebarContractFrame(ctx, _gsxgw, true, "", "", "", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:85:4
		_gsxgw.Node(ctx, ui.SidebarHeader(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:86:5
			_gsxgw.Node(ctx, ui.SidebarSeparator(nil))
			return _gsxgw.Err()
		}), nil))
//line sidebar_contract.gsx:88:4
		_gsxgw.Node(ctx, ui.SidebarContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:89:5
			_gsxgw.Node(ctx, ui.SidebarGroup(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:90:6
				_gsxgw.Node(ctx, ui.SidebarGroupLabel(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("Tokens")
					return _gsxgw.Err()
				}), _gsxrt.Attrs{{Key: "tabindex", Value: "0"}}))
//line sidebar_contract.gsx:91:6
				_gsxgw.Node(ctx, ui.SidebarMenu(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:92:7
					_gsxgw.Node(ctx, ui.SidebarMenuItem(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:93:8
						_gsxgw.Node(ctx, ui.SidebarMenuButton(true, "", "", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
							_gsxgw.S("Active")
							return _gsxgw.Err()
						}), _gsxrt.Attrs{{Key: "data-sidebar-contract", Value: "active"}}))
//line sidebar_contract.gsx:96:8
						_gsxgw.Node(ctx, ui.SidebarMenuBadge(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
							_gsxgw.S("1")
							return _gsxgw.Err()
						}), _gsxrt.Attrs{{Key: "data-sidebar-contract", Value: "active-badge"}}))
						return _gsxgw.Err()
					}), nil))
//line sidebar_contract.gsx:98:7
					_gsxgw.Node(ctx, ui.SidebarMenuItem(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:99:8
						_gsxgw.Node(ctx, ui.SidebarMenuButton(false, "", "", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
							_gsxgw.S("Hover")
							return _gsxgw.Err()
						}), _gsxrt.Attrs{{Key: "data-sidebar-contract", Value: "hover"}}))
						return _gsxgw.Err()
					}), nil))
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), nil))
		return _gsxgw.Err()
	}), nil))
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}

//line sidebar_contract.gsx:108:1
func SidebarCallerFixture() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderSidebarCallerFixture(ctx, _gsxgw)
	})
}

func _gsxrenderSidebarCallerFixture(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line sidebar_contract.gsx:109:2
	_gsxgw.NodeResult(_gsxrenderSidebarContractFrame(ctx, _gsxgw, true, "", "", "", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:113:3
		_gsxgw.Node(ctx, ui.SidebarHeader(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:114:4
			_gsxgw.Node(ctx, ui.SidebarInput(_gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "class", Value: "h-12"}}, _gsxrt.Attrs{{Key: "aria-label", Value: "Caller input"}})))
			return _gsxgw.Err()
		}), nil))
//line sidebar_contract.gsx:116:3
		_gsxgw.Node(ctx, ui.SidebarMenu(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:117:4
			_gsxgw.Node(ctx, ui.SidebarMenuItem(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:118:5
				_gsxgw.Node(ctx, ui.SidebarMenuButton(false, "", "", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("Caller menu button")
					return _gsxgw.Err()
				}), _gsxrt.Attrs{{Key: "class", Value: "h-16 rounded-none"}}))
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), nil))
		return _gsxgw.Err()
	}), gsx.Attrs{{Key: "class", Value: "w-80"}}))
	return _gsxgw.Err()
}

//line sidebar_contract.gsx:124:1
func SidebarContractFixture(name string) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:125:2
		switch name {
		case "offcanvas-left":
//line sidebar_contract.gsx:127:3
			_gsxgw.NodeResult(_gsxrenderSidebarContractFrame(ctx, _gsxgw, true, "left", "", "offcanvas", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:128:4
				_gsxgw.Node(ctx, ui.SidebarContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("Left")
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
		case "offcanvas-right":
//line sidebar_contract.gsx:131:3
			_gsxgw.NodeResult(_gsxrenderSidebarContractFrame(ctx, _gsxgw, false, "right", "", "offcanvas", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:132:4
				_gsxgw.Node(ctx, ui.SidebarContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("Right")
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
		case "none":
//line sidebar_contract.gsx:135:3
			_gsxgw.NodeResult(_gsxrenderSidebarContractFrame(ctx, _gsxgw, false, "right", "inset", "none", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:136:4
				_gsxgw.Node(ctx, ui.SidebarContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("Always visible")
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
		case "icon-sidebar":
//line sidebar_contract.gsx:139:3
			_gsxgw.NodeResult(_gsxrenderSidebarContractFrame(ctx, _gsxgw, false, "", "", "icon", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:140:4
				_gsxgw.NodeResult(_gsxrenderSidebarContractMenu(ctx, _gsxgw))
				return _gsxgw.Err()
			}), nil))
		case "icon-floating":
//line sidebar_contract.gsx:143:3
			_gsxgw.NodeResult(_gsxrenderSidebarContractFrame(ctx, _gsxgw, false, "", "floating", "icon", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:144:4
				_gsxgw.NodeResult(_gsxrenderSidebarContractMenu(ctx, _gsxgw))
				return _gsxgw.Err()
			}), nil))
		case "inset-collapsed":
//line sidebar_contract.gsx:147:3
			_gsxgw.NodeResult(_gsxrenderSidebarContractFrame(ctx, _gsxgw, false, "", "inset", "icon", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:148:4
				_gsxgw.NodeResult(_gsxrenderSidebarContractMenu(ctx, _gsxgw))
				return _gsxgw.Err()
			}), nil))
		case "menu-icon":
//line sidebar_contract.gsx:151:3
			_gsxgw.NodeResult(_gsxrenderSidebarContractFrame(ctx, _gsxgw, false, "", "", "icon", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:152:4
				_gsxgw.NodeResult(_gsxrenderSidebarContractMenu(ctx, _gsxgw))
				return _gsxgw.Err()
			}), nil))
		case "menu-expanded":
//line sidebar_contract.gsx:155:3
			_gsxgw.NodeResult(_gsxrenderSidebarContractFrame(ctx, _gsxgw, true, "", "", "icon", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:156:4
				_gsxgw.NodeResult(_gsxrenderSidebarContractMenu(ctx, _gsxgw))
				return _gsxgw.Err()
			}), nil))
		case "tokens":
//line sidebar_contract.gsx:159:3
			_gsxgw.NodeResult(_gsxrenderSidebarTokenFixture(ctx, _gsxgw))
		case "caller":
//line sidebar_contract.gsx:161:3
			_gsxgw.NodeResult(_gsxrenderSidebarCallerFixture(ctx, _gsxgw))
		case "mobile":
//line sidebar_contract.gsx:163:3
			_gsxgw.NodeResult(_gsxrenderSidebarContractFrame(ctx, _gsxgw, true, "", "", "", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:164:4
				_gsxgw.NodeResult(_gsxrenderSidebarContractMenu(ctx, _gsxgw))
				return _gsxgw.Err()
			}), nil))
		case "keyboard":
//line sidebar_contract.gsx:167:3
			_gsxgw.S("<div>")
//line sidebar_contract.gsx:168:4
			_gsxgw.NodeResult(_gsxrenderSidebarContractFrame(ctx, _gsxgw, true, "", "", "", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:169:5
				_gsxgw.Node(ctx, ui.SidebarContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("First")
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
//line sidebar_contract.gsx:171:4
			_gsxgw.NodeResult(_gsxrenderSidebarContractFrame(ctx, _gsxgw, true, "", "", "", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line sidebar_contract.gsx:172:5
				_gsxgw.Node(ctx, ui.SidebarContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("Second")
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
//line sidebar_contract.gsx:174:4
			_gsxgw.S("<input aria-label=\"Typing target\"></div>")
		}
		return _gsxgw.Err()
	})
}
