// Code generated by gsx; DO NOT EDIT.

package textarea

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

//line rtl.gsx:5:1
// Rtl mirrors shadcn's own textarea-rtl demo: a Field pairing a label,
// Textarea, and description, translated to Arabic and wrapped in dir="rtl".

//line rtl.gsx:7:1
func Rtl() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:8:2
		_gsxgw.Node(ctx, ui.Field("", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:9:3
			_gsxgw.Node(ctx, ui.FieldLabel(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("التعليقات")
				return _gsxgw.Err()
			}), _gsxrt.Attrs{{Key: "for", Value: "textarea-rtl-feedback"}}))
//line rtl.gsx:10:3
			_gsxgw.Node(ctx, ui.Textarea("", _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "id", Value: "textarea-rtl-feedback"}}, _gsxrt.Attrs{{Key: "placeholder", Value: "تعليقاتك تساعدنا على التحسين..."}}, _gsxrt.Attrs{{Key: "rows", Value: "4"}})))
//line rtl.gsx:11:3
			_gsxgw.Node(ctx, ui.FieldDescription(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("شاركنا أفكارك حول خدمتنا.")
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "dir", Value: "rtl"}}, _gsxrt.Attrs{{Key: "lang", Value: "ar"}}, _gsxrt.Attrs{{Key: "class", Value: "w-full max-w-xs"}})))
		return _gsxgw.Err()
	})
}
