package cli

import (
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	gsxui "github.com/gsxhq/gsxui"
	"github.com/gsxhq/gsxui/internal/registry"
)

// runAdd vendors the requested components (and their transitive deps) into
// cfg.UI. Vendored .gsx files keep their "package ui" clause regardless of
// cfg.UI's basename — Go allows a package's declared name to differ from
// its directory name, so e.g. `gsxui add button` into cfg.UI = "components"
// still produces components/button.gsx starting with "package ui", and it
// compiles and imports fine as "components".
func runAdd(args []string) error {
	fs2 := flag.NewFlagSet("add", flag.ContinueOnError)
	overwrite := fs2.Bool("overwrite", false, "replace locally modified files")
	if err := fs2.Parse(args); err != nil {
		return err
	}
	names := fs2.Args()
	if len(names) == 0 {
		return fmt.Errorf("usage: gsxui add [--overwrite] <component>...")
	}
	dir, err := os.Getwd()
	if err != nil {
		return err
	}
	cfg, err := LoadConfig(dir)
	if err != nil {
		return err
	}
	module, err := modulePath(dir)
	if err != nil {
		return err
	}
	resolved, err := registry.Resolve(names)
	if err != nil {
		return err
	}
	fmt.Printf("adding: %s\n", strings.Join(resolved, " "))

	for _, name := range resolved {
		if fi, err := fs.Stat(gsxui.Files, "ui/"+name); err == nil && fi.IsDir() {
			// Directory component (icon): vendors as its own package under
			// <cfg.UI>/<name>/ — it must stay a package (icon.New) and its
			// generated data tables stay out of the user's ui namespace.
			entries, err := fs.ReadDir(gsxui.Files, "ui/"+name)
			if err != nil {
				return err
			}
			for _, e := range entries {
				fname := e.Name()
				if e.IsDir() || strings.HasSuffix(fname, ".x.go") || strings.HasSuffix(fname, "_test.go") {
					continue
				}
				src, err := fs.ReadFile(gsxui.Files, "ui/"+name+"/"+fname)
				if err != nil {
					return err
				}
				if strings.HasSuffix(fname, ".gsx") || strings.HasSuffix(fname, ".go") {
					src = RewriteGsx(src, module, cfg.UI)
				}
				if err := writeVendored(filepath.Join(dir, cfg.UI, name, fname), src, *overwrite); err != nil {
					return err
				}
			}
		} else {
			src, err := fs.ReadFile(gsxui.Files, "ui/"+name+".gsx")
			if err != nil {
				return err
			}
			if err := writeVendored(filepath.Join(dir, cfg.UI, name+".gsx"), RewriteGsx(src, module, cfg.UI), *overwrite); err != nil {
				return err
			}
		}
		if registry.HasJS(name) {
			src, err := fs.ReadFile(gsxui.Files, "ui/"+name+".js")
			if err != nil {
				return err
			}
			if err := writeVendored(filepath.Join(dir, cfg.JS, name+".js"), src, *overwrite); err != nil {
				return err
			}
		}
	}

	notice, err := fs.ReadFile(gsxui.Files, "NOTICE.md")
	if err != nil {
		return err
	}
	if err := writeVendored(filepath.Join(dir, cfg.UI, "NOTICE.md"), notice, true); err != nil {
		return err
	}

	if err := regenBarrel(dir, cfg, *overwrite); err != nil {
		return err
	}
	if err := runCommand(dir, "go", "tool", "gsx", "generate"); err != nil {
		return fmt.Errorf("gsx generate: %w — if the gsx tool is missing, run 'gsxui init' (or 'go get -tool github.com/gsxhq/gsx/cmd/gsx@latest')", err)
	}
	fmt.Println("done — build with: go build ./...")
	return nil
}

// barrelHeader is the first line Barrel emits — its presence marks index.js
// as gsxui-generated and safe to regenerate freely.
const barrelHeader = "// Generated by gsxui — edit by adding/removing components, not by hand."

// regenBarrel rewrites index.js from the behaviors present on disk. A
// user-authored index.js (one that doesn't start with barrelHeader) is left
// alone unless overwrite is set, matching writeVendored's contract.
func regenBarrel(dir string, cfg Config, overwrite bool) error {
	indexPath := filepath.Join(dir, cfg.JS, "index.js")
	if existing, err := os.ReadFile(indexPath); err == nil && !overwrite {
		if !strings.HasPrefix(string(existing), barrelHeader) {
			return fmt.Errorf("%s differs from the gsxui version — pass --overwrite to replace it", indexPath)
		}
	}
	matches, err := filepath.Glob(filepath.Join(dir, cfg.JS, "*.js"))
	if err != nil {
		return err
	}
	var behaviors []string
	for _, m := range matches {
		base := filepath.Base(m)
		if base == "index.js" || base == "gsxui.js" {
			continue
		}
		behaviors = append(behaviors, strings.TrimSuffix(base, ".js"))
	}
	sort.Strings(behaviors)
	return os.WriteFile(indexPath, Barrel(behaviors), 0o644)
}

func runList(args []string) error {
	if len(args) != 0 {
		return fmt.Errorf("usage: gsxui list")
	}
	names, err := registry.Components()
	if err != nil {
		return err
	}
	for _, n := range names {
		deps, err := registry.Deps(n)
		if err != nil {
			return err
		}
		line := n
		if registry.HasJS(n) {
			line += " (js)"
		}
		if len(deps) > 0 {
			line += " — requires " + strings.Join(deps, ", ")
		}
		fmt.Println(line)
	}
	return nil
}
