package cli

import (
	"fmt"
	"runtime/debug"
	"sync"
)

// gsxModule is the gsx module whose runtime and code generator a gsxui
// project is initialised with.
const gsxModule = "github.com/gsxhq/gsx"

// gsxVersion is the gsx version `gsxui init` pins a project to: the one this
// gsxui binary was built against. gsxui links gsx (its parser and printer
// rewrite vendored .gsx sources), so the build info always records it, at the
// version gsxui's go.mod selects. Vendored components are generated by and
// tested against that gsx; a newer one may change syntax or codegen they rely
// on.
var gsxVersion = sync.OnceValues(func() (string, error) {
	info, ok := debug.ReadBuildInfo()
	if !ok {
		return "", fmt.Errorf("determine the gsx version: gsxui was built without module build info")
	}
	return moduleVersion(info, gsxModule)
})

// moduleVersion is the version of module path that info's build selected. A
// replaced module reports the version its requirement names, which is what a
// consuming project can fetch.
func moduleVersion(info *debug.BuildInfo, path string) (string, error) {
	for _, dep := range info.Deps {
		if dep.Path != path {
			continue
		}
		if dep.Version == "" || dep.Version == "(devel)" {
			return "", fmt.Errorf("determine the %s version: build info records no version for it", path)
		}
		return dep.Version, nil
	}
	return "", fmt.Errorf("determine the %s version: gsxui's build info does not list it", path)
}
