package cli

import (
	"strings"
	"testing"
)

func TestRewriteGsx(t *testing.T) {
	in := `package dialog

import (
	"github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui/button"
)
`
	out := string(RewriteGsx([]byte(in), "example.com/app", "components"))
	if !strings.Contains(out, `"example.com/app/components/button"`) {
		t.Fatalf("ui import not rewritten:\n%s", out)
	}
	if !strings.Contains(out, `"github.com/gsxhq/gsx"`) {
		t.Fatalf("gsx runtime import must be untouched:\n%s", out)
	}
	if strings.Contains(out, "gsxhq/gsxui") {
		t.Fatalf("gsxui reference left behind:\n%s", out)
	}
}

func TestRewriteJS(t *testing.T) {
	in := `import { on, emit } from "../core/gsxui.js";`
	out := string(RewriteJS([]byte(in)))
	if out != `import { on, emit } from "./core/gsxui.js";` {
		t.Fatalf("got %q", out)
	}
}

func TestBarrel(t *testing.T) {
	got := string(Barrel([]string{"dropdown", "dialog"}))
	want := `// Generated by gsxui — edit by adding/removing components, not by hand.
export * from "./core/gsxui.js";
import "./dialog.js";
import "./dropdown.js";
`
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestBarrelEmpty(t *testing.T) {
	got := string(Barrel(nil))
	want := `// Generated by gsxui — edit by adding/removing components, not by hand.
export * from "./core/gsxui.js";
`
	if got != want {
		t.Fatalf("got:\n%s", got)
	}
}
