package cli

import (
	"bytes"
	"fmt"
	"sort"
)

// RewriteGsx retargets gsxui-internal imports at the user's module. One
// prefix rule covers both the flat ui package and ui/icon. The gsx runtime
// import (github.com/gsxhq/gsx) is deliberately untouched.
func RewriteGsx(src []byte, module, uiDir string) []byte {
	return bytes.ReplaceAll(src,
		[]byte(`"github.com/gsxhq/gsxui/ui`),
		[]byte(`"`+module+`/`+uiDir))
}

// Barrel renders index.js for the installed behavior set. Core (gsxui.js)
// sits beside the behaviors, so no path rewriting is needed anywhere in JS.
func Barrel(behaviors []string) []byte {
	sorted := append([]string(nil), behaviors...)
	sort.Strings(sorted)
	var b bytes.Buffer
	b.WriteString("// Generated by gsxui — edit by adding/removing components, not by hand.\n")
	b.WriteString("export * from \"./gsxui.js\";\n")
	for _, name := range sorted {
		fmt.Fprintf(&b, "import \"./%s.js\";\n", name)
	}
	return b.Bytes()
}
