package cli

import (
	"strings"
	"testing"
)

func TestRewriteGsx(t *testing.T) {
	in := `package ui

import (
	"github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
)
`
	out := string(RewriteGsx([]byte(in), "example.com/app", "ui"))
	if !strings.Contains(out, `"example.com/app/ui"`) {
		t.Fatalf("ui import not rewritten:\n%s", out)
	}
	if !strings.Contains(out, `"github.com/gsxhq/gsx"`) {
		t.Fatalf("gsx runtime import must be untouched:\n%s", out)
	}
	if strings.Contains(out, "gsxhq/gsxui") {
		t.Fatalf("gsxui reference left behind:\n%s", out)
	}
}

func TestRewriteGsxIcon(t *testing.T) {
	in := `package ui

import (
	"github.com/gsxhq/gsxui/ui/icon"
)
`
	out := string(RewriteGsx([]byte(in), "example.com/app", "ui"))
	if !strings.Contains(out, `"example.com/app/ui/icon"`) {
		t.Fatalf("icon import not rewritten:\n%s", out)
	}
	if strings.Contains(out, "gsxhq/gsxui") {
		t.Fatalf("gsxui reference left behind:\n%s", out)
	}
}

func TestRewriteGsxCustomUIDir(t *testing.T) {
	in := `import "github.com/gsxhq/gsxui/ui"`
	out := string(RewriteGsx([]byte(in), "example.com/app", "components/ui"))
	if !strings.Contains(out, `"example.com/app/components/ui"`) {
		t.Fatalf("ui import not rewritten for custom uiDir:\n%s", out)
	}
}

func TestBarrel(t *testing.T) {
	got := string(Barrel([]string{"dropdown", "dialog"}))
	want := `// Generated by gsxui — edit by adding/removing components, not by hand.
export * from "./gsxui.js";
import "./dialog.js";
import "./dropdown.js";
`
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestBarrelEmpty(t *testing.T) {
	got := string(Barrel(nil))
	want := `// Generated by gsxui — edit by adding/removing components, not by hand.
export * from "./gsxui.js";
`
	if got != want {
		t.Fatalf("got:\n%s", got)
	}
}
