package cli

import (
	"bytes"
	"strings"
	"testing"
)

func TestRewriteGsxRewritesOnlyExactUIImports(t *testing.T) {
	in := []byte(`package ui

import "github.com/gsxhq/gsx"
import root "github.com/gsxhq/gsxui/ui"
import _ "github.com/gsxhq/gsxui/ui/icon"
import . "github.com/gsxhq/gsxui/ui/internal/helpers"

const commentLookalike = "github.com/gsxhq/gsxui/ui"

// github.com/gsxhq/gsxui/ui/icon in a comment must stay unchanged.
component Example() {
	<div data-path="github.com/gsxhq/gsxui/ui/icon" />
}
`)

	got, err := RewriteGsx(in, "example.com/app", "components/ui")
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		`import "github.com/gsxhq/gsx"`,
		`root "example.com/app/components/ui"`,
		`_ "example.com/app/components/ui/icon"`,
		`. "example.com/app/components/ui/internal/helpers"`,
		`const commentLookalike = "github.com/gsxhq/gsxui/ui"`,
		`// github.com/gsxhq/gsxui/ui/icon in a comment must stay unchanged.`,
		`data-path="github.com/gsxhq/gsxui/ui/icon"`,
	} {
		if !strings.Contains(string(got), want) {
			t.Errorf("rewritten GSX missing %q:\n%s", want, got)
		}
	}
}

func TestRewriteGsxPreservesLookalikeImportPaths(t *testing.T) {
	in := []byte(`package ui

import (
	"github.com/gsxhq/gsxui/ui2"
	"github.com/gsxhq/gsxui/ui?variant=maia"
	"github.com/gsxhq/gsxui/ui%2Ficon"
	"github.com/gsxhq/gsxui/u\x69/icon"
)
`)

	got, err := RewriteGsx(in, "example.com/app", "ui")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, in) {
		t.Fatalf("lookalike imports changed:\n%s\nwant:\n%s", got, in)
	}
}

func TestRewriteGsxHandlesGroupedAliasesAndIsIdempotent(t *testing.T) {
	in := []byte(`package ui

import (
	alias "github.com/gsxhq/gsxui/ui"
	_ "github.com/gsxhq/gsxui/ui/icon"
	. "github.com/gsxhq/gsxui/ui/helpers"
)
`)

	once, err := RewriteGsx(in, "example.com/app", "ui")
	if err != nil {
		t.Fatal(err)
	}
	twice, err := RewriteGsx(once, "example.com/app", "ui")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(twice, once) {
		t.Fatalf("second rewrite changed output:\n%s\nfirst:\n%s", twice, once)
	}
}

func TestRewriteGsxRejectsMalformedSource(t *testing.T) {
	in := []byte(`package ui

import "github.com/gsxhq/gsxui/ui"

component Broken( {
`)
	if _, err := RewriteGsx(in, "example.com/app", "ui"); err == nil {
		t.Fatal("RewriteGsx accepted malformed GSX")
	}
}

func TestRewriteGsxRejectsInvalidDestination(t *testing.T) {
	tests := []struct {
		name   string
		module string
		uiDir  string
	}{
		{name: "empty module", module: "", uiDir: "ui"},
		{name: "module query", module: "example.com/app?style=maia", uiDir: "ui"},
		{name: "module alias", module: "example.com/app/../other", uiDir: "ui"},
		{name: "empty UI directory", module: "example.com/app", uiDir: ""},
		{name: "absolute UI directory", module: "example.com/app", uiDir: "/ui"},
		{name: "escaping UI directory", module: "example.com/app", uiDir: "../ui"},
		{name: "unclean UI directory", module: "example.com/app", uiDir: "components/../ui"},
		{name: "backslash UI directory", module: "example.com/app", uiDir: `components\ui`},
		{name: "query UI directory", module: "example.com/app", uiDir: "ui?style=maia"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if _, err := RewriteGsx([]byte("package ui\n"), tt.module, tt.uiDir); err == nil {
				t.Fatal("RewriteGsx accepted invalid destination")
			}
		})
	}
}

func TestBarrel(t *testing.T) {
	got := string(Barrel([]string{"dropdown", "dialog"}))
	want := `// Generated by gsxui — edit by adding/removing components, not by hand.
export * from "./gsxui.js";
import "./dialog.js";
import "./dropdown.js";
`
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestBarrelEmpty(t *testing.T) {
	got := string(Barrel(nil))
	want := `// Generated by gsxui — edit by adding/removing components, not by hand.
export * from "./gsxui.js";
`
	if got != want {
		t.Fatalf("got:\n%s", got)
	}
}
