package cli

import (
	"bytes"
	"fmt"
	"sort"
)

// RewriteGsx retargets gsxui-internal imports at the user's module. The gsx
// runtime import (github.com/gsxhq/gsx) is deliberately untouched.
func RewriteGsx(src []byte, module, uiDir string) []byte {
	return bytes.ReplaceAll(src,
		[]byte(`"github.com/gsxhq/gsxui/ui/`),
		[]byte(`"`+module+`/`+uiDir+`/`))
}

// RewriteJS retargets a behavior module's core import for the flat vendored
// layout: behaviors sit next to index.js, core below them.
func RewriteJS(src []byte) []byte {
	return bytes.ReplaceAll(src,
		[]byte(`"../core/gsxui.js"`),
		[]byte(`"./core/gsxui.js"`))
}

// Barrel renders index.js for the installed behavior set.
func Barrel(behaviors []string) []byte {
	sorted := append([]string(nil), behaviors...)
	sort.Strings(sorted)
	var b bytes.Buffer
	b.WriteString("// Generated by gsxui — edit by adding/removing components, not by hand.\n")
	b.WriteString("export * from \"./core/gsxui.js\";\n")
	for _, name := range sorted {
		fmt.Fprintf(&b, "import \"./%s.js\";\n", name)
	}
	return b.Bytes()
}
