// Code generated by gsx; DO NOT EDIT.

package inputotp

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

//line pattern.gsx:5:1
// Pattern mirrors shadcn's own input-otp-pattern.tsx, which feeds the
// input-otp library's REGEXP_ONLY_DIGITS_AND_CHARS to both native
// validation and live keystroke filtering with a single anchored regex.
// This port needs two DIFFERENT attributes for those two different jobs —
// see ui/input-otp.gsx's own DECISION doc comment: the native HTML5
// pattern attribute stays whole-string-anchored ("[0-9]*", validity only,
// browser-native), while data-gsxui-input-otp-pattern is the UNANCHORED
// per-character class ui/input-otp.js actually tests one keystroke at a
// time against ("[0-9]", not "[0-9]*"). Copying shadcn's own anchored
// pattern constant into the per-character attribute would reject every
// character typed.

//line pattern.gsx:16:1
func Pattern() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pattern.gsx:17:2
		_gsxgw.S("<div class=\"flex flex-col gap-2\">")
//line pattern.gsx:18:3
		_gsxgw.Node(ctx, ui.InputOTP(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line pattern.gsx:19:4
			_gsxgw.Node(ctx, ui.InputOTPGroup(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line pattern.gsx:20:5
				_gsxgw.Node(ctx, ui.InputOTPSlot(nil))
//line pattern.gsx:21:5
				_gsxgw.Node(ctx, ui.InputOTPSlot(nil))
//line pattern.gsx:22:5
				_gsxgw.Node(ctx, ui.InputOTPSlot(nil))
//line pattern.gsx:23:5
				_gsxgw.Node(ctx, ui.InputOTPSlot(nil))
//line pattern.gsx:24:5
				_gsxgw.Node(ctx, ui.InputOTPSlot(nil))
//line pattern.gsx:25:5
				_gsxgw.Node(ctx, ui.InputOTPSlot(nil))
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "maxlength", Value: "6"}}, _gsxrt.Attrs{{Key: "pattern", Value: "[0-9]*"}}, _gsxrt.Attrs{{Key: "data-gsxui-input-otp-pattern", Value: "[0-9]"}})))
//line pattern.gsx:28:3
		_gsxgw.S("<p class=\"text-sm text-muted-foreground\">Digits only. data-gsxui-input-otp-pattern takes an unanchored per-character class, not a whole-string-anchored regex — see ui/input-otp.gsx's own doc comment for why.</p></div>")
		return _gsxgw.Err()
	})
}
