// Code generated by gsx; DO NOT EDIT.

package inputotp

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

//line rtl.gsx:5:1
// Rtl wraps Basic's own 6-digit/2-group OTP layout in an Arabic dir="rtl"
// form context (a label plus the surrounding div), but does NOT force
// dir="rtl" onto the OTP widget itself: ui/input-otp.gsx pins dir="ltr" on
// both InputOTP's own root and InputOTPGroup by design (see its own ADAPT
// doc comments) so the digit slots always read left-to-right regardless of
// document direction, matching shadcn's own input-otp behavior under RTL.
// The label and page chrome flip to RTL; the OTP slots themselves don't.

//line rtl.gsx:12:1
func Rtl() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:13:2
		_gsxgw.S("<div dir=\"rtl\" lang=\"ar\">")
//line rtl.gsx:14:3
		_gsxgw.S("<label class=\"mb-2 block text-sm font-medium\">رمز التحقق</label>")
//line rtl.gsx:15:3
		_gsxgw.Node(ctx, ui.InputOTP(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:16:4
			_gsxgw.Node(ctx, ui.InputOTPGroup(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:17:5
				_gsxgw.Node(ctx, ui.InputOTPSlot(_gsxrt.Attrs{{Key: "aria-invalid", Value: "true"}}))
//line rtl.gsx:18:5
				_gsxgw.Node(ctx, ui.InputOTPSlot(nil))
//line rtl.gsx:19:5
				_gsxgw.Node(ctx, ui.InputOTPSlot(nil))
				return _gsxgw.Err()
			}), nil))
//line rtl.gsx:21:4
			_gsxgw.Node(ctx, ui.InputOTPSeparator(nil))
//line rtl.gsx:22:4
			_gsxgw.Node(ctx, ui.InputOTPGroup(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:23:5
				_gsxgw.Node(ctx, ui.InputOTPSlot(nil))
//line rtl.gsx:24:5
				_gsxgw.Node(ctx, ui.InputOTPSlot(nil))
//line rtl.gsx:25:5
				_gsxgw.Node(ctx, ui.InputOTPSlot(nil))
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "maxlength", Value: "6"}}, _gsxrt.Attrs{{Key: "aria-invalid", Value: "true"}})))
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}
