// Code generated by gsx; DO NOT EDIT.

package card

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	uicard "github.com/gsxhq/gsxui/ui/card"
	_gsxio "io"
)

// Attrs demonstrates class-merge override: class="py-8" replaces Card's
// default py-6 — tailwind-merge resolves same-property conflicts, caller
// wins, same mechanism every gsxui component uses for its fallthrough attrs.

//line attrs.gsx:8:1
func Attrs() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line attrs.gsx:9:2
		_gsxgw.Node(ctx, uicard.Card(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line attrs.gsx:10:3
			_gsxgw.Node(ctx, uicard.CardHeader(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line attrs.gsx:11:4
				_gsxgw.Node(ctx, uicard.CardTitle(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("Roomier card")
					return _gsxgw.Err()
				}), nil))
//line attrs.gsx:12:4
				_gsxgw.Node(ctx, uicard.CardDescription(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("py-8 overrides py-6; the rest of the class list merges untouched.")
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
//line attrs.gsx:14:3
			_gsxgw.Node(ctx, uicard.CardContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line attrs.gsx:15:4
				_gsxgw.S("<p class=\"text-sm text-muted-foreground\">Every part accepts attrs the same way — this isn't Card-specific.</p>")
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "class", Value: "py-8"}}))
		return _gsxgw.Err()
	})
}
