// Code generated by gsx; DO NOT EDIT.

package card

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

//line compound.gsx:7:1
// Compound composes every Card part: a border-b header with title,
// description and action, content, and a border-t footer.

//line compound.gsx:9:1
func Compound() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line compound.gsx:10:2
		_gsxgw.Node(ctx, ui.Card(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line compound.gsx:11:3
			_gsxgw.Node(ctx, ui.CardHeader(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line compound.gsx:12:4
				_gsxgw.Node(ctx, ui.CardTitle(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("Notifications")
					return _gsxgw.Err()
				}), nil))
//line compound.gsx:13:4
				_gsxgw.Node(ctx, ui.CardDescription(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("You have 3 unread messages.")
					return _gsxgw.Err()
				}), nil))
//line compound.gsx:14:4
				_gsxgw.Node(ctx, ui.CardAction(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line compound.gsx:15:5
					_gsxgw.Node(ctx, ui.Badge("secondary", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("New")
						return _gsxgw.Err()
					}), nil))
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), _gsxrt.Attrs{{Key: "class", Value: "border-b"}}))
//line compound.gsx:18:3
			_gsxgw.Node(ctx, ui.CardContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line compound.gsx:19:4
				_gsxgw.S("<p class=\"text-sm text-muted-foreground\">Push notifications are enabled for this device.</p>")
				return _gsxgw.Err()
			}), nil))
//line compound.gsx:21:3
			_gsxgw.Node(ctx, ui.CardFooter(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line compound.gsx:22:4
				_gsxgw.Node(ctx, ui.Button("", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("Mark all as read")
					return _gsxgw.Err()
				}), _gsxrt.Attrs{{Key: "class", Value: "w-full"}}))
				return _gsxgw.Err()
			}), _gsxrt.Attrs{{Key: "class", Value: "border-t"}}))
			return _gsxgw.Err()
		}), nil))
		return _gsxgw.Err()
	})
}
