// Code generated by gsx; DO NOT EDIT.

package accordion

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	uiaccordion "github.com/gsxhq/gsxui/ui/accordion"
	_gsxio "io"
)

// Compact overrides AccordionContent's default pb-4 with a caller pb-2 —
// tailwind-merge drops the base utility, same class-merge story as every
// other component.

//line compact.gsx:8:1
func Compact() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line compact.gsx:9:2
		_gsxgw.Node(ctx, uiaccordion.Accordion("compact", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line compact.gsx:10:3
			_gsxgw.Node(ctx, uiaccordion.AccordionItem("compact", true, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line compact.gsx:11:4
				_gsxgw.Node(ctx, uiaccordion.AccordionTrigger(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("Shipping")
					return _gsxgw.Err()
				}), nil))
//line compact.gsx:12:4
				_gsxgw.Node(ctx, uiaccordion.AccordionContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("Ships within 2 business days.")
					return _gsxgw.Err()
				}), _gsxrt.Attrs{{Key: "class", Value: "pb-2"}}))
				return _gsxgw.Err()
			}), nil))
//line compact.gsx:14:3
			_gsxgw.Node(ctx, uiaccordion.AccordionItem("compact", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line compact.gsx:15:4
				_gsxgw.Node(ctx, uiaccordion.AccordionTrigger(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("Returns")
					return _gsxgw.Err()
				}), nil))
//line compact.gsx:16:4
				_gsxgw.Node(ctx, uiaccordion.AccordionContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("30-day return window.")
					return _gsxgw.Err()
				}), _gsxrt.Attrs{{Key: "class", Value: "pb-2"}}))
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), nil))
		return _gsxgw.Err()
	})
}
