// Code generated by gsx; DO NOT EDIT.

package table

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	uitable "github.com/gsxhq/gsxui/ui/table"
	_gsxio "io"
)

// Data renders a compound table: caption, header, and three rows built
// from a slice via a for-range loop; the Unpaid row's status gets a
// conditional class.

//line data.gsx:8:1
func Data() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line data.gsx:9:2
		invoices := []struct{ Invoice, Status, Amount string }{{"INV001", "Paid", "$250.00"}, {"INV002", "Pending", "$150.00"}, {"INV003", "Unpaid", "$350.00"}}
//line data.gsx:10:2
		_gsxgw.Node(ctx, uitable.Table(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line data.gsx:11:3
			_gsxgw.Node(ctx, uitable.TableCaption(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("A list of your recent invoices.")
				return _gsxgw.Err()
			}), nil))
//line data.gsx:12:3
			_gsxgw.Node(ctx, uitable.TableHeader(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line data.gsx:13:4
				_gsxgw.Node(ctx, uitable.TableRow(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line data.gsx:13:22
					_gsxgw.Node(ctx, uitable.TableHead(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Invoice")
						return _gsxgw.Err()
					}), nil))
//line data.gsx:13:68
					_gsxgw.Node(ctx, uitable.TableHead(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Status")
						return _gsxgw.Err()
					}), nil))
//line data.gsx:13:113
					_gsxgw.Node(ctx, uitable.TableHead(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Amount")
						return _gsxgw.Err()
					}), _gsxrt.Attrs{{Key: "class", Value: "text-right"}}))
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
//line data.gsx:15:3
			_gsxgw.Node(ctx, uitable.TableBody(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line data.gsx:16:4
				for _, inv := range invoices {
//line data.gsx:17:5
					_gsxgw.Node(ctx, uitable.TableRow(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line data.gsx:18:6
						_gsxgw.Node(ctx, uitable.TableCell(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
//line data.gsx:18:45
							_gsxgw.Text(string(inv.Invoice))
							return _gsxgw.Err()
						}), _gsxrt.Attrs{{Key: "class", Value: "font-medium"}}))
//line data.gsx:19:6
						_gsxgw.Node(ctx, uitable.TableCell(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
//line data.gsx:19:78
							_gsxgw.Text(string(inv.Status))
							return _gsxgw.Err()
						}), _gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.ClassIf("text-destructive", inv.Status == "Unpaid"))}}))
//line data.gsx:20:6
						_gsxgw.Node(ctx, uitable.TableCell(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
							_gsxgw := _gsxrt.W(_gsxw)
//line data.gsx:20:44
							_gsxgw.Text(string(inv.Amount))
							return _gsxgw.Err()
						}), _gsxrt.Attrs{{Key: "class", Value: "text-right"}}))
						return _gsxgw.Err()
					}), nil))
				}
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), nil))
		return _gsxgw.Err()
	})
}
