// Code generated by gsx; DO NOT EDIT.

package switchctl

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	uilabel "github.com/gsxhq/gsxui/ui/label"
	uiswitch "github.com/gsxhq/gsxui/ui/switchctl"
	_gsxio "io"
)

// Basic pairs an unchecked and a checked Switch, each with a Label.

//line basic.gsx:14:1
func Basic() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:15:2
		_gsxgw.S("<div class=\"flex flex-col gap-3\">")
//line basic.gsx:16:3
		_gsxgw.S("<div class=\"flex items-center gap-2\">")
//line basic.gsx:17:4
		_gsxgw.Node(ctx, uiswitch.Switch(_gsxrt.Attrs{{Key: "id", Value: "switch-basic-airplane"}}))
//line basic.gsx:18:4
		_gsxgw.Node(ctx, uilabel.Label(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
			_gsxgw.S("Airplane mode")
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "for", Value: "switch-basic-airplane"}}))
		_gsxgw.S("</div>")
//line basic.gsx:20:3
		_gsxgw.S("<div class=\"flex items-center gap-2\">")
//line basic.gsx:21:4
		_gsxgw.Node(ctx, uiswitch.Switch(_gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "id", Value: "switch-basic-wifi"}}, _gsxrt.Attrs{{Key: "checked", Value: true}})))
//line basic.gsx:22:4
		_gsxgw.Node(ctx, uilabel.Label(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
			_gsxgw.S("Wi-Fi")
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "for", Value: "switch-basic-wifi"}}))
		_gsxgw.S("</div></div>")
		return _gsxgw.Err()
	})
}
