// Code generated by gsx; DO NOT EDIT.

package switchctl

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

//line rtl.gsx:5:1
// Rtl mirrors shadcn's own switch-rtl demo: a horizontal Field pairing a
// label+description with a Switch, translated to Arabic and wrapped in
// dir="rtl".

//line rtl.gsx:8:1
func Rtl() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:9:2
		_gsxgw.Node(ctx, ui.Field("horizontal", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:10:3
			_gsxgw.Node(ctx, ui.FieldContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line rtl.gsx:11:4
				_gsxgw.Node(ctx, ui.FieldLabel(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("المشاركة عبر الأجهزة")
					return _gsxgw.Err()
				}), _gsxrt.Attrs{{Key: "for", Value: "switch-rtl-focus-mode"}}))
//line rtl.gsx:12:4
				_gsxgw.Node(ctx, ui.FieldDescription(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("يتم مشاركة التركيز عبر الأجهزة، ويتم إيقاف تشغيله عند مغادرة التطبيق.")
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
//line rtl.gsx:14:3
			_gsxgw.Node(ctx, ui.Switch(_gsxrt.Attrs{{Key: "id", Value: "switch-rtl-focus-mode"}}))
			return _gsxgw.Err()
		}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "dir", Value: "rtl"}}, _gsxrt.Attrs{{Key: "lang", Value: "ar"}}, _gsxrt.Attrs{{Key: "class", Value: "max-w-sm"}})))
		return _gsxgw.Err()
	})
}
