// Code generated by gsx; DO NOT EDIT.

package sonner

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

//line server.gsx:5:1
// Server demonstrates the real-world flash-message pattern: the SERVER
// renders a toast card and the browser adopts it into the same stacking /
// timer / dismiss lifecycle as a JS-triggered toast — with zero HTMX-specific
// code. Two paths are shown:
//
//  1. A static ui.Toast rendered inline (the markup showcase). On a full page
//     load a server would drain its session/request flashes into <ui.Toaster/>
//     exactly like this; ui/sonner.js adopts every li[data-slot="toast"]
//     present at init.
//  2. A button + inline <script> that clones a pre-rendered server row (the
//     ui.Toast wrapped in the <template data-server-flash-demo> below) and
//     appends it into #gsxui-toaster — precisely what an HTMX out-of-band
//     swap (hx-swap-oob="beforeend:#gsxui-toaster") does on the wire. The
//     MutationObserver on the <ol> adopts it; no page-specific lifecycle code.
//
// This is the one-viewport-per-page model: the server is the single source of
// toast markup, ui.Toaster is mounted once, and appends flow in from anywhere.

//line server.gsx:22:1
func Server() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line server.gsx:23:2
		_gsxgw.S("<div class=\"flex flex-col items-start gap-4\">")
//line server.gsx:24:3
		_gsxgw.Node(ctx, ui.Toast("success", "Profile updated", "Your changes have been saved.", "", "", nil))
//line server.gsx:25:3
		_gsxgw.Node(ctx, ui.Button("outline", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
			_gsxgw.S("Append a server flash")
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "id", Value: "sonner-server-flash-btn"}}))
//line server.gsx:26:3
		_gsxgw.S("<template")
		_gsxgw.BoolAttr("data-server-flash-demo", true)
		_gsxgw.S(">")
//line server.gsx:27:4
		_gsxgw.Node(ctx, ui.Toast("info", "New message", "A server-rendered row, appended like an HTMX OOB swap.", "", "", nil))
		_gsxgw.S("</template>")
//line server.gsx:33:3
		_gsxgw.S("<script")
		_gsxgw.Nonce(ctx)
		_gsxgw.S(">\ndocument.getElementById(\"sonner-server-flash-btn\").addEventListener(\"click\", () => {\n\tconst tpl = document.querySelector(\"template[data-server-flash-demo]\");\n\tconst viewport = document.getElementById(\"gsxui-toaster\");\n\tif (!tpl || !viewport) return;\n\tviewport.appendChild(tpl.content.firstElementChild.cloneNode(true));\n});\n</script></div>")
		return _gsxgw.Err()
	})
}
