// Code generated by gsx; DO NOT EDIT.

package pages

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/site/hl"
	_gsxf0 "github.com/jackielii/structpages"
	_gsxio "io"
)

// NpmFree is the /docs/npm-free page: running gsxui without Vite — or npm —
// with real CLI output (copied from internal/cli/init.go's actual printed
// strings, not invented; a drift test pins the init summary snippet).
//
//line npm_free.gsx:5:1
type NpmFree struct{}

var npmFreeTOCItems = []docTOCItem{
	{ID: "initialize", Title: "Initialize without a scaffold", Depth: 2},
	{ID: "serve-scripts", Title: "Serve the scripts", Depth: 2},
	{ID: "build-css", Title: "Build the CSS", Depth: 2},
}

//line npm_free.gsx:16:1
func (n NpmFree) Page() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line npm_free.gsx:17:2
		_gsxgw.NodeResult(_gsxrendersiteLayout(ctx, _gsxgw, "npm-free", "npm-free", layoutDocs, npmFreeTOCItems, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line npm_free.gsx:18:3
			_gsxgw.S("<div data-doc=\"npm-free\" class=\"flex max-w-3xl flex-col gap-10 py-10\">")
//line npm_free.gsx:19:4
			_gsxgw.S("<div class=\"flex flex-col gap-4\">")
//line npm_free.gsx:20:5
			_gsxgw.S("<h1 class=\"text-3xl font-semibold tracking-tight\">npm-free</h1>")
//line npm_free.gsx:21:5
			_gsxgw.S("<p class=\"text-muted-foreground\">The recommended setup is the gsx scaffold with gsxui on top — ")
//line npm_free.gsx:22:70
			_gsxgw.S("<code>gsx init</code> then")
//line npm_free.gsx:23:6
			_gsxgw.S("<code>gsxui init</code>, as ")
//line npm_free.gsx:23:34
			_gsxgw.S("<a")
			_gsxv0, _gsxerr := _gsxf0.URLFor(ctx, (GettingStarted{}))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" href=\"")
			_gsxgw.URL(string(_gsxv0))
			_gsxgw.S("\">Getting Started</a> shows. But nothing in gsxui requires Vite — or npm: the component behaviors are dependency-free native ES modules, and the one CSS dependency (")
//line npm_free.gsx:25:22
			_gsxgw.S("<code>tw-animate-css</code>) is vendored as ")
//line npm_free.gsx:25:66
			_gsxgw.S("<code>web/gsxui/animate.css</code> so the stylesheet builds without ")
//line npm_free.gsx:26:32
			_gsxgw.S("<code>node_modules</code>.</p></div>")
//line npm_free.gsx:29:4
			_gsxgw.S("<section class=\"flex flex-col gap-3\">")
//line npm_free.gsx:30:5
			_gsxgw.NodeResult(_gsxrenderdocHeading(ctx, _gsxgw, npmFreeTOCItems[0], nil))
//line npm_free.gsx:31:5
			_gsxgw.S("<p>If ")
//line npm_free.gsx:32:9
			_gsxgw.S("<code>gsxui init</code> finds neither ")
//line npm_free.gsx:32:47
			_gsxgw.S("<code>vite.config.ts</code> nor ")
//line npm_free.gsx:32:79
			_gsxgw.S("<code>web/main.js</code>, it initializes in npm-free mode: no npm commands run and no ")
//line npm_free.gsx:33:63
			_gsxgw.S("<code>package.json</code> is written. Everything else matches the ")
//line npm_free.gsx:34:23
			_gsxgw.S("<a")
			_gsxv1, _gsxerr := _gsxf0.URLFor(ctx, (GettingStarted{}))
			if _gsxerr != nil {
				return _gsxerr
			}
			_gsxgw.S(" href=\"")
			_gsxgw.URL(string(_gsxv1))
			_gsxgw.S("\">standard setup</a> — the same CSS and JS entries are vendored, and the Go tooling is installed the same way.</p>")
//line npm_free.gsx:37:5
			_gsxgw.S("<pre>")
//line npm_free.gsx:37:10
			_gsxgw.S("<code>")
//line npm_free.gsx:37:16
			_gsxgw.Node(ctx, hl.Node("snippets/nonvite-init.output"))
			_gsxgw.S("</code></pre></section>")
//line npm_free.gsx:39:4
			_gsxgw.S("<section class=\"flex flex-col gap-3\">")
//line npm_free.gsx:40:5
			_gsxgw.NodeResult(_gsxrenderdocHeading(ctx, _gsxgw, npmFreeTOCItems[1], nil))
//line npm_free.gsx:41:5
			_gsxgw.S("<p>You own serving and CSS building. Serve the vendored JS directory statically and load the barrel with one module script tag — no bundler required, any bundler welcome:</p>")
//line npm_free.gsx:45:5
			_gsxgw.S("<pre>")
//line npm_free.gsx:45:10
			_gsxgw.S("<code>")
//line npm_free.gsx:45:16
			_gsxgw.Node(ctx, hl.Node("snippets/nonvite-serve.go"))
			_gsxgw.S("</code></pre></section>")
//line npm_free.gsx:47:4
			_gsxgw.S("<section class=\"flex flex-col gap-3\">")
//line npm_free.gsx:48:5
			_gsxgw.NodeResult(_gsxrenderdocHeading(ctx, _gsxgw, npmFreeTOCItems[2], nil))
//line npm_free.gsx:49:5
			_gsxgw.S("<p>Build the CSS entry with any Tailwind v4 tool — gsxui never installs or manages your build tooling. True to this page's title, the ")
//line npm_free.gsx:51:37
			_gsxgw.S("<a href=\"https://tailwindcss.com/docs/installation/tailwind-cli\">standalone Tailwind CLI</a> is the natural fit: a single binary from ")
//line npm_free.gsx:53:11
			_gsxgw.S("<a href=\"https://github.com/tailwindlabs/tailwindcss/releases/latest\">GitHub releases</a>, no npm involved. If you already have npm, its ")
//line npm_free.gsx:54:45
			_gsxgw.S("<code>@tailwindcss/cli</code> package takes the same flags. Then link the output from your pages:</p>")
//line npm_free.gsx:57:5
			_gsxgw.S("<pre>")
//line npm_free.gsx:57:10
			_gsxgw.S("<code>")
//line npm_free.gsx:57:16
			_gsxgw.Node(ctx, hl.Node("snippets/nonvite-css.sh"))
			_gsxgw.S("</code></pre></section></div>")
			return _gsxgw.Err()
		})))
		return _gsxgw.Err()
	})
}
