// Code generated by gsx; DO NOT EDIT.

package pages

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxcm "github.com/gsxhq/gsxui/merge"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
)

// Theme is the /theme route: a live editor over the shadcn-compatible
// CSS custom properties every gsxui component reads. Entirely client-side
// once loaded (web/theme.js) — the Go side only server-renders the default
// light/dark values so the page works before any JS runs.
//
//line theme.gsx:7:1
type Theme struct{}

// themeVar is one editable CSS custom property, with its default light and
// dark values.
type themeVar struct {
	Name  string
	Light string
	Dark  string
}

// themeGroup is a labeled cluster of related vars (matches the editor's
// section headings).
type themeGroup struct {
	Title string
	Vars  []themeVar
}

// themeGroups holds the default light/dark values for every editable
// tokens, grouped the way the editor displays them. Source of truth:
// assets/css/themes/default.css. The drift test keeps the editor and the
// vendored default theme byte-for-byte aligned.
var themeGroups = []themeGroup{
	{
		Title: "Base",
		Vars: []themeVar{
			{Name: "--background", Light: "oklch(1 0 0)", Dark: "oklch(0.145 0 0)"},
			{Name: "--foreground", Light: "oklch(0% 0 0)", Dark: "oklch(0.985 0 0)"},
			{Name: "--card", Light: "oklch(1 0 0)", Dark: "oklch(0.205 0 0)"},
			{Name: "--card-foreground", Light: "oklch(0% 0 0)", Dark: "oklch(0.985 0 0)"},
			{Name: "--popover", Light: "oklch(1 0 0)", Dark: "oklch(0.205 0 0)"},
			{Name: "--popover-foreground", Light: "oklch(0% 0 0)", Dark: "oklch(0.985 0 0)"},
		},
	},
	{
		Title: "Brand",
		Vars: []themeVar{
			{Name: "--primary", Light: "oklch(0% 0 0)", Dark: "oklch(0.922 0 0)"},
			{Name: "--primary-foreground", Light: "oklch(0.985 0 0)", Dark: "oklch(0.205 0 0)"},
			{Name: "--secondary", Light: "oklch(0.97 0 0)", Dark: "oklch(0.269 0 0)"},
			{Name: "--secondary-foreground", Light: "oklch(0.205 0 0)", Dark: "oklch(0.985 0 0)"},
			{Name: "--accent", Light: "oklch(0.97 0 0)", Dark: "oklch(0.371 0 0)"},
			{Name: "--accent-foreground", Light: "oklch(0.205 0 0)", Dark: "oklch(0.985 0 0)"},
		},
	},
	{
		Title: "Feedback",
		Vars: []themeVar{
			{Name: "--muted", Light: "oklch(0.97 0 0)", Dark: "oklch(0.269 0 0)"},
			{Name: "--muted-foreground", Light: "oklch(0.556 0 0)", Dark: "oklch(0.708 0 0)"},
			{Name: "--destructive", Light: "oklch(0.577 0.245 27.325)", Dark: "oklch(0.704 0.191 22.216)"},
			{Name: "--destructive-foreground", Light: "oklch(0.97 0.01 17)", Dark: "oklch(0.58 0.22 27)"},
		},
	},
	{
		Title: "Structure",
		Vars: []themeVar{
			{Name: "--border", Light: "oklch(0.922 0 0)", Dark: "oklch(1 0 0 / 10%)"},
			{Name: "--input", Light: "oklch(0.922 0 0)", Dark: "oklch(1 0 0 / 15%)"},
			{Name: "--ring", Light: "oklch(0.708 0 0)", Dark: "oklch(0.556 0 0)"},
			{Name: "--radius", Light: "0.625rem", Dark: "0.625rem"},
		},
	},
	{
		Title: "Sidebar",
		Vars: []themeVar{
			{Name: "--sidebar", Light: "oklch(0.985 0 0)", Dark: "oklch(0.205 0 0)"},
			{Name: "--sidebar-foreground", Light: "oklch(0% 0 0)", Dark: "oklch(0.985 0 0)"},
			{Name: "--sidebar-primary", Light: "oklch(0.205 0 0)", Dark: "oklch(0.488 0.243 264.376)"},
			{Name: "--sidebar-primary-foreground", Light: "oklch(0.985 0 0)", Dark: "oklch(0.985 0 0)"},
			{Name: "--sidebar-accent", Light: "oklch(0.97 0 0)", Dark: "oklch(0.269 0 0)"},
			{Name: "--sidebar-accent-foreground", Light: "oklch(0.205 0 0)", Dark: "oklch(0.985 0 0)"},
			{Name: "--sidebar-border", Light: "oklch(0.922 0 0)", Dark: "oklch(1 0 0 / 10%)"},
			{Name: "--sidebar-ring", Light: "oklch(0.708 0 0)", Dark: "oklch(0.439 0 0)"},
		},
	},
}

// ThemeGroups returns the default theme group definitions for testing purposes.
// This allows tests to verify that Go defaults stay in sync with CSS values.
func ThemeGroups() []themeGroup {
	return themeGroups
}

const tabBtnBase = "rounded-md border border-border px-3 py-1.5 text-sm font-medium transition-colors"

const themeImportPlaceholder = `:root {
  --primary: oklch(0.6 0.2 280);
}
.dark {
  --primary: oklch(0.7 0.2 280);
}`

//line theme.gsx:103:1
func (t Theme) Page() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line theme.gsx:104:2
		_gsxgw.NodeResult(_gsxrenderLayout(ctx, _gsxgw, "Theme", "", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line theme.gsx:105:3
			_gsxgw.S("<div class=\"flex flex-col gap-6 py-10\">")
//line theme.gsx:106:4
			_gsxgw.S("<div>")
//line theme.gsx:107:5
			_gsxgw.S("<h1 class=\"text-3xl font-semibold tracking-tight\">Theme editor</h1>")
//line theme.gsx:108:5
			_gsxgw.S("<p class=\"mt-2 max-w-2xl text-sm text-muted-foreground\">Edit the semantic CSS custom properties gsxui's components read. Paste a tweakcn/shadcn theme's root and dark blocks into Import to try it, or export what you build here as a ready-to-drop-in theme.</p></div>")
//line theme.gsx:112:4
			_gsxgw.S("<div class=\"grid grid-cols-1 gap-8 lg:grid-cols-2\">")
//line theme.gsx:113:5
			_gsxgw.S("<div class=\"flex flex-col gap-6\">")
//line theme.gsx:114:6
			for _, g := range themeGroups {
//line theme.gsx:115:7
				_gsxgw.S("<section class=\"flex flex-col gap-3\">")
//line theme.gsx:116:8
				_gsxgw.S("<h2 class=\"text-sm font-medium uppercase tracking-wide text-muted-foreground\">")
//line theme.gsx:116:86
				_gsxgw.Text(string(g.Title))
				_gsxgw.S("</h2>")
//line theme.gsx:117:8
				_gsxgw.S("<div class=\"flex flex-col gap-2\">")
//line theme.gsx:118:9
				_gsxgw.S("<div class=\"grid grid-cols-[minmax(0,120px)_1fr_1fr] gap-3 text-xs text-muted-foreground\">")
//line theme.gsx:119:10
				_gsxgw.S("<span></span>")
//line theme.gsx:120:10
				_gsxgw.S("<span>Light</span>")
//line theme.gsx:121:10
				_gsxgw.S("<span>Dark</span></div>")
//line theme.gsx:123:9
				for _, v := range g.Vars {
//line theme.gsx:124:10
					_gsxgw.S("<div>")
//line theme.gsx:125:11
					_gsxgw.S("<div class=\"grid grid-cols-[minmax(0,120px)_1fr_1fr] items-center gap-3\">")
//line theme.gsx:126:12
					_gsxgw.S("<label class=\"truncate font-mono text-xs text-muted-foreground\" title=\"")
					_gsxgw.AttrValue(string(v.Name))
					_gsxgw.S("\">")
//line theme.gsx:126:91
					_gsxgw.Text(string(v.Name))
					_gsxgw.S("</label>")
//line theme.gsx:127:12
					_gsxgw.S("<input type=\"text\" data-theme-var=\"")
					_gsxgw.AttrValue(string(v.Name))
					_gsxgw.S("\" data-theme-mode=\"light\" value=\"")
					_gsxgw.AttrValue(string(v.Light))
					_gsxgw.S("\" class=\"h-8 w-full min-w-0 rounded-md border border-input bg-transparent px-2 font-mono text-xs shadow-xs outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50\">")
//line theme.gsx:134:12
					_gsxgw.S("<input type=\"text\" data-theme-var=\"")
					_gsxgw.AttrValue(string(v.Name))
					_gsxgw.S("\" data-theme-mode=\"dark\" value=\"")
					_gsxgw.AttrValue(string(v.Dark))
					_gsxgw.S("\" class=\"h-8 w-full min-w-0 rounded-md border border-input bg-transparent px-2 font-mono text-xs shadow-xs outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50\"></div>")
//line theme.gsx:142:11
					if v.Name == "--radius" {
//line theme.gsx:143:12
						_gsxgw.S("<p class=\"col-start-2 col-span-2 mt-1 text-xs text-muted-foreground\">preview only — radius is theme-invariant in exports</p>")
					}
					_gsxgw.S("</div>")
				}
				_gsxgw.S("</div></section>")
			}
//line theme.gsx:152:6
			_gsxgw.S("<section class=\"flex flex-col gap-3 border-t border-border pt-6\">")
//line theme.gsx:153:7
			_gsxgw.S("<h2 class=\"text-sm font-medium uppercase tracking-wide text-muted-foreground\">Export</h2>")
//line theme.gsx:154:7
			_gsxgw.S("<div class=\"flex flex-wrap gap-2\">")
//line theme.gsx:155:8
			_gsxgw.Node(ctx, ui.Button("outline", "sm", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Copy CSS")
				return _gsxgw.Err()
			}), _gsxrt.Attrs{{Key: "data-theme-copy", Value: true}}))
//line theme.gsx:156:8
			_gsxgw.Node(ctx, ui.Button("outline", "sm", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Download gsxui.css")
				return _gsxgw.Err()
			}), _gsxrt.Attrs{{Key: "data-theme-download", Value: true}}))
			_gsxgw.S("</div>")
//line theme.gsx:158:7
			_gsxgw.S("<textarea")
			_gsxgw.BoolAttr("data-theme-export-output", true)
			_gsxgw.BoolAttr("readonly", true)
			_gsxgw.S(" rows=\"6\" class=\"hidden w-full rounded-md border border-input bg-transparent p-2 font-mono text-xs shadow-xs outline-none\"></textarea></section>")
//line theme.gsx:165:6
			_gsxgw.S("<section class=\"flex flex-col gap-3 border-t border-border pt-6\">")
//line theme.gsx:166:7
			_gsxgw.S("<h2 class=\"text-sm font-medium uppercase tracking-wide text-muted-foreground\">Import</h2>")
//line theme.gsx:167:7
			_gsxgw.S("<p class=\"text-xs text-muted-foreground\">Paste a tweakcn/shadcn-style root/dark block of --var: value; pairs.</p>")
//line theme.gsx:170:7
			_gsxgw.S("<textarea")
			_gsxgw.BoolAttr("data-theme-import", true)
			_gsxgw.S(" rows=\"6\" placeholder=\"")
			_gsxgw.AttrValue(string(themeImportPlaceholder))
			_gsxgw.S("\" class=\"w-full rounded-md border border-input bg-transparent p-2 font-mono text-xs shadow-xs outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50\"></textarea>")
//line theme.gsx:176:7
			_gsxgw.S("<div>")
//line theme.gsx:177:8
			_gsxgw.Node(ctx, ui.Button("outline", "sm", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Apply")
				return _gsxgw.Err()
			}), _gsxrt.Attrs{{Key: "data-theme-import-apply", Value: true}}))
			_gsxgw.S("</div></section></div>")
//line theme.gsx:181:5
			_gsxgw.S("<div class=\"flex flex-col gap-4\">")
//line theme.gsx:182:6
			_gsxgw.S("<div class=\"flex items-center gap-2\">")
//line theme.gsx:183:7
			_gsxgw.S("<button type=\"button\" data-theme-tab=\"light\" aria-pressed=\"true\" class=\"")
			_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(tabBtnBase), _gsxrt.Class("bg-accent text-accent-foreground"))
			_gsxgw.S("\">Light</button>")
//line theme.gsx:191:7
			_gsxgw.S("<button type=\"button\" data-theme-tab=\"dark\" aria-pressed=\"false\" class=\"")
			_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(tabBtnBase), _gsxrt.Class("text-muted-foreground hover:bg-accent hover:text-accent-foreground"))
			_gsxgw.S("\">Dark</button></div>")
//line theme.gsx:200:6
			_gsxgw.S("<div")
			_gsxgw.BoolAttr("data-theme-preview", true)
			_gsxgw.S(" class=\"flex flex-col gap-6 rounded-xl border border-border bg-background p-6\">")
//line theme.gsx:201:7
			_gsxgw.S("<div class=\"flex flex-wrap items-center gap-2\">")
//line theme.gsx:202:8
			_gsxgw.Node(ctx, ui.Button("", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Default")
				return _gsxgw.Err()
			}), nil))
//line theme.gsx:203:8
			_gsxgw.Node(ctx, ui.Button("secondary", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Secondary")
				return _gsxgw.Err()
			}), nil))
//line theme.gsx:204:8
			_gsxgw.Node(ctx, ui.Button("outline", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Outline")
				return _gsxgw.Err()
			}), nil))
//line theme.gsx:205:8
			_gsxgw.Node(ctx, ui.Button("ghost", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Ghost")
				return _gsxgw.Err()
			}), nil))
//line theme.gsx:206:8
			_gsxgw.Node(ctx, ui.Button("link", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Link")
				return _gsxgw.Err()
			}), nil))
//line theme.gsx:207:8
			_gsxgw.Node(ctx, ui.Button("destructive", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Destructive")
				return _gsxgw.Err()
			}), nil))
			_gsxgw.S("</div>")
//line theme.gsx:209:7
			_gsxgw.S("<div class=\"flex flex-wrap items-center gap-2\">")
//line theme.gsx:210:8
			_gsxgw.Node(ctx, ui.Badge("", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Default")
				return _gsxgw.Err()
			}), nil))
//line theme.gsx:211:8
			_gsxgw.Node(ctx, ui.Badge("secondary", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Secondary")
				return _gsxgw.Err()
			}), nil))
//line theme.gsx:212:8
			_gsxgw.Node(ctx, ui.Badge("outline", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Outline")
				return _gsxgw.Err()
			}), nil))
//line theme.gsx:213:8
			_gsxgw.Node(ctx, ui.Badge("destructive", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Destructive")
				return _gsxgw.Err()
			}), nil))
			_gsxgw.S("</div>")
//line theme.gsx:215:7
			_gsxgw.Node(ctx, ui.Card(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line theme.gsx:216:8
				_gsxgw.Node(ctx, ui.CardHeader(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line theme.gsx:217:9
					_gsxgw.Node(ctx, ui.CardTitle(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Profile")
						return _gsxgw.Err()
					}), nil))
//line theme.gsx:218:9
					_gsxgw.Node(ctx, ui.CardDescription(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Preview restyles live as you edit the tokens.")
						return _gsxgw.Err()
					}), nil))
					return _gsxgw.Err()
				}), nil))
//line theme.gsx:220:8
				_gsxgw.Node(ctx, ui.CardContent(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line theme.gsx:221:9
					_gsxgw.S("<div class=\"flex flex-col gap-3\">")
//line theme.gsx:222:10
					_gsxgw.S("<div class=\"flex flex-col gap-1.5\">")
//line theme.gsx:223:11
					_gsxgw.Node(ctx, ui.Label(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Name")
						return _gsxgw.Err()
					}), _gsxrt.Attrs{{Key: "for", Value: "theme-preview-name"}}))
//line theme.gsx:224:11
					_gsxgw.Node(ctx, ui.Input(_gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "id", Value: "theme-preview-name"}}, _gsxrt.Attrs{{Key: "placeholder", Value: "Ada Lovelace"}})))
					_gsxgw.S("</div>")
//line theme.gsx:226:10
					_gsxgw.S("<div class=\"flex items-center gap-2\">")
//line theme.gsx:227:11
					_gsxgw.Node(ctx, ui.Checkbox(_gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "id", Value: "theme-preview-terms"}}, _gsxrt.Attrs{{Key: "checked", Value: true}})))
//line theme.gsx:228:11
					_gsxgw.Node(ctx, ui.Label(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
						_gsxgw.S("Accept terms")
						return _gsxgw.Err()
					}), _gsxrt.Attrs{{Key: "for", Value: "theme-preview-terms"}}))
					_gsxgw.S("</div></div>")
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), _gsxrt.Attrs{{Key: "class", Value: "max-w-sm"}}))
//line theme.gsx:233:7
			_gsxgw.Node(ctx, ui.Alert("", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line theme.gsx:234:8
				_gsxgw.Node(ctx, ui.AlertTitle(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("Heads up")
					return _gsxgw.Err()
				}), nil))
//line theme.gsx:235:8
				_gsxgw.Node(ctx, ui.AlertDescription(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("This alert restyles with the tokens above.")
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
//line theme.gsx:237:7
			_gsxgw.Node(ctx, ui.Alert("destructive", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line theme.gsx:238:8
				_gsxgw.Node(ctx, ui.AlertTitle(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("Something went wrong")
					return _gsxgw.Err()
				}), nil))
//line theme.gsx:239:8
				_gsxgw.Node(ctx, ui.AlertDescription(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
					_gsxgw.S("The destructive variant uses --destructive.")
					return _gsxgw.Err()
				}), nil))
				return _gsxgw.Err()
			}), nil))
			_gsxgw.S("</div></div></div></div>")
			return _gsxgw.Err()
		})))
		return _gsxgw.Err()
	})
}
