// Code generated by gsx; DO NOT EDIT.

package calendar

import (
	"time"

	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	"github.com/gsxhq/gsxui/ui"
	_gsxio "io"
	_gsxty1 "time"
)

// DefaultMonth is the fixed month Basic renders when no month is given —
// 2026-01, deliberately never time.Now(): jstest/specs/calendar.spec.ts
// asserts exact grid contents (data-date values, the "Go and JS agree on …"
// diffs), and a test like that cannot depend on the day it runs.
//
//line basic.gsx:10:1
var DefaultMonth = time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)

// Basic renders a single-mode calendar pinned to DefaultMonth by default. A
// zero month falls back to DefaultMonth, so the zero-arg registration
// (site/examples/calendar.go's static Node) and jstest/harness's own
// per-request re-render (its Query hook, driven by ?month=) share one
// component instead of two.

//line basic.gsx:21:1
func Basic(month time.Time) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:22:2
		if month.IsZero() {
			month = DefaultMonth
		}
//line basic.gsx:27:2
		_gsxgw.Node(ctx, ui.Calendar("single", month, nil, *new(_gsxty1.Time), *new(_gsxty1.Time), time.Sunday, true, "label", 0, 0, *new(_gsxty1.Time), *new(_gsxty1.Time), nil, nil, "", nil))
		return _gsxgw.Err()
	})
}
