// Code generated by gsx; DO NOT EDIT.

package maia

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxcm "github.com/gsxhq/gsxui/merge"
	_gsxio "io"
)

//line card.gsx:5:1
// Card and its parts are the shadcn/ui Card compound set. Parts are plain
// sibling components — compose them in markup; no shared state, no context.

//line card.gsx:8:1
func Card(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderCard(ctx, _gsxgw, children, attrs)
	})
}

func _gsxrenderCard(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line card.gsx:9:2
	_gsxgw.S("<div class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("group/card"), _gsxrt.Class("ring-foreground/10 bg-card text-card-foreground gap-(--card-spacing) overflow-hidden rounded-2xl py-(--card-spacing) text-sm ring-1 [--card-spacing:--spacing(6)] has-[>img:first-child]:pt-0 data-[size=sm]:[--card-spacing:--spacing(4)] *:[img:first-child]:rounded-t-xl *:[img:last-child]:rounded-b-xl flex flex-col"), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-card"})
	_gsxgw.BoolAttr("data-gsxui-slot-card", true)
	_gsxgw.S(">")
//line card.gsx:17:3
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}

//line card.gsx:21:1
func CardHeader(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderCardHeader(ctx, _gsxgw, children, attrs)
	})
}

func _gsxrenderCardHeader(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line card.gsx:22:2
	_gsxgw.S("<div class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("gap-2 rounded-t-xl px-(--card-spacing) grid auto-rows-min grid-rows-[auto_auto]"), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-card-header"})
	_gsxgw.BoolAttr("data-gsxui-slot-card-header", true)
	_gsxgw.S(">")
//line card.gsx:27:3
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}

//line card.gsx:31:1
func CardTitle(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderCardTitle(ctx, _gsxgw, children, attrs)
	})
}

func _gsxrenderCardTitle(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line card.gsx:32:2
	_gsxgw.S("<div class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("text-base font-medium"), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-card-title"})
	_gsxgw.BoolAttr("data-gsxui-slot-card-title", true)
	_gsxgw.S(">")
//line card.gsx:32:81
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}

//line card.gsx:35:1
func CardDescription(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderCardDescription(ctx, _gsxgw, children, attrs)
	})
}

func _gsxrenderCardDescription(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line card.gsx:36:2
	_gsxgw.S("<div class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("text-muted-foreground text-sm"), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-card-description"})
	_gsxgw.BoolAttr("data-gsxui-slot-card-description", true)
	_gsxgw.S(">")
//line card.gsx:36:95
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}

//line card.gsx:39:1
func CardAction(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderCardAction(ctx, _gsxgw, children, attrs)
	})
}

func _gsxrenderCardAction(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line card.gsx:40:2
	_gsxgw.S("<div class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("col-start-2 row-span-2 row-start-1 self-start justify-self-end"), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-card-action"})
	_gsxgw.BoolAttr("data-gsxui-slot-card-action", true)
	_gsxgw.S(">")
//line card.gsx:45:3
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}

//line card.gsx:49:1
func CardContent(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderCardContent(ctx, _gsxgw, children, attrs)
	})
}

func _gsxrenderCardContent(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line card.gsx:50:2
	_gsxgw.S("<div class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("px-(--card-spacing)"), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-card-content"})
	_gsxgw.BoolAttr("data-gsxui-slot-card-content", true)
	_gsxgw.S(">")
//line card.gsx:50:81
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}

//line card.gsx:53:1
func CardFooter(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderCardFooter(ctx, _gsxgw, children, attrs)
	})
}

func _gsxrenderCardFooter(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line card.gsx:54:2
	_gsxgw.S("<div class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("rounded-b-xl px-(--card-spacing) flex"), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-card-footer"})
	_gsxgw.BoolAttr("data-gsxui-slot-card-footer", true)
	_gsxgw.S(">")
//line card.gsx:54:98
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}
