// Code generated by gsx; DO NOT EDIT.

package maia

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxcm "github.com/gsxhq/gsxui/merge"
	"github.com/gsxhq/gsxui/ui/icon"
	_gsxio "io"
	_gsxsc "strconv"
)

//line combobox.gsx:8:1
// Combobox and its parts are the shadcn/ui Combobox (registry/new-york-v4/
// ui/combobox.tsx) — a Base UI (@base-ui/react) filtered listbox, NOT the
// legacy Command+Popover "combobox" recipe some registries also ship
// (registry/new-york-v4/examples/combobox-*.tsx is that older pattern and is
// NOT this component's demo; the real demos, verified against
// content/docs/components/base/combobox.mdx, live at apps/v4/examples/base/
// combobox-*.tsx — see 2026-07-24 tier4 source map `## combobox`). Eleven
// parts ship here: Combobox, ComboboxInput, ComboboxTrigger, ComboboxClear,
// ComboboxContent, ComboboxList, ComboboxItem, ComboboxGroup, ComboboxLabel,
// ComboboxEmpty, ComboboxSeparator.
//
// MECHANISM (open/close + value model, ported from ui/select.gsx/select.js):
// ComboboxContent rides the same popover machinery as SelectContent —
// popover="auto" (top layer, light dismiss, free Esc), position:fixed
// anchoring below the input (ui/combobox.js), the discrete-transition
// enter/exit class block copied BYTE-IDENTICAL from ui/select.gsx (see
// below), and data-state="open" stamped synchronously BEFORE
// showPopover() — the flash-avoidance rule (docs/jsx-parity.md
// ## animations). MECHANISM (form bridge): when name != "", Combobox
// server-renders a real hidden sr-only <input type="text" name value>
// sibling — a non-JS form post, FormData collection, and a <label>'s
// click-through all see an ordinary text control — identical in shape to
// select.gsx's hidden <select> bridge (ui/select.gsx's own header), just a
// plain <input> here since a combobox's value is one string, not an
// enumerated <option> set. combobox.js keeps its .value synced on every
// commit/clear and dispatches a bubbling native "change", exactly like
// select.js:64-66 — Combobox and Select are interchangeable to a consumer
// listening for gsxui:select or the bridge's change event.
//
// ADAPT (filter: Base UI's `contains`, web-verified, NOT read from package
// source): @base-ui/react is absent from this checkout, so the filter
// algorithm can't be traced from dist/ the way select.js's typeahead or
// command.js's commandScore were. Base UI's published docs and issue
// tracker (web-verified, not a source read) name the Combobox default as
// `useFilter().contains` — an Intl.Collator-backed BOOLEAN match at
// sensitivity: "base" (case- and accent-insensitive), ported verbatim in
// ui/combobox.js. It returns a boolean, not a score: there is NO ranking
// and NO reordering, a real divergence from cmdk's command-score fuzzy
// engine (## command's own filter). combobox.js therefore only
// hides/shows items on every keystroke — it does NOT port command.js's
// DOM-reordering pass.
//
// GAP (no shared JS with ui/command.js, registry.Deps reasoning): a JS
// `import` from combobox.js into command.js would be invisible to
// internal/registry.Deps, which derives a component's dependency list by
// go/parser over the generated ui/*.x.go (Go source only) — command.js's
// own commandScore ranking engine has no Go representation to scan, so the
// CLI vendoring path would silently miss it. combobox.js duplicates only
// what it needs (its own `contains` matcher, its own highlight-tracking
// loop) rather than import command.js at all.
//
// GAP (deferred, not built — multi-select/chips and two React-only
// helpers): ComboboxChips, ComboboxChip, ComboboxChipsInput, ChipRemove
// (the multi-select chip-input composition) are not ported — this is a
// single-select port (Combobox's own `value` param is one string).
// ComboboxCollection (a React items-array-to-JSX mapping helper) is not
// needed: a gsx caller just writes an ordinary `for` loop over its own
// slice, calling ComboboxItem per element. useComboboxAnchor (`() =>
// React.useRef<HTMLDivElement|null>(null)`, existing only so a multi-select
// caller can share one ref between ComboboxChips and ComboboxContent) has
// no gsx equivalent to build — a gsx caller passes an anchor selector
// string instead, when/if chips ship.
//
// ADAPT (Content/List drop the anchor-width/available-height CSS vars):
// Base UI's Positioner primitive sets --anchor-width/--available-width/
// --available-height/--transform-origin custom properties at runtime for
// ComboboxContent/List to consume (registry/new-york-v4/ui/combobox.tsx's
// own w-(--anchor-width), max-w-(--available-width),
// origin-(--transform-origin), and List's own
// min(calc(--spacing(72)---spacing(9)),calc(var(--available-height)-
// -spacing(9))) tokens). combobox.js implements fixed positioning below the
// input instead (ui/select.js's own openContent model, not a full
// anchor-positioning engine), so those vars are never set; the tokens that
// depend on them are dropped in favor of plain nova-retargeted values
// (min-w-36 origin-top-left on Content) — the exact same substitution ##
// select's own ADAPT entry documents for SelectContent's
// min-w-[8rem]->min-w-36. List keeps the FIRST arm of its own min() (the
// only one that doesn't depend on the dropped var) rather than collapsing
// to a flat max-h-72: max-h-72 alone is 288px, but spacing(72)-spacing(9)
// is 252px — a real, review-caught difference (a prior draft's flat
// max-h-72 clipped the bottom ~40px of a full list against ComboboxContent's
// own max-h-72 + overflow-hidden with no way to scroll to it). duration-100
// (nova's one-off value for this component) is dropped the same way ##
// select's own entry rejects it: duration-150 is the popover family's
// shared standard, supplied by the discrete-transition block below.

//line combobox.gsx:93:1
func Combobox(name string, value string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line combobox.gsx:94:2
		_gsxgw.S("<div")
		if !attrs.Has("data-gsxui-combobox") {
			_gsxgw.BoolAttr("data-gsxui-combobox", true)
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("contents"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-combobox"})
		_gsxgw.BoolAttr("data-gsxui-slot-combobox", true)
		_gsxgw.S(">")
//line combobox.gsx:95:3
		_gsxgw.Node(ctx, children)
//line combobox.gsx:96:3
		if name != "" {
//line combobox.gsx:97:4
			_gsxgw.S("<input")
			_gsxgw.BoolAttr("data-gsxui-combobox-bridge", true)
			_gsxgw.S(" aria-hidden=\"true\" tabindex=\"-1\" type=\"text\" name=\"")
			_gsxgw.AttrValue(string(name))
			_gsxgw.S("\" value=\"")
			_gsxgw.AttrValue(string(value))
			_gsxgw.S("\"")
			_gsxgw.BoolAttr("data-gsxui-slot-combobox-bridge", true)
			_gsxgw.S(">")
		}
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line combobox.gsx:110:1
// ComboboxInput composes ui.InputGroup/ui.InputGroupInput/ui.InputGroupAddon
// directly, and calls ComboboxClear (not a nested InputGroupButton) for the
// clear button, but INLINES the trigger button rather than calling
// ComboboxTrigger: shadcn's own source polymorphically merges
// ComboboxTrigger's props onto InputGroupButton's own <button> via Base
// UI's `render` prop (one DOM button, two logical components layered on
// it) — gsx has no clone-element merge, so nesting ComboboxTrigger's own
// (independently real) <button> inside another button-producing call would
// emit an invalid button-in-button. ComboboxClear has no such conflict:
// per the source map, ComboboxClear itself is ALWAYS composed of
// InputGroupButton (`render={<InputGroupButton variant="ghost"
// size="icon-xs" />}`, "no base class of its own at all, purely a merge
// passthrough") — it never independently renders a bare <button> the way
// ComboboxTrigger's own standalone shape does — so calling it here produces
// exactly one <button>, not two. See ComboboxTrigger's and ComboboxClear's
// own doc comments below.
//
// InputGroupInput keeps its OWN default generic input-control slot hook
// (not overridden): ui/input-group.gsx's InputGroup keys its focus ring off
// that descendant hook's focus-visible state — overriding the slot
// here (an earlier draft of this port did, to `"input-group-input"`, before
// review) silently killed the only focus indicator on the control, a WCAG
// 2.4.7 failure. showTrigger/showClear are independent booleans: both true
// renders both buttons, with the trigger hidden by the input group's
// clear-button descendant condition whenever a clear button is also present
// (clear wins visually), matching shadcn's own
// composition table exactly (source map ## combobox §2).
//
// aria-haspopup="listbox" is a permanent, server-rendered fact (APG expects
// it present regardless of open/closed state); aria-controls is the
// counterpart JS stamps once at init (also permanent — see combobox.js's
// own init()), pointing at ComboboxList's id.
//
// ADAPT (attrs split class vs. everything else, matching source's own
// `{className, ...props}` destructure): the source sends `className` into
// `cn("w-auto", className)` on InputGroup, and spreads every OTHER extra
// prop (`...props`) onto the input itself. gsx's attrs bag doesn't
// destructure on its own, so this port does it explicitly — the same
// class/rest split ui/native-select.gsx's own wrapper-vs-control doc
// comment documents (attrs.Class() to the wrapper, attrs.Without("class")
// to the control): a caller's `class="w-[220px]"` sizes the InputGroup
// (merged with the "w-auto" default via the usual tailwind-merge
// precedence), while `id`/`aria-invalid`/etc. land on the actual `<input>`,
// e.g. for a <label for> pairing (site/examples/combobox/form.gsx).

//line combobox.gsx:154:1
func ComboboxInput(placeholder string, showTrigger bool, showClear bool, disabled bool, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line combobox.gsx:155:2
		var wrapperAttrs gsx.Attrs
		if class, ok := attrs.Get("class"); ok {
			wrapperAttrs = gsx.Attrs{{Key: "class", Value: class}}
		}
//line combobox.gsx:161:2
		_gsxgw.NodeResult(_gsxrenderInputGroup(ctx, _gsxgw, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line combobox.gsx:167:3
			_gsxgw.NodeResult(_gsxrenderInputGroupInput(ctx, _gsxgw, _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "data-gsxui-combobox-input", Value: _gsxrt.Toggle(true)}}, _gsxrt.Attrs{{Key: "type", Value: "text"}}, _gsxrt.Attrs{{Key: "role", Value: "combobox"}}, _gsxrt.Attrs{{Key: "aria-expanded", Value: "false"}}, _gsxrt.Attrs{{Key: "aria-haspopup", Value: "listbox"}}, _gsxrt.Attrs{{Key: "aria-autocomplete", Value: "list"}}, _gsxrt.Attrs{{Key: "autocomplete", Value: "off"}}, _gsxrt.Attrs{{Key: "spellcheck", Value: "false"}}, _gsxrt.Attrs{{Key: "placeholder", Value: placeholder}}, _gsxrt.Attrs{{Key: "disabled", Value: disabled}}, attrs.Without("class"), _gsxrt.Attrs{{Key: "data-gsxui-slot-combobox-input", Value: _gsxrt.Toggle(true)}})))
//line combobox.gsx:181:3
			_gsxgw.NodeResult(_gsxrenderInputGroupAddon(ctx, _gsxgw, "inline-end", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line combobox.gsx:182:4
				if showTrigger {
//line combobox.gsx:183:5
					_gsxgw.NodeResult(_gsxrenderInputGroupButton(ctx, _gsxgw, "ghost", "icon-xs", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line combobox.gsx:193:6
						_gsxgw.Node(ctx, icon.ChevronDown(_gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.Class("pointer-events-none size-4 text-muted-foreground"))}}, _gsxrt.Attrs{{Key: "data-gsxui-slot-combobox-trigger-icon", Value: _gsxrt.Toggle(true)}})...))
						return _gsxgw.Err()
					}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "data-gsxui-combobox-trigger", Value: _gsxrt.Toggle(true)}}, _gsxrt.Attrs{{Key: "disabled", Value: disabled}}, _gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.Class("[&_svg:not([class*='size-'])]:size-4 [[data-gsxui-slot-input-group]:has([data-gsxui-slot-combobox-clear])_&]:hidden"))}}, _gsxrt.Attrs{{Key: "data-gsxui-slot-combobox-trigger", Value: _gsxrt.Toggle(true)}})))
				}
//line combobox.gsx:199:4
				if showClear {
//line combobox.gsx:200:5
					_gsxgw.NodeResult(_gsxrenderComboboxClear(ctx, _gsxgw, _gsxrt.Attrs{{Key: "disabled", Value: disabled}}))
				}
				return _gsxgw.Err()
			}), nil))
//line combobox.gsx:203:3
			_gsxgw.Node(ctx, children)
			return _gsxgw.Err()
		}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "data-gsxui-combobox-input-group", Value: _gsxrt.Toggle(true)}}, _gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.Class("w-auto"))}}, wrapperAttrs, _gsxrt.Attrs{{Key: "data-gsxui-slot-combobox-input-group", Value: _gsxrt.Toggle(true)}})))
		return _gsxgw.Err()
	})
}

//line combobox.gsx:207:1
// ComboboxTrigger is the standalone chevron-toggle button — used directly
// only by the "trigger a popup from a button" composition variant (combobox
// composed with a ui.Button and the search input moved inside
// ComboboxContent instead of ComboboxInput's own addon; out of this port's
// shipped examples, see the GAP list above). ComboboxInput's own addon does
// NOT call this — see its doc comment for why.

//line combobox.gsx:213:1
func ComboboxTrigger(attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line combobox.gsx:214:2
		_gsxgw.S("<button")
		if !attrs.Has("type") {
			_gsxgw.S(" type=\"button\"")
		}
		if !attrs.Has("data-gsxui-combobox-trigger") {
			_gsxgw.BoolAttr("data-gsxui-combobox-trigger", true)
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("[&_svg:not([class*='size-'])]:size-4 [[data-gsxui-slot-input-group]:has([data-gsxui-slot-combobox-clear])_&]:hidden"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "button", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-combobox-trigger"})
		_gsxgw.BoolAttr("data-gsxui-slot-combobox-trigger", true)
		_gsxgw.S(">")
//line combobox.gsx:223:3
		_gsxgw.Node(ctx, icon.ChevronDown(_gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.Class("pointer-events-none size-4 text-muted-foreground"))}}, _gsxrt.Attrs{{Key: "data-gsxui-slot-combobox-trigger-icon", Value: _gsxrt.Toggle(true)}})...))
		_gsxgw.S("</button>")
		return _gsxgw.Err()
	})
}

//line combobox.gsx:230:1
// ComboboxClear composes ui.InputGroupButton (variant="ghost"
// size="icon-xs") directly — per the source map, this part is ALWAYS an
// InputGroupButton composition (no independent bare-button shape the way
// ComboboxTrigger has), "no base class of its own at all, purely a merge
// passthrough" (`cn(className)` in the source). A prior draft of this port
// gave it its own `[&_svg:not(size-)]:size-4` class and a hand-rolled
// <button>, which both diverged from the source AND left a standalone
// `<ui.ComboboxClear/>` completely unstyled — fixed in review. Safe for
// ComboboxInput's own addon to call directly (see its doc comment): unlike
// ComboboxTrigger, this never independently emits a bare <button> that
// could nest inside another one.
// disabled has no declared param — the brief's own signature is
// `ComboboxClear(attrs gsx.Attrs)` only, matching source's plain
// `{...props}` spread (Base UI's Combobox has no explicit `disabled` prop
// on this part either). ComboboxInput passes its own `disabled` bool
// through the attrs bag (`disabled={disabled}` as a plain non-parameter
// attribute), which InputGroupButton forwards to ui.Button's own typed
// `disabled` param the same way — the established override mechanism (see
// ui/input-group.gsx's InputGroupButton composition contract).

//line combobox.gsx:249:1
func ComboboxClear(attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderComboboxClear(ctx, _gsxgw, attrs)
	})
}

func _gsxrenderComboboxClear(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line combobox.gsx:250:2
	_gsxgw.NodeResult(_gsxrenderInputGroupButton(ctx, _gsxgw, "ghost", "icon-xs", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line combobox.gsx:258:3
		_gsxgw.Node(ctx, icon.X())
		return _gsxgw.Err()
	}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "data-gsxui-combobox-clear", Value: _gsxrt.Toggle(true)}}, _gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.Class("[&>svg]:pointer-events-none"))}}, attrs, _gsxrt.Attrs{{Key: "data-gsxui-slot-combobox-clear", Value: _gsxrt.Toggle(true)}})))
	return _gsxgw.Err()
}

//line combobox.gsx:262:1
// ComboboxContent is the popover listbox surface. See the package doc
// comment for the popover-machinery MECHANISM and the CSS-var-drop ADAPT.
// ComboboxContent is the named ancestor targeted by ComboboxEmpty's
// empty-state visibility rule;
// combobox.js stamps data-empty on this element (and, separately, on
// ComboboxList, whose own data-empty:p-0 selector is a different
// attribute-presence target) whenever a filter pass leaves zero visible
// items. ring-1 ring-foreground/10 (not border) is the shadcn source's own
// original token here, not a nova border->ring swap to reject — new-york-v4
// never had a border on this part (source map ## combobox §1).

//line combobox.gsx:272:1
func ComboboxContent(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line combobox.gsx:273:2
		_gsxgw.S("<div")
		if !attrs.Has("data-gsxui-combobox-content") {
			_gsxgw.BoolAttr("data-gsxui-combobox-content", true)
		}
		if !attrs.Has("popover") {
			_gsxgw.S(" popover=\"auto\"")
		}
		if !attrs.Has("data-state") {
			_gsxgw.S(" data-state=\"closed\"")
		}
		if !attrs.Has("data-side") {
			_gsxgw.S(" data-side=\"bottom\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("relative z-50 max-h-72 min-w-36 origin-top-left overflow-hidden rounded-lg bg-popover text-popover-foreground shadow-md ring-1 ring-foreground/10 opacity-0 scale-95 transition-[opacity,scale,translate,display,overlay] transition-discrete duration-150 [&:popover-open]:opacity-100 [&:popover-open]:scale-100 starting:[&:popover-open]:opacity-0 starting:[&:popover-open]:scale-95 starting:[&:popover-open]:data-[side=bottom]:-translate-y-2 starting:[&:popover-open]:data-[side=left]:translate-x-2 starting:[&:popover-open]:data-[side=right]:-translate-x-2 starting:[&:popover-open]:data-[side=top]:translate-y-2"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-combobox-content"})
		_gsxgw.BoolAttr("data-gsxui-slot-combobox-content", true)
		_gsxgw.S(">")
//line combobox.gsx:284:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line combobox.gsx:288:1
// ComboboxList is the scrolling item container (unlike ui.Select, which has
// no separate list part — SelectContent itself scrolls — Combobox's List is
// its own element, matching the raw source's own separate part). role and
// tabindex="-1" implement the WAI-ARIA combobox pattern's listbox half;
// combobox.js never moves real focus here (command.js's model — see the
// package doc comment), only stamps data-highlighted on the current item
// and aria-activedescendant on the INPUT. data-empty:p-0 collapses this
// element's own padding when combobox.js reports zero visible items (a
// second, independent data-empty target from ComboboxContent's own group
// selector — see ComboboxContent's doc comment).
//
// max-h-[calc(--spacing(72)---spacing(9))]: the source/nova token is
// `max-h-[min(calc(--spacing(72)---spacing(9)),calc(var(--available-height)-
// -spacing(9)))]` — a min() of two arms, the second depending on the
// --available-height var this port's fixed-positioning ADAPT never sets
// (see the package doc comment). Only the FIRST arm survives; a flat
// `max-h-72` (a prior draft's mistake, caught in review) is a DIFFERENT,
// larger number — 288px vs. this arm's 252px (spacing(72) minus
// spacing(9), i.e. 18rem - 2.25rem at the default --spacing: 0.25rem) —
// and clips the last ~40px of a full list against ComboboxContent's own
// max-h-72 + overflow-hidden with no way to scroll to it.

//line combobox.gsx:309:1
func ComboboxList(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line combobox.gsx:310:2
		_gsxgw.S("<div")
		if !attrs.Has("data-gsxui-combobox-list") {
			_gsxgw.BoolAttr("data-gsxui-combobox-list", true)
		}
		if !attrs.Has("role") {
			_gsxgw.S(" role=\"listbox\"")
		}
		if !attrs.Has("tabindex") {
			_gsxgw.S(" tabindex=\"-1\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("max-h-[calc(--spacing(72)---spacing(9))] scroll-py-1 overflow-y-auto p-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden data-empty:p-0"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-combobox-list"})
		_gsxgw.BoolAttr("data-gsxui-slot-combobox-list", true)
		_gsxgw.S(">")
//line combobox.gsx:320:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line combobox.gsx:324:1
// ComboboxItem is one option. value is the form/filter value (data-value,
// synced into the hidden bridge on commit); selected server-renders the
// initial pick. Two attributes track two different facts, the same split
// ## select documents for SelectItem: data-state="checked"|"unchecked"
// tracks the VALUE alone and drives the checkmark's CSS visibility
// through the same checked-state ancestor gate that
// mount-gating-in-CSS MECHANISM ## select's own entry names); aria-selected
// tracks the value too here (NOT isValue&&isFocused like Select's own
// aria-selected — Combobox's separate highlight cursor is
// data-highlighted + the input's aria-activedescendant, a materially
// different split since focus never leaves the input). Items are never tab
// stops (command.js's model): no tabindex is stamped at all.

//line combobox.gsx:336:1
func ComboboxItem(value string, selected bool, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line combobox.gsx:337:2
		_gsxgw.S("<div")
		if !attrs.Has("data-gsxui-combobox-item") {
			_gsxgw.BoolAttr("data-gsxui-combobox-item", true)
		}
		if !attrs.Has("role") {
			_gsxgw.S(" role=\"option\"")
		}
		if !attrs.Has("data-value") {
			_gsxgw.S(" data-value=\"")
			_gsxgw.AttrValue(string(value))
			_gsxgw.S("\"")
		}
		if selected {
			if !attrs.Has("data-state") {
				_gsxgw.S(" data-state=\"checked\"")
			}
		} else {
			if !attrs.Has("data-state") {
				_gsxgw.S(" data-state=\"unchecked\"")
			}
		}
		if !attrs.Has("aria-selected") {
			_gsxgw.S(" aria-selected=\"")
			_gsxgw.S(_gsxsc.FormatBool(bool(selected)))
			_gsxgw.S("\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("relative flex w-full cursor-default items-center gap-2 rounded-md py-1 pr-8 pl-1.5 text-sm outline-hidden select-none data-[highlighted=true]:bg-accent data-[highlighted=true]:text-accent-foreground data-disabled:pointer-events-none [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 data-[state=checked]:[&>[data-gsxui-slot-combobox-item-indicator]]:flex"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-combobox-item"})
		_gsxgw.BoolAttr("data-gsxui-slot-combobox-item", true)
		_gsxgw.S(">")
//line combobox.gsx:353:3
		_gsxgw.Node(ctx, children)
//line combobox.gsx:354:3
		_gsxgw.S("<span")
		_gsxgw.BoolAttr("data-gsxui-combobox-item-indicator", true)
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("pointer-events-none absolute right-2 hidden size-4 items-center justify-center [&>svg]:size-4 pointer-coarse:[&>svg]:size-5"))
		_gsxgw.S("\"")
		_gsxgw.BoolAttr("data-gsxui-slot-combobox-item-indicator", true)
		_gsxgw.S(">")
//line combobox.gsx:361:4
		_gsxgw.Node(ctx, icon.Check())
		_gsxgw.S("</span></div>")
		return _gsxgw.Err()
	})
}

//line combobox.gsx:366:1
// ComboboxGroup wraps a set of items under a ComboboxLabel — real structural
// parts, not a native <optgroup> collapse, the same call ## select makes
// for SelectGroup/SelectLabel (a custom listbox can hold an arbitrary
// styled label child; a native <select> can't). combobox.js wires
// aria-labelledby to the contained ComboboxLabel's generated id at init,
// mirroring select.js's own group-labelling MECHANISM exactly.

//line combobox.gsx:372:1
func ComboboxGroup(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line combobox.gsx:373:2
		_gsxgw.S("<div")
		if !attrs.Has("data-gsxui-combobox-group") {
			_gsxgw.BoolAttr("data-gsxui-combobox-group", true)
		}
		if !attrs.Has("role") {
			_gsxgw.S(" role=\"group\"")
		}
		_gsxgw.ClassMerged(_gsxcm.Merge, attrs.Class())
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-combobox-group"})
		_gsxgw.BoolAttr("data-gsxui-slot-combobox-group", true)
		_gsxgw.S(">")
//line combobox.gsx:373:90
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line combobox.gsx:376:1
// ComboboxLabel is the group heading. pointer-coarse: variants are a real
// new (non-metric) addition nova's own CSS carries for this part — ported
// verbatim, not a retarget.

//line combobox.gsx:379:1
func ComboboxLabel(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line combobox.gsx:380:2
		_gsxgw.S("<div")
		if !attrs.Has("data-gsxui-combobox-label") {
			_gsxgw.BoolAttr("data-gsxui-combobox-label", true)
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("px-2 py-1.5 text-xs text-muted-foreground pointer-coarse:px-3 pointer-coarse:py-2 pointer-coarse:text-sm"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-combobox-label"})
		_gsxgw.BoolAttr("data-gsxui-slot-combobox-label", true)
		_gsxgw.S(">")
//line combobox.gsx:386:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line combobox.gsx:390:1
// ComboboxEmpty is server-rendered hidden; combobox.js reveals it via the
// content ancestor's empty-state selector when a filter pass leaves
// zero visible items — see ComboboxContent's own doc comment for exactly
// which element combobox.js stamps data-empty on.

//line combobox.gsx:394:1
func ComboboxEmpty(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line combobox.gsx:395:2
		_gsxgw.S("<div")
		if !attrs.Has("data-gsxui-combobox-empty") {
			_gsxgw.BoolAttr("data-gsxui-combobox-empty", true)
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("hidden w-full justify-center py-2 text-center text-sm text-muted-foreground [[data-gsxui-slot-combobox-content][data-empty]_&]:flex"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-combobox-empty"})
		_gsxgw.BoolAttr("data-gsxui-slot-combobox-empty", true)
		_gsxgw.S(">")
//line combobox.gsx:403:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line combobox.gsx:407:1
// ComboboxSeparator divides groups. aria-hidden, matching ## select's own
// SelectSeparator (a decorative rule, not a role="separator").

//line combobox.gsx:409:1
func ComboboxSeparator(attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line combobox.gsx:410:2
		_gsxgw.S("<div")
		if !attrs.Has("data-gsxui-combobox-separator") {
			_gsxgw.BoolAttr("data-gsxui-combobox-separator", true)
		}
		if !attrs.Has("aria-hidden") {
			_gsxgw.S(" aria-hidden=\"true\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("-mx-1 my-1 h-px bg-border"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, "div", attrs, _gsxrt.AttrSinks{}, []string{"class", "style", "data-gsxui-slot-combobox-separator"})
		_gsxgw.BoolAttr("data-gsxui-slot-combobox-separator", true)
		_gsxgw.S("></div>")
		return _gsxgw.Err()
	})
}
