// Code generated by gsx; DO NOT EDIT.

package alert

import (
	_gsxctx "context"
	_gsxrt "github.com/gsxhq/gsx"
	uialert "github.com/gsxhq/gsxui/ui/alert"
	uiicon "github.com/gsxhq/gsxui/ui/icon"
	_gsxio "io"
)

// Basic renders a default Alert with an icon, title, and description.

//line basic.gsx:10:1
func Basic() _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:11:2
		_gsxgw.Node(ctx, uialert.Alert("", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line basic.gsx:12:3
			_gsxgw.Node(ctx, uiicon.Terminal())
//line basic.gsx:13:3
			_gsxgw.Node(ctx, uialert.AlertTitle(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("Heads up!")
				return _gsxgw.Err()
			}), nil))
//line basic.gsx:14:3
			_gsxgw.Node(ctx, uialert.AlertDescription(_gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
				_gsxgw.S("You can add components to your app using the CLI.")
				return _gsxgw.Err()
			}), nil))
			return _gsxgw.Err()
		}), nil))
		return _gsxgw.Err()
	})
}
