// Code generated by gsx; DO NOT EDIT.

package ui

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxcm "github.com/gsxhq/gsxui/merge"
	_gsxio "io"
)

//line alert-dialog.gsx:5:1
// AlertDialog composes Dialog's native top-layer and state machinery while
// opting out of backdrop light dismissal.

//line alert-dialog.gsx:7:1
func AlertDialog(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line alert-dialog.gsx:8:2
		_gsxgw.NodeResult(_gsxrenderDialog(ctx, _gsxgw, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line alert-dialog.gsx:8:49
			_gsxgw.Node(ctx, children)
			return _gsxgw.Err()
		}), withSlot("alert-dialog", attrs)))
		return _gsxgw.Err()
	})
}

//line alert-dialog.gsx:11:1
func AlertDialogTrigger(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line alert-dialog.gsx:12:2
		_gsxv0 := withSlot("alert-dialog-trigger", attrs)
		_gsxgw.S("<button")
		if !_gsxv0.Has("data-gsxui-dialog-trigger") {
			_gsxgw.BoolAttr("data-gsxui-dialog-trigger", true)
		}
		if !_gsxv0.Has("type") {
			_gsxgw.S(" type=\"button\"")
		}
		if !_gsxv0.Has("aria-haspopup") {
			_gsxgw.S(" aria-haspopup=\"dialog\"")
		}
		if !_gsxv0.Has("aria-expanded") {
			_gsxgw.S(" aria-expanded=\"false\"")
		}
		_gsxgw.ClassMerged(_gsxcm.Merge, _gsxv0.Class())
		_gsxgw.StyleMerged("", _gsxv0.Style())
		_gsxgw.Spread(ctx, _gsxv0, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line alert-dialog.gsx:19:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</button>")
		return _gsxgw.Err()
	})
}

//line alert-dialog.gsx:23:1
func AlertDialogContent(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line alert-dialog.gsx:24:2
		_gsxgw.NodeResult(_gsxrenderDialogContent(ctx, _gsxgw, true, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line alert-dialog.gsx:30:3
			_gsxgw.Node(ctx, children)
			return _gsxgw.Err()
		}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "role", Value: "alertdialog"}}, _gsxrt.Attrs{{Key: "data-gsxui-dialog-static", Value: true}}, withSlot("alert-dialog-content", attrs))))
		return _gsxgw.Err()
	})
}

//line alert-dialog.gsx:34:1
func AlertDialogHeader(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line alert-dialog.gsx:35:2
		_gsxv1 := withSlot("alert-dialog-header", attrs)
		_gsxgw.S("<div")
		_gsxgw.ClassMerged(_gsxcm.Merge, _gsxv1.Class())
		_gsxgw.StyleMerged("", _gsxv1.Style())
		_gsxgw.Spread(ctx, _gsxv1, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line alert-dialog.gsx:35:53
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line alert-dialog.gsx:38:1
func AlertDialogFooter(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line alert-dialog.gsx:39:2
		_gsxv2 := withSlot("alert-dialog-footer", attrs)
		_gsxgw.S("<div")
		_gsxgw.ClassMerged(_gsxcm.Merge, _gsxv2.Class())
		_gsxgw.StyleMerged("", _gsxv2.Style())
		_gsxgw.Spread(ctx, _gsxv2, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line alert-dialog.gsx:39:53
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line alert-dialog.gsx:42:1
func AlertDialogTitle(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line alert-dialog.gsx:43:2
		_gsxv3 := withSlot("alert-dialog-title", attrs)
		_gsxgw.S("<h2")
		if !_gsxv3.Has("data-gsxui-dialog-title") {
			_gsxgw.BoolAttr("data-gsxui-dialog-title", true)
		}
		_gsxgw.ClassMerged(_gsxcm.Merge, _gsxv3.Class())
		_gsxgw.StyleMerged("", _gsxv3.Style())
		_gsxgw.Spread(ctx, _gsxv3, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line alert-dialog.gsx:43:75
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</h2>")
		return _gsxgw.Err()
	})
}

//line alert-dialog.gsx:46:1
func AlertDialogDescription(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line alert-dialog.gsx:47:2
		_gsxv4 := withSlot("alert-dialog-description", attrs)
		_gsxgw.S("<p")
		if !_gsxv4.Has("data-gsxui-dialog-description") {
			_gsxgw.BoolAttr("data-gsxui-dialog-description", true)
		}
		_gsxgw.ClassMerged(_gsxcm.Merge, _gsxv4.Class())
		_gsxgw.StyleMerged("", _gsxv4.Style())
		_gsxgw.Spread(ctx, _gsxv4, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line alert-dialog.gsx:47:86
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</p>")
		return _gsxgw.Err()
	})
}

//line alert-dialog.gsx:50:1
func AlertDialogAction(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line alert-dialog.gsx:51:2
		_gsxgw.NodeResult(_gsxrenderButton(ctx, _gsxgw, "", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line alert-dialog.gsx:51:80
			_gsxgw.Node(ctx, children)
			return _gsxgw.Err()
		}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "data-gsxui-dialog-close", Value: true}}, withSlot("alert-dialog-action", attrs))))
		return _gsxgw.Err()
	})
}

//line alert-dialog.gsx:54:1
func AlertDialogCancel(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line alert-dialog.gsx:55:2
		_gsxgw.NodeResult(_gsxrenderButton(ctx, _gsxgw, "outline", "", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line alert-dialog.gsx:60:3
			_gsxgw.Node(ctx, children)
			return _gsxgw.Err()
		}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "data-gsxui-dialog-close", Value: true}}, withSlot("alert-dialog-cancel", attrs))))
		return _gsxgw.Err()
	})
}
