// Code generated by gsx; DO NOT EDIT.

package ui

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxcm "github.com/gsxhq/gsxui/merge"
	_gsxio "io"
)

//line aspect-ratio.gsx:5:1
// AspectRatio is the shadcn/ui AspectRatio. shadcn's version is a bare
// passthrough onto Radix's AspectRatioPrimitive.Root, which renders two
// nested divs: an outer one sized by the padding-bottom-percentage hack
// (position:relative; width:100%; padding-bottom:calc(100% / ratio), ratio
// set via inline style from a numeric `ratio` prop) and an inner one
// (position:absolute; inset:0) holding the actual children. This port
// replaces that whole mechanism with the CSS `aspect-ratio` property
// (ADAPT — see docs/jsx-parity.md) directly on a single div: no padding
// hack, no wrapper-within-wrapper, and no numeric-ratio-to-percentage
// arithmetic to reproduce. ratio is a string, not a float, so callers write
// the same expression the CSS property itself accepts, e.g. ratio="16 / 9"
// (aspect-ratio also accepts a bare number, ratio="1.5").
//
// gsx.RawCSS(ratio) opts the composed value out of gw's CSS value filter
// (MECHANISM): that filter is a conservative, character-blocklist port of
// html/template's CSS sanitizer and rejects "/" outright (also "(", ")",
// ";", and several others that never appear in a valid aspect-ratio value
// either) — but "/" is not incidental punctuation here, it is
// aspect-ratio's own required <width> "/" <height> separator, so no value
// most callers would ever write could pass the filter unmodified. ratio is
// trusted, developer-authored layout intent, the same trust boundary every
// ui/*.gsx component already extends to its own class strings (Tailwind's
// class attribute receives no injection filtering either) — not sanitized
// end-user request data.

//line aspect-ratio.gsx:29:1
func AspectRatio(ratio string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line aspect-ratio.gsx:30:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"aspect-ratio\"")
		}
		_gsxgw.ClassMerged(_gsxcm.Merge, attrs.Class())
		if attrs.Has("style") {
			_gsxgw.StyleMerged(_gsxrt.StyleString(_gsxrt.Class(_gsxrt.StyleValue("aspect-ratio: "+gsx.RawCSS(ratio)))), attrs.Style())
		} else {
			_gsxgw.S(" style=\"")
			_gsxgw.Style(_gsxrt.Class(_gsxrt.StyleValue("aspect-ratio: " + gsx.RawCSS(ratio))))
			_gsxgw.S("\"")
		}
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line aspect-ratio.gsx:31:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}
