// Code generated by gsx; DO NOT EDIT.

package ui

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxstd "github.com/gsxhq/gsx/std"
	_gsxcm "github.com/gsxhq/gsxui/merge"
	"github.com/gsxhq/gsxui/ui/icon"
	_gsxio "io"
)

//line carousel.gsx:8:1
// Carousel and its parts are the shadcn/ui Carousel (registry/new-york-v4/
// ui/carousel.tsx). shadcn's version wraps embla-carousel-react, a
// JS-transform carousel (it drags a flex track with
// `transform: translate3d(...)`, driven by its own pointer-physics engine —
// no CSS scroll-snap, no native `overflow: auto` anywhere). Per the roadmap's
// own decision (2026-07-24 controls source map, `## carousel`), this port
// substitutes real native CSS scroll-snap for embla entirely:
// `overflow-x-auto snap-x snap-mandatory` (or the `-y`/`snap-y` pair,
// vertical) on CarouselContent's own viewport div, `snap-start` on every
// CarouselItem, plain JS only for the prev/next buttons and disabled-state/
// current-index bookkeeping (ui/carousel.js). This is a genuine behavior
// substitution, not a strict downgrade: native scroll brings real touch/
// trackpad momentum and rubber-banding for free (a WIN embla's transform
// approach never had) but drops embla's `loop` (infinite wraparound) —
// GAP, no native-scroll analog without slide-cloning, and no docs demo
// exercises it, so it's an accepted v1 gap, not silently dropped.
//
// GAP (no context, orientation/spacing passed explicitly): Radix-less —
// there is no CarouselContext broadcasting `orientation` from Carousel down
// to CarouselContent/CarouselItem/CarouselPrevious/CarouselNext the way
// shadcn's own `useCarousel()` does. Every part that needs it takes its own
// `orientation` param instead, the same explicit-prop-instead-of-context
// shape `## toggle-group`'s groupType/variant/size/spacing already
// establishes. Spacing (embla's `-ml-4`/`pl-4` default gap, overridden to
// `-ml-1`/`pl-1` by `carousel-spacing.tsx`) stays caller-controlled via the
// ordinary class-merge mechanism — no separate spacing param, matching the
// upstream demo's own proof that gap is entirely a `className` override.

//line carousel.gsx:35:1
func Carousel(orientation string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line carousel.gsx:36:2
		_gsxgw.S("<div")
		if !attrs.Has("role") {
			_gsxgw.S(" role=\"region\"")
		}
		if !attrs.Has("aria-roledescription") {
			_gsxgw.S(" aria-roledescription=\"carousel\"")
		}
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"carousel\"")
		}
		if !attrs.Has("data-gsxui-carousel") {
			_gsxgw.BoolAttr("data-gsxui-carousel", true)
		}
		if !attrs.Has("data-orientation") {
			_gsxgw.S(" data-orientation=\"")
			_gsxgw.AttrValue(string(_gsxstd.Default((orientation), "horizontal")))
			_gsxgw.S("\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("relative"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line carousel.gsx:45:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line carousel.gsx:49:1
// CarouselContent renders BOTH divs from shadcn's own source: the outer div
// is embla's `carouselRef` viewport target, ported here as the REAL native
// scroll container (`overflow-x-auto`/`-y-auto` + `snap-x`/`snap-y
// snap-mandatory`, replacing embla's own bare `overflow-hidden` — a scroll
// container needs `overflow: auto`, not `hidden`, to scroll at all); the
// inner div stays the plain flex track shadcn's own version already has,
// `{ attrs... }` landing there exactly as it does on shadcn's own inner div
// (`carousel-spacing.tsx`'s `-ml-1` override targets this same inner div).
//
// `[scrollbar-width:none] [&::-webkit-scrollbar]:hidden` on the outer div is
// NEW — present in neither shadcn's source nor nova's own CSS — needed only
// because this port is now on a real native scroll container that would
// otherwise show a visible scrollbar embla's transform-based approach never
// had anything analogous to.

//line carousel.gsx:63:1
func CarouselContent(orientation string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line carousel.gsx:64:2
		_gsxgw.S("<div data-slot=\"carousel-content\"")
		var _gsxv0 string
		if orientation == "vertical" {
			_gsxv0 = "overflow-y-auto snap-y snap-mandatory [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"
		} else {
			_gsxv0 = "overflow-x-auto snap-x snap-mandatory [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(_gsxv0))
		_gsxgw.S("\">")
//line carousel.gsx:74:3
		_gsxgw.S("<div")
		_gsxv1 := "flex"
		var _gsxv2 string
		if orientation == "vertical" {
			_gsxv2 = "-mt-4 flex-col"
		} else {
			_gsxv2 = "-ml-4"
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(_gsxv1), _gsxrt.Class(_gsxv2), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line carousel.gsx:81:4
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div></div>")
		return _gsxgw.Err()
	})
}

//line carousel.gsx:86:1
// CarouselItem adds `snap-start` to shadcn's own class string — also NEW,
// not in shadcn's source, required for native scroll-snap to have any snap
// points at all (embla needed none: it never scrolls, it transforms).

//line carousel.gsx:89:1
func CarouselItem(orientation string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line carousel.gsx:90:2
		_gsxgw.S("<div")
		if !attrs.Has("role") {
			_gsxgw.S(" role=\"group\"")
		}
		if !attrs.Has("aria-roledescription") {
			_gsxgw.S(" aria-roledescription=\"slide\"")
		}
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"carousel-item\"")
		}
		_gsxv3 := "min-w-0 shrink-0 grow-0 basis-full snap-start"
		var _gsxv4 string
		if orientation == "vertical" {
			_gsxv4 = "pt-4"
		} else {
			_gsxv4 = "pl-4"
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(_gsxv3), _gsxrt.Class(_gsxv4), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line carousel.gsx:100:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line carousel.gsx:104:1
// CarouselPrevious/CarouselNext compose Button (variant="outline"
// size="icon") exactly like shadcn's own versions, plus
// data-gsxui-carousel-prev/-next for carousel.js's delegated click wiring.
// shadcn computes `disabled={!canScrollPrev}`/`!canScrollNext` from embla's
// live scroll-progress state, unavailable at Go render time — the initial
// server-rendered `disabled` value is chosen per button since the two are
// NOT symmetric unknowns: a freshly mounted scroll container always starts
// at `scrollLeft`/`scrollTop` 0 (a real DOM invariant, not a guess), so
// Previous genuinely has nowhere to scroll back to and starts disabled;
// whether Next has anywhere to scroll forward TO depends on rendered
// content/viewport widths carousel.gsx cannot measure, so it starts enabled
// (the permissive default — a functional button that turns out to have
// nothing to do is harmless, a disabled one that turns out to be wrong is
// not). carousel.js's own init pass recomputes and corrects both from the
// real DOM immediately on load either way — see its own header comment.

//line carousel.gsx:119:1
func CarouselPrevious(orientation string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line carousel.gsx:120:2
		_gsxv5 := "absolute size-8 rounded-full"
		var _gsxv6 string
		if orientation == "vertical" {
			_gsxv6 = "-top-12 left-1/2 -translate-x-1/2 rotate-90"
		} else {
			_gsxv6 = "top-1/2 -left-12 -translate-y-1/2"
		}
		_gsxgw.NodeResult(_gsxrenderButton(ctx, _gsxgw, "outline", "icon", "", true, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line carousel.gsx:136:3
			_gsxgw.Node(ctx, icon.ArrowLeft())
//line carousel.gsx:137:3
			_gsxgw.S("<span class=\"sr-only\">Previous slide</span>")
			return _gsxgw.Err()
		}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "data-slot", Value: "carousel-previous"}}, _gsxrt.Attrs{{Key: "data-gsxui-carousel-prev", Value: true}}, _gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.Class(_gsxv5), _gsxrt.Class(_gsxv6))}}, attrs)))
		return _gsxgw.Err()
	})
}

//line carousel.gsx:141:1
func CarouselNext(orientation string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line carousel.gsx:142:2
		_gsxv7 := "absolute size-8 rounded-full"
		var _gsxv8 string
		if orientation == "vertical" {
			_gsxv8 = "-bottom-12 left-1/2 -translate-x-1/2 rotate-90"
		} else {
			_gsxv8 = "top-1/2 -right-12 -translate-y-1/2"
		}
		_gsxgw.NodeResult(_gsxrenderButton(ctx, _gsxgw, "outline", "icon", "", false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line carousel.gsx:157:3
			_gsxgw.Node(ctx, icon.ArrowRight())
//line carousel.gsx:158:3
			_gsxgw.S("<span class=\"sr-only\">Next slide</span>")
			return _gsxgw.Err()
		}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "data-slot", Value: "carousel-next"}}, _gsxrt.Attrs{{Key: "data-gsxui-carousel-next", Value: true}}, _gsxrt.Attrs{{Key: "class", Value: _gsxrt.ClassJoin(_gsxrt.Class(_gsxv7), _gsxrt.Class(_gsxv8))}}, attrs)))
		return _gsxgw.Err()
	})
}
