// Code generated by gsx; DO NOT EDIT.

package ui

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxstd "github.com/gsxhq/gsx/std"
	_gsxcm "github.com/gsxhq/gsxui/merge"
	"github.com/gsxhq/gsxui/ui/icon"
	_gsxio "io"
)

//line command.gsx:8:1
// Command and its parts are the shadcn/ui Command (registry/new-york-v4/
// ui/command.tsx). shadcn's version wraps the cmdk React library
// (CommandPrimitive); there is no React here, so the primitive's behavior —
// score-ranked filtering, roving selection that keeps FOCUS in the input
// (aria-activedescendant, not tab focus), Enter/click activation, group
// hiding, DOM reordering by score — is reimplemented in ui/command.js,
// including a faithful port of cmdk's own ranking algorithm (command-score,
// MIT). Markup follows shadcn's data-slot structure with cmdk's private
// [cmdk-*] attribute selectors mapped onto the equivalent data-slot
// selectors (ADAPT — cmdk stamps those attributes at runtime; we own the
// markup, so the slots are the stable hooks). Nova density metrics applied
// per the 2026-07-24 retarget (rounded-xl + p-1 root, max-h-72 list).
//
// GAP: cmdk props not ported — shouldFilter/filter (custom filter fn),
// value/onValueChange (controlled selection), loop. Items opt into
// navigation with a data-href attribute (command.js assigns location);
// anything else listens for the gsxui:select CustomEvent on the item.

//line command.gsx:25:1
func Command(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderCommand(ctx, _gsxgw, children, attrs)
	})
}

func _gsxrenderCommand(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line command.gsx:26:2
	_gsxgw.S("<div")
	if !attrs.Has("data-slot") {
		_gsxgw.S(" data-slot=\"command\"")
	}
	if !attrs.Has("data-gsxui-command") {
		_gsxgw.BoolAttr("data-gsxui-command", true)
	}
	_gsxgw.S(" class=\"")
	_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("flex h-full w-full flex-col overflow-hidden rounded-xl bg-popover p-1 text-popover-foreground"), _gsxrt.Class(attrs.Class()))
	_gsxgw.S("\"")
	_gsxgw.StyleMerged("", attrs.Style())
	_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
	_gsxgw.S(">")
//line command.gsx:32:3
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</div>")
	return _gsxgw.Err()
}

//line command.gsx:36:1
// CommandDialog composes Dialog/DialogContent (so command → dialog derives
// for the CLI and dialog.js's machinery — trigger wiring, Esc, exit
// animation, backdrop — is reused whole). The sr-only header lives INSIDE
// DialogContent, unlike shadcn's outside-the-content placement: our
// dialog.js wireA11y looks the title/description up within the <dialog>
// element to stamp aria-labelledby/-describedby (an ADAPT with identical
// semantics — the text is sr-only either way).
//
// data-gsxui-command-dialog on the content is command.js's global-hotkey
// hook: ⌘K/Ctrl-K toggles the first such dialog on the page.

//line command.gsx:46:1
func CommandDialog(title string, description string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line command.gsx:47:2
		_gsxgw.NodeResult(_gsxrenderDialog(ctx, _gsxgw, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line command.gsx:48:3
			_gsxgw.NodeResult(_gsxrenderDialogContent(ctx, _gsxgw, false, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
				_gsxgw := _gsxrt.W(_gsxw)
//line command.gsx:53:4
				_gsxgw.NodeResult(_gsxrenderDialogHeader(ctx, _gsxgw, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line command.gsx:54:5
					_gsxgw.NodeResult(_gsxrenderDialogTitle(ctx, _gsxgw, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line command.gsx:54:18
						_gsxgw.Text(string(_gsxstd.Default((title), "Command Palette")))
						return _gsxgw.Err()
					}), nil))
//line command.gsx:55:5
					_gsxgw.NodeResult(_gsxrenderDialogDescription(ctx, _gsxgw, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
						_gsxgw := _gsxrt.W(_gsxw)
//line command.gsx:55:24
						_gsxgw.Text(string(_gsxstd.Default((description), "Search for a command to run...")))
						return _gsxgw.Err()
					}), nil))
					return _gsxgw.Err()
				}), _gsxrt.Attrs{{Key: "class", Value: "sr-only"}}))
//line command.gsx:57:4
				_gsxgw.NodeResult(_gsxrenderCommand(ctx, _gsxgw, _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
					_gsxgw := _gsxrt.W(_gsxw)
//line command.gsx:58:5
					_gsxgw.Node(ctx, children)
					return _gsxgw.Err()
				}), _gsxrt.Attrs{{Key: "class", Value: "**:data-[slot=command-input-wrapper]:h-12 [&_[data-slot=command-group-heading]]:px-2 [&_[data-slot=command-group-heading]]:font-medium [&_[data-slot=command-group-heading]]:text-muted-foreground [&_[data-slot=command-group]]:px-2 [&_[data-slot=command-group]:not([hidden])_~[data-slot=command-group]]:pt-0 [&_[data-slot=command-input-wrapper]_svg]:h-5 [&_[data-slot=command-input-wrapper]_svg]:w-5 [&_[data-slot=command-input]]:h-12 [&_[data-slot=command-item]]:px-2 [&_[data-slot=command-item]]:py-3 [&_[data-slot=command-item]_svg]:h-5 [&_[data-slot=command-item]_svg]:w-5"}}))
				return _gsxgw.Err()
			}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "data-gsxui-command-dialog", Value: true}}, _gsxrt.Attrs{{Key: "class", Value: "overflow-hidden p-0"}}, attrs)))
			return _gsxgw.Err()
		}), _gsxrt.Attrs{{Key: "data-slot", Value: "command-dialog"}}))
		return _gsxgw.Err()
	})
}

//line command.gsx:64:1
// CommandInput renders shadcn's search-icon-plus-input wrapper row. The
// input is the palette's single focus target: command.js filters on input,
// moves selection on ArrowUp/ArrowDown, and activates on Enter, all while
// focus stays here (aria-activedescendant tracks the selected option).

//line command.gsx:68:1
func CommandInput(placeholder string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line command.gsx:69:2
		_gsxgw.S("<div data-slot=\"command-input-wrapper\" class=\"flex h-9 items-center gap-2 border-b px-3\">")
//line command.gsx:70:3
		_gsxgw.Node(ctx, icon.Search(_gsxrt.Attrs{{Key: "class", Value: "size-4 shrink-0 opacity-50"}}...))
//line command.gsx:71:3
		_gsxgw.S("<input")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"command-input\"")
		}
		if !attrs.Has("data-gsxui-command-input") {
			_gsxgw.BoolAttr("data-gsxui-command-input", true)
		}
		if !attrs.Has("type") {
			_gsxgw.S(" type=\"text\"")
		}
		if !attrs.Has("role") {
			_gsxgw.S(" role=\"combobox\"")
		}
		if !attrs.Has("aria-expanded") {
			_gsxgw.S(" aria-expanded=\"true\"")
		}
		if !attrs.Has("aria-autocomplete") {
			_gsxgw.S(" aria-autocomplete=\"list\"")
		}
		if !attrs.Has("autocomplete") {
			_gsxgw.S(" autocomplete=\"off\"")
		}
		if !attrs.Has("spellcheck") {
			_gsxgw.S(" spellcheck=\"false\"")
		}
		if !attrs.Has("placeholder") {
			_gsxgw.S(" placeholder=\"")
			_gsxgw.AttrValue(string(placeholder))
			_gsxgw.S("\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("flex h-10 w-full rounded-md bg-transparent py-3 text-sm outline-hidden placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "xlink:href"}, []string{"background", "src"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S("></div>")
		return _gsxgw.Err()
	})
}

//line command.gsx:87:1
func CommandList(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line command.gsx:88:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"command-list\"")
		}
		if !attrs.Has("data-gsxui-command-list") {
			_gsxgw.BoolAttr("data-gsxui-command-list", true)
		}
		if !attrs.Has("role") {
			_gsxgw.S(" role=\"listbox\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("max-h-72 scroll-py-1 overflow-x-hidden overflow-y-auto"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line command.gsx:95:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line command.gsx:99:1
// CommandEmpty is server-rendered hidden; command.js reveals it when a
// query matches nothing (cmdk's Empty renders conditionally — same net
// visual, inverted mechanism since there is no VDOM to unmount).

//line command.gsx:102:1
func CommandEmpty(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line command.gsx:103:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"command-empty\"")
		}
		if !attrs.Has("hidden") {
			_gsxgw.BoolAttr("hidden", true)
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("py-6 text-center text-sm"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line command.gsx:103:86
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line command.gsx:106:1
// CommandGroup's heading is a real child div (slot command-group-heading)
// rather than cmdk's heading prop + [cmdk-group-heading] runtime stamp —
// the classes shadcn applies through the group's arbitrary selectors land
// on it via the mapped data-slot selectors (see Command's doc comment).

//line command.gsx:110:1
func CommandGroup(heading string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line command.gsx:111:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"command-group\"")
		}
		if !attrs.Has("role") {
			_gsxgw.S(" role=\"group\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("overflow-hidden p-1 text-foreground"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line command.gsx:112:3
		if heading != "" {
//line command.gsx:113:4
			_gsxgw.S("<div data-slot=\"command-group-heading\" class=\"px-2 py-1.5 text-xs font-medium text-muted-foreground\">")
//line command.gsx:113:105
			_gsxgw.Text(string(heading))
			_gsxgw.S("</div>")
		}
//line command.gsx:115:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line command.gsx:119:1
func CommandSeparator(attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line command.gsx:120:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"command-separator\"")
		}
		if !attrs.Has("role") {
			_gsxgw.S(" role=\"separator\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("-mx-1 h-px bg-border"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S("></div>")
		return _gsxgw.Err()
	})
}

//line command.gsx:123:1
// CommandItem is a role="option" div (cmdk's own role), NOT focusable —
// selection is the data-selected stamp command.js manages, focus never
// leaves the input. value seeds the match text; empty value falls back to
// the item's textContent (cmdk's own default). data-[selected=true] styling
// matches shadcn's tokens. Disable with aria-disabled="true" or a
// data-disabled attribute (skipped by filter, selection, and activation —
// the same contract as DropdownMenuItem).

//line command.gsx:130:1
func CommandItem(value string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line command.gsx:131:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"command-item\"")
		}
		if !attrs.Has("data-gsxui-command-item") {
			_gsxgw.BoolAttr("data-gsxui-command-item", true)
		}
		if !attrs.Has("data-value") {
			_gsxgw.S(" data-value=\"")
			_gsxgw.AttrValue(string(value))
			_gsxgw.S("\"")
		}
		if !attrs.Has("role") {
			_gsxgw.S(" role=\"option\"")
		}
		if !attrs.Has("aria-selected") {
			_gsxgw.S(" aria-selected=\"false\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("relative flex cursor-default items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden select-none data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 data-[selected=true]:bg-accent data-[selected=true]:text-accent-foreground [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line command.gsx:140:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line command.gsx:144:1
func CommandShortcut(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line command.gsx:145:2
		_gsxgw.S("<span")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"command-shortcut\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("ml-auto text-xs tracking-widest text-muted-foreground"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line command.gsx:146:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</span>")
		return _gsxgw.Err()
	})
}
