// Code generated by gsx; DO NOT EDIT.

package ui

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxstd "github.com/gsxhq/gsx/std"
	_gsxcm "github.com/gsxhq/gsxui/merge"
	_gsxio "io"
)

//line item.gsx:5:1
const itemBase = "group/item flex flex-wrap items-center rounded-md border border-transparent text-sm transition-colors duration-100 outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 [a]:transition-colors [a]:hover:bg-accent/50"

//line item.gsx:7:1
func ItemGroup(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:8:2
		_gsxgw.S("<div")
		if !attrs.Has("role") {
			_gsxgw.S(" role=\"list\"")
		}
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"item-group\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("group/item-group flex flex-col"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line item.gsx:9:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line item.gsx:13:1
// ItemSeparator composes ui.Separator directly (flat package, no
// re-implementation) — the item -> separator dependency internal/registry
// derives and registry_test.go pins. shadcn's own version types its props as
// React.ComponentProps<typeof Separator> and spreads {...props} after its
// explicit orientation="horizontal", so a caller-supplied orientation prop
// wins there. `orientation` here is a real Go param (not left to attrs) for
// exactly that reason: attrs is untyped fallthrough onto Separator's own
// rendered <div>, not a hook into the orientation argument compiled into the
// call to Separator, so only an explicit param can actually override it —
// same competing-defaults mechanism as ButtonGroupSeparator's own
// orientation |> default("vertical").

//line item.gsx:24:1
func ItemSeparator(orientation string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:25:2
		_gsxgw.NodeResult(_gsxrenderSeparator(ctx, _gsxgw, _gsxstd.Default((orientation), "horizontal"), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "data-slot", Value: "item-separator"}}, _gsxrt.Attrs{{Key: "class", Value: "my-0"}}, attrs)))
		return _gsxgw.Err()
	})
}

//line item.gsx:33:1
// Item's variant/size cva map (itemVariants) picks between static class
// blocks by the JS-resolved prop values — no data-[variant=...]/
// data-[size=...] selectors in registry/new-york-v4/ui/item.tsx to preserve,
// so both port as switches inside class={}, the same idiom as
// button.gsx's variantClass/sizeClass pair (here inlined, since only Item
// itself uses this pair — no sibling component shares it the way
// pagination.gsx shares button.gsx's helpers).
//
// asChild tag-swapping is dropped — always renders a <div> — the same
// narrow gap as button's own asChild (see docs/jsx-parity.md ## button).

//line item.gsx:43:1
func Item(variant string, size string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:44:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"item\"")
		}
		if !attrs.Has("data-variant") {
			_gsxgw.S(" data-variant=\"")
			_gsxgw.AttrValue(string(_gsxstd.Default((variant), "default")))
			_gsxgw.S("\"")
		}
		if !attrs.Has("data-size") {
			_gsxgw.S(" data-size=\"")
			_gsxgw.AttrValue(string(_gsxstd.Default((size), "default")))
			_gsxgw.S("\"")
		}
		_gsxv0 := itemBase
		var _gsxv1 string
		switch variant {
		case "outline":
			_gsxv1 = "border-border"
		case "muted":
			_gsxv1 = "bg-muted/50"
		default:
			_gsxv1 = "bg-transparent"
		}
		var _gsxv2 string
		switch size {
		case "sm":
			_gsxv2 = "gap-2.5 px-4 py-3"
		default:
			_gsxv2 = "gap-4 p-4"
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(_gsxv0), _gsxrt.Class(_gsxv1), _gsxrt.Class(_gsxv2), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line item.gsx:67:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line item.gsx:71:1
// ItemMedia's variant cva map (itemMediaVariants), same static-block shape
// as Item's own — ported as a switch inside class={}.

//line item.gsx:73:1
func ItemMedia(variant string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:74:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"item-media\"")
		}
		if !attrs.Has("data-variant") {
			_gsxgw.S(" data-variant=\"")
			_gsxgw.AttrValue(string(_gsxstd.Default((variant), "default")))
			_gsxgw.S("\"")
		}
		_gsxv3 := "flex shrink-0 items-center justify-center gap-2 group-has-[[data-slot=item-description]]/item:translate-y-0.5 group-has-[[data-slot=item-description]]/item:self-start [&_svg]:pointer-events-none"
		var _gsxv4 string
		switch variant {
		case "icon":
			_gsxv4 = "size-8 rounded-sm border bg-muted [&_svg:not([class*='size-'])]:size-4"
		case "image":
			_gsxv4 = "size-10 overflow-hidden rounded-sm [&_img]:size-full [&_img]:object-cover"
		default:
			_gsxv4 = "bg-transparent"
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class(_gsxv3), _gsxrt.Class(_gsxv4), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line item.gsx:90:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line item.gsx:94:1
func ItemContent(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:95:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"item-content\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("flex flex-1 flex-col gap-1 [&+[data-slot=item-content]]:flex-none"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line item.gsx:100:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line item.gsx:104:1
func ItemTitle(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:105:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"item-title\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("flex w-fit items-center gap-2 text-sm leading-snug font-medium"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line item.gsx:110:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line item.gsx:114:1
// ItemDescription renders a real <p>, matching shadcn's own source exactly
// (unlike EmptyDescription, whose type says "p" but whose element is a
// <div> — see empty.gsx).

//line item.gsx:117:1
func ItemDescription(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:118:2
		_gsxgw.S("<p")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"item-description\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("line-clamp-2 text-sm leading-normal font-normal text-balance text-muted-foreground [&>a]:underline [&>a]:underline-offset-4 [&>a:hover]:text-primary"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line item.gsx:123:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</p>")
		return _gsxgw.Err()
	})
}

//line item.gsx:127:1
func ItemActions(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:128:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"item-actions\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("flex items-center gap-2"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line item.gsx:129:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line item.gsx:133:1
func ItemHeader(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:134:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"item-header\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("flex basis-full items-center justify-between gap-2"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line item.gsx:139:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}

//line item.gsx:143:1
func ItemFooter(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line item.gsx:144:2
		_gsxgw.S("<div")
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"item-footer\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("flex basis-full items-center justify-between gap-2"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line item.gsx:149:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</div>")
		return _gsxgw.Err()
	})
}
