// Code generated by gsx; DO NOT EDIT.

package ui

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxcm "github.com/gsxhq/gsxui/merge"
	"github.com/gsxhq/gsxui/ui/icon"
	_gsxio "io"
	_gsxsc "strconv"
)

//line pagination.gsx:8:1
// Pagination and its parts are the shadcn/ui Pagination
// (registry/new-york-v4/ui/pagination.tsx) — no Radix primitive underneath;
// every part is already a plain styled element (nav/ul/li/a/span). The one
// real dependency is PaginationLink, which composes Button's stable styling
// token and reflected variant/size axes instead of duplicating presentation.
// ChevronLeft/ChevronRight/Ellipsis
// (Lucide's MoreHorizontal, see breadcrumb.gsx) come from ui/icon — the
// pagination -> icon dependency, also derived and pinned.

//line pagination.gsx:16:1
func Pagination(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pagination.gsx:17:2
		_gsxv0 := withSlot("pagination", attrs)
		_gsxgw.S("<nav")
		if !_gsxv0.Has("role") {
			_gsxgw.S(" role=\"navigation\"")
		}
		if !_gsxv0.Has("aria-label") {
			_gsxgw.S(" aria-label=\"pagination\"")
		}
		_gsxgw.ClassMerged(_gsxcm.Merge, _gsxv0.Class())
		_gsxgw.StyleMerged("", _gsxv0.Style())
		_gsxgw.Spread(ctx, _gsxv0, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line pagination.gsx:22:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</nav>")
		return _gsxgw.Err()
	})
}

//line pagination.gsx:26:1
func PaginationContent(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pagination.gsx:27:2
		_gsxv1 := withSlot("pagination-content", attrs)
		_gsxgw.S("<ul")
		_gsxgw.ClassMerged(_gsxcm.Merge, _gsxv1.Class())
		_gsxgw.StyleMerged("", _gsxv1.Style())
		_gsxgw.Spread(ctx, _gsxv1, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line pagination.gsx:28:3
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</ul>")
		return _gsxgw.Err()
	})
}

//line pagination.gsx:32:1
func PaginationItem(children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pagination.gsx:33:2
		_gsxv2 := withSlot("pagination-item", attrs)
		_gsxgw.S("<li")
		_gsxgw.ClassMerged(_gsxcm.Merge, _gsxv2.Class())
		_gsxgw.StyleMerged("", _gsxv2.Style())
		_gsxgw.Spread(ctx, _gsxv2, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line pagination.gsx:33:48
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</li>")
		return _gsxgw.Err()
	})
}

//line pagination.gsx:36:1
// PaginationLink renders the shadcn/ui PaginationLink onto a real <a>,
// composed from Button's token and axes. isActive
// selects the "outline" variant (else "ghost") and stamps data-active plus,
// when true, aria-current="page" — the conditional-attribute mechanism
// (see docs/guide "conditional attributes") standing in for shadcn's
// `aria-current={isActive ? "page" : undefined}`, an attribute entirely
// absent when false, not merely empty. size defaults to "icon"
// (PaginationLinkProps' own `size = "icon"` default), distinct from
// Button's own "default" zero-value size.

//line pagination.gsx:45:1
func PaginationLink(href string, isActive bool, size string, children gsx.Node, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
		return _gsxrenderPaginationLink(ctx, _gsxgw, href, isActive, size, children, attrs)
	})
}

func _gsxrenderPaginationLink(ctx _gsxctx.Context, _gsxgw *_gsxrt.Writer, href string, isActive bool, size string, children gsx.Node, attrs gsx.Attrs) error {
	if _gsxerr := _gsxgw.Err(); _gsxerr != nil {
		return _gsxerr
	}
//line pagination.gsx:46:2
	variant := "ghost"
	if isActive {
		variant = "outline"
	}
	if size == "" {
		size = "icon"
	}
//line pagination.gsx:55:2
	_gsxv3 := withSlot("button", withSlot("pagination-link", attrs))
	_gsxgw.S("<a")
	if isActive {
		if !_gsxv3.Has("aria-current") {
			_gsxgw.S(" aria-current=\"page\"")
		}
	}
	if !_gsxv3.Has("data-active") {
		_gsxgw.S(" data-active=\"")
		_gsxgw.S(_gsxsc.FormatBool(bool(isActive)))
		_gsxgw.S("\"")
	}
	if !_gsxv3.Has("data-variant") {
		_gsxgw.S(" data-variant=\"")
		_gsxgw.AttrValue(string(variant))
		_gsxgw.S("\"")
	}
	if !_gsxv3.Has("data-size") {
		_gsxgw.S(" data-size=\"")
		_gsxgw.AttrValue(string(size))
		_gsxgw.S("\"")
	}
	if !_gsxv3.Has("href") {
		_gsxgw.S(" href=\"")
		_gsxgw.URL(string(href))
		_gsxgw.S("\"")
	}
	_gsxgw.ClassMerged(_gsxcm.Merge, _gsxv3.Class())
	_gsxgw.StyleMerged("", _gsxv3.Style())
	_gsxgw.Spread(ctx, _gsxv3, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
	_gsxgw.S(">")
//line pagination.gsx:65:3
	_gsxgw.Node(ctx, children)
	_gsxgw.S("</a>")
	return _gsxgw.Err()
}

//line pagination.gsx:69:1
// PaginationPrevious/PaginationNext hardcode their own content (icon + a
// sm:-only label) exactly like shadcn's versions — there is no children
// slot to override it, matching React's behavior where PaginationLink's
// literal JSX children always win over anything spread from ...props.

//line pagination.gsx:73:1
func PaginationPrevious(href string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pagination.gsx:74:2
		_gsxgw.NodeResult(_gsxrenderPaginationLink(ctx, _gsxgw, href, false, "default", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line pagination.gsx:80:3
			_gsxgw.Node(ctx, icon.ChevronLeft())
//line pagination.gsx:81:3
			_gsxv4 := withSlot("pagination-previous-label", nil)
			_gsxgw.S("<span")
			_gsxgw.ClassMerged(_gsxcm.Merge, _gsxv4.Class())
			_gsxgw.StyleMerged("", _gsxv4.Style())
			_gsxgw.Spread(ctx, _gsxv4, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
			_gsxgw.S(">Previous</span>")
			return _gsxgw.Err()
		}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "aria-label", Value: "Go to previous page"}}, withSlot("pagination-previous", attrs))))
		return _gsxgw.Err()
	})
}

//line pagination.gsx:85:1
func PaginationNext(href string, attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pagination.gsx:86:2
		_gsxgw.NodeResult(_gsxrenderPaginationLink(ctx, _gsxgw, href, false, "default", _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
			_gsxgw := _gsxrt.W(_gsxw)
//line pagination.gsx:92:3
			_gsxv5 := withSlot("pagination-next-label", nil)
			_gsxgw.S("<span")
			_gsxgw.ClassMerged(_gsxcm.Merge, _gsxv5.Class())
			_gsxgw.StyleMerged("", _gsxv5.Style())
			_gsxgw.Spread(ctx, _gsxv5, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
			_gsxgw.S(">Next</span>")
//line pagination.gsx:93:3
			_gsxgw.Node(ctx, icon.ChevronRight())
			return _gsxgw.Err()
		}), _gsxrt.ConcatAttrs(_gsxrt.Attrs{{Key: "aria-label", Value: "Go to next page"}}, withSlot("pagination-next", attrs))))
		return _gsxgw.Err()
	})
}

//line pagination.gsx:97:1
func PaginationEllipsis(attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line pagination.gsx:98:2
		_gsxv6 := withSlot("pagination-ellipsis", attrs)
		_gsxgw.S("<span")
		if !_gsxv6.Has("aria-hidden") {
			_gsxgw.S(" aria-hidden=\"true\"")
		}
		_gsxgw.ClassMerged(_gsxcm.Merge, _gsxv6.Class())
		_gsxgw.StyleMerged("", _gsxv6.Style())
		_gsxgw.Spread(ctx, _gsxv6, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">")
//line pagination.gsx:102:3
		_gsxgw.Node(ctx, icon.Ellipsis())
//line pagination.gsx:103:3
		_gsxv7 := withSlot("pagination-ellipsis-label", nil)
		_gsxgw.S("<span")
		_gsxgw.ClassMerged(_gsxcm.Merge, _gsxv7.Class())
		_gsxgw.StyleMerged("", _gsxv7.Style())
		_gsxgw.Spread(ctx, _gsxv7, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "src", "xlink:href"}, []string{"background"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S(">More pages</span></span>")
		return _gsxgw.Err()
	})
}
