// Code generated by gsx; DO NOT EDIT.

package ui

import (
	_gsxctx "context"
	"github.com/gsxhq/gsx"
	_gsxrt "github.com/gsxhq/gsx"
	_gsxcm "github.com/gsxhq/gsxui/merge"
	_gsxio "io"
)

// Radio is the shadcn/ui RadioGroupItem, ported as a real native
// <input type="radio">: form-native, zero JS, browser :checked/:disabled
// truth replaces Radix's button-role + hidden-input + Indicator part
// (ledger ADAPT). shadcn's RadioGroup container (a styled grid wrapper) is
// not ported — native `name` grouping on sibling <input type="radio">
// elements already gives you the group; the layout wrapper is the caller's
// concern, same as any other flex/grid container (ledger ADAPT).
//
// Tokens are carried verbatim from RadioGroupItem (aspect-square size-4
// shrink-0 rounded-full border border-input text-primary shadow-xs
// transition-[color,box-shadow] outline-none + focus-visible/disabled/
// aria-invalid/dark tokens); appearance-none is added for the same
// mechanical reason as checkbox.
//
// The Indicator's CircleIcon child (`fill-primary`) becomes a
// checked:bg-[radial-gradient(...)] painted in currentColor — a data-URI
// can't reference the caller's CSS custom properties (--primary), but a
// currentColor gradient can, and text-primary above is what makes
// currentColor resolve to the primary color here. This is why text-primary
// stays instead of being dropped like checkbox's analogous token: it is now
// load-bearing for the dot's color, not vestigial. Same restructuring
// approach as checkbox's data-URI, different mechanism because the payload
// here is a flat fill, not an SVG path; the radial-gradient's embedded
// spaces are Tailwind's underscore escape for whitespace inside a bracketed
// arbitrary value, not literal spaces — see checkbox.gsx and
// docs/jsx-parity.md.

//line radio.gsx:31:1
func Radio(attrs gsx.Attrs) _gsxrt.Node {
	return _gsxrt.Func(func(ctx _gsxctx.Context, _gsxw _gsxio.Writer) error {
		_gsxgw := _gsxrt.W(_gsxw)
//line radio.gsx:32:2
		_gsxgw.S("<input")
		if !attrs.Has("type") {
			_gsxgw.S(" type=\"radio\"")
		}
		if !attrs.Has("data-slot") {
			_gsxgw.S(" data-slot=\"radio\"")
		}
		_gsxgw.S(" class=\"")
		_gsxgw.Class(_gsxcm.Merge, _gsxrt.Class("peer aspect-square size-4 shrink-0 appearance-none rounded-full border border-input text-primary shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 dark:bg-input/30 checked:bg-[radial-gradient(circle_closest-side,currentColor_45%,transparent_50%)]"), _gsxrt.Class(attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", attrs.Style())
		_gsxgw.Spread(ctx, attrs, []string{"action", "cite", "data", "formaction", "href", "manifest", "ping", "poster", "xlink:href"}, []string{"background", "src"}, []string{"imagesrcset", "srcset"}, nil, []string{"class", "style"})
		_gsxgw.S("/>")
		return _gsxgw.Err()
	})
}
